
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  appointments: 'appointments',
  doctors: 'doctors',
  expedients: 'expedients',
  fields: 'fields',
  hospitals: 'hospitals',
  registers: 'registers',
  weekdays: 'weekdays'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AppointmentsScalarFieldEnum = {
  id: 'id',
  email_doctor: 'email_doctor',
  email_patient: 'email_patient',
  date: 'date',
  start: 'start',
  end: 'end',
  registered: 'registered'
} as const

export type AppointmentsScalarFieldEnum = (typeof AppointmentsScalarFieldEnum)[keyof typeof AppointmentsScalarFieldEnum]


export const DoctorsScalarFieldEnum = {
  email: 'email',
  id_field: 'id_field',
  id_hospital: 'id_hospital',
  id_expedient: 'id_expedient',
  first_day: 'first_day'
} as const

export type DoctorsScalarFieldEnum = (typeof DoctorsScalarFieldEnum)[keyof typeof DoctorsScalarFieldEnum]


export const ExpedientsScalarFieldEnum = {
  id: 'id',
  duration: 'duration',
  description: 'description'
} as const

export type ExpedientsScalarFieldEnum = (typeof ExpedientsScalarFieldEnum)[keyof typeof ExpedientsScalarFieldEnum]


export const FieldsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
} as const

export type FieldsScalarFieldEnum = (typeof FieldsScalarFieldEnum)[keyof typeof FieldsScalarFieldEnum]


export const HospitalsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  street: 'street',
  number: 'number',
  district: 'district',
  cep: 'cep',
  city: 'city',
  uf: 'uf'
} as const

export type HospitalsScalarFieldEnum = (typeof HospitalsScalarFieldEnum)[keyof typeof HospitalsScalarFieldEnum]


export const RegistersScalarFieldEnum = {
  name: 'name',
  cpf: 'cpf',
  gender: 'gender',
  birth: 'birth',
  email: 'email',
  password: 'password',
  type: 'type'
} as const

export type RegistersScalarFieldEnum = (typeof RegistersScalarFieldEnum)[keyof typeof RegistersScalarFieldEnum]


export const WeekdaysScalarFieldEnum = {
  id_expedient: 'id_expedient',
  weekday: 'weekday',
  week: 'week',
  start: 'start',
  end: 'end',
  break: 'break',
  time_break: 'time_break'
} as const

export type WeekdaysScalarFieldEnum = (typeof WeekdaysScalarFieldEnum)[keyof typeof WeekdaysScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const appointmentsOrderByRelevanceFieldEnum = {
  email_doctor: 'email_doctor',
  email_patient: 'email_patient'
} as const

export type appointmentsOrderByRelevanceFieldEnum = (typeof appointmentsOrderByRelevanceFieldEnum)[keyof typeof appointmentsOrderByRelevanceFieldEnum]


export const doctorsOrderByRelevanceFieldEnum = {
  email: 'email'
} as const

export type doctorsOrderByRelevanceFieldEnum = (typeof doctorsOrderByRelevanceFieldEnum)[keyof typeof doctorsOrderByRelevanceFieldEnum]


export const expedientsOrderByRelevanceFieldEnum = {
  description: 'description'
} as const

export type expedientsOrderByRelevanceFieldEnum = (typeof expedientsOrderByRelevanceFieldEnum)[keyof typeof expedientsOrderByRelevanceFieldEnum]


export const fieldsOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description'
} as const

export type fieldsOrderByRelevanceFieldEnum = (typeof fieldsOrderByRelevanceFieldEnum)[keyof typeof fieldsOrderByRelevanceFieldEnum]


export const hospitalsOrderByRelevanceFieldEnum = {
  name: 'name',
  street: 'street',
  district: 'district',
  cep: 'cep',
  city: 'city',
  uf: 'uf'
} as const

export type hospitalsOrderByRelevanceFieldEnum = (typeof hospitalsOrderByRelevanceFieldEnum)[keyof typeof hospitalsOrderByRelevanceFieldEnum]


export const registersOrderByRelevanceFieldEnum = {
  name: 'name',
  cpf: 'cpf',
  gender: 'gender',
  email: 'email',
  password: 'password'
} as const

export type registersOrderByRelevanceFieldEnum = (typeof registersOrderByRelevanceFieldEnum)[keyof typeof registersOrderByRelevanceFieldEnum]

