
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/library"
import type * as Prisma from "../models.ts"
import { type PrismaClient } from "./class.ts"

export type * from '../models.ts'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
 * Metrics
 */
export type Metrics = runtime.Metrics
export type Metric<T> = runtime.Metric<T>
export type MetricHistogram = runtime.MetricHistogram
export type MetricHistogramBucket = runtime.MetricHistogramBucket

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 6.18.0
 * Query Engine version: 34b5a692b7bd79939a9a2c3ef97d816e749cda2f
 */
export const prismaVersion: PrismaVersion = {
  client: "6.18.0",
  engine: "34b5a692b7bd79939a9a2c3ef97d816e749cda2f"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  appointments: 'appointments',
  doctors: 'doctors',
  expedients: 'expedients',
  fields: 'fields',
  hospitals: 'hospitals',
  registers: 'registers',
  weekdays: 'weekdays'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "appointments" | "doctors" | "expedients" | "fields" | "hospitals" | "registers" | "weekdays"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    appointments: {
      payload: Prisma.$appointmentsPayload<ExtArgs>
      fields: Prisma.appointmentsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.appointmentsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.appointmentsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>
        }
        findFirst: {
          args: Prisma.appointmentsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.appointmentsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>
        }
        findMany: {
          args: Prisma.appointmentsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>[]
        }
        create: {
          args: Prisma.appointmentsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>
        }
        createMany: {
          args: Prisma.appointmentsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.appointmentsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>
        }
        update: {
          args: Prisma.appointmentsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>
        }
        deleteMany: {
          args: Prisma.appointmentsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.appointmentsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.appointmentsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$appointmentsPayload>
        }
        aggregate: {
          args: Prisma.AppointmentsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAppointments>
        }
        groupBy: {
          args: Prisma.appointmentsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AppointmentsGroupByOutputType>[]
        }
        count: {
          args: Prisma.appointmentsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AppointmentsCountAggregateOutputType> | number
        }
      }
    }
    doctors: {
      payload: Prisma.$doctorsPayload<ExtArgs>
      fields: Prisma.doctorsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.doctorsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$doctorsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.doctorsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$doctorsPayload>
        }
        findFirst: {
          args: Prisma.doctorsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$doctorsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.doctorsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$doctorsPayload>
        }
        findMany: {
          args: Prisma.doctorsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$doctorsPayload>[]
        }
        create: {
          args: Prisma.doctorsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$doctorsPayload>
        }
        createMany: {
          args: Prisma.doctorsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.doctorsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$doctorsPayload>
        }
        update: {
          args: Prisma.doctorsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$doctorsPayload>
        }
        deleteMany: {
          args: Prisma.doctorsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.doctorsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.doctorsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$doctorsPayload>
        }
        aggregate: {
          args: Prisma.DoctorsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDoctors>
        }
        groupBy: {
          args: Prisma.doctorsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DoctorsGroupByOutputType>[]
        }
        count: {
          args: Prisma.doctorsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DoctorsCountAggregateOutputType> | number
        }
      }
    }
    expedients: {
      payload: Prisma.$expedientsPayload<ExtArgs>
      fields: Prisma.expedientsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.expedientsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$expedientsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.expedientsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$expedientsPayload>
        }
        findFirst: {
          args: Prisma.expedientsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$expedientsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.expedientsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$expedientsPayload>
        }
        findMany: {
          args: Prisma.expedientsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$expedientsPayload>[]
        }
        create: {
          args: Prisma.expedientsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$expedientsPayload>
        }
        createMany: {
          args: Prisma.expedientsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.expedientsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$expedientsPayload>
        }
        update: {
          args: Prisma.expedientsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$expedientsPayload>
        }
        deleteMany: {
          args: Prisma.expedientsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.expedientsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.expedientsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$expedientsPayload>
        }
        aggregate: {
          args: Prisma.ExpedientsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateExpedients>
        }
        groupBy: {
          args: Prisma.expedientsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ExpedientsGroupByOutputType>[]
        }
        count: {
          args: Prisma.expedientsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ExpedientsCountAggregateOutputType> | number
        }
      }
    }
    fields: {
      payload: Prisma.$fieldsPayload<ExtArgs>
      fields: Prisma.fieldsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.fieldsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$fieldsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.fieldsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$fieldsPayload>
        }
        findFirst: {
          args: Prisma.fieldsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$fieldsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.fieldsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$fieldsPayload>
        }
        findMany: {
          args: Prisma.fieldsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$fieldsPayload>[]
        }
        create: {
          args: Prisma.fieldsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$fieldsPayload>
        }
        createMany: {
          args: Prisma.fieldsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.fieldsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$fieldsPayload>
        }
        update: {
          args: Prisma.fieldsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$fieldsPayload>
        }
        deleteMany: {
          args: Prisma.fieldsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.fieldsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.fieldsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$fieldsPayload>
        }
        aggregate: {
          args: Prisma.FieldsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFields>
        }
        groupBy: {
          args: Prisma.fieldsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FieldsGroupByOutputType>[]
        }
        count: {
          args: Prisma.fieldsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FieldsCountAggregateOutputType> | number
        }
      }
    }
    hospitals: {
      payload: Prisma.$hospitalsPayload<ExtArgs>
      fields: Prisma.hospitalsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.hospitalsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$hospitalsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.hospitalsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$hospitalsPayload>
        }
        findFirst: {
          args: Prisma.hospitalsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$hospitalsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.hospitalsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$hospitalsPayload>
        }
        findMany: {
          args: Prisma.hospitalsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$hospitalsPayload>[]
        }
        create: {
          args: Prisma.hospitalsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$hospitalsPayload>
        }
        createMany: {
          args: Prisma.hospitalsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.hospitalsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$hospitalsPayload>
        }
        update: {
          args: Prisma.hospitalsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$hospitalsPayload>
        }
        deleteMany: {
          args: Prisma.hospitalsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.hospitalsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.hospitalsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$hospitalsPayload>
        }
        aggregate: {
          args: Prisma.HospitalsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateHospitals>
        }
        groupBy: {
          args: Prisma.hospitalsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.HospitalsGroupByOutputType>[]
        }
        count: {
          args: Prisma.hospitalsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.HospitalsCountAggregateOutputType> | number
        }
      }
    }
    registers: {
      payload: Prisma.$registersPayload<ExtArgs>
      fields: Prisma.registersFieldRefs
      operations: {
        findUnique: {
          args: Prisma.registersFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$registersPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.registersFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$registersPayload>
        }
        findFirst: {
          args: Prisma.registersFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$registersPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.registersFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$registersPayload>
        }
        findMany: {
          args: Prisma.registersFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$registersPayload>[]
        }
        create: {
          args: Prisma.registersCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$registersPayload>
        }
        createMany: {
          args: Prisma.registersCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.registersDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$registersPayload>
        }
        update: {
          args: Prisma.registersUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$registersPayload>
        }
        deleteMany: {
          args: Prisma.registersDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.registersUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.registersUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$registersPayload>
        }
        aggregate: {
          args: Prisma.RegistersAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRegisters>
        }
        groupBy: {
          args: Prisma.registersGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RegistersGroupByOutputType>[]
        }
        count: {
          args: Prisma.registersCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RegistersCountAggregateOutputType> | number
        }
      }
    }
    weekdays: {
      payload: Prisma.$weekdaysPayload<ExtArgs>
      fields: Prisma.weekdaysFieldRefs
      operations: {
        findUnique: {
          args: Prisma.weekdaysFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$weekdaysPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.weekdaysFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$weekdaysPayload>
        }
        findFirst: {
          args: Prisma.weekdaysFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$weekdaysPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.weekdaysFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$weekdaysPayload>
        }
        findMany: {
          args: Prisma.weekdaysFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$weekdaysPayload>[]
        }
        create: {
          args: Prisma.weekdaysCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$weekdaysPayload>
        }
        createMany: {
          args: Prisma.weekdaysCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.weekdaysDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$weekdaysPayload>
        }
        update: {
          args: Prisma.weekdaysUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$weekdaysPayload>
        }
        deleteMany: {
          args: Prisma.weekdaysDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.weekdaysUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.weekdaysUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$weekdaysPayload>
        }
        aggregate: {
          args: Prisma.WeekdaysAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWeekdays>
        }
        groupBy: {
          args: Prisma.weekdaysGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WeekdaysGroupByOutputType>[]
        }
        count: {
          args: Prisma.weekdaysCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WeekdaysCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AppointmentsScalarFieldEnum = {
  id: 'id',
  email_doctor: 'email_doctor',
  email_patient: 'email_patient',
  date: 'date',
  start: 'start',
  end: 'end',
  registered: 'registered'
} as const

export type AppointmentsScalarFieldEnum = (typeof AppointmentsScalarFieldEnum)[keyof typeof AppointmentsScalarFieldEnum]


export const DoctorsScalarFieldEnum = {
  email: 'email',
  id_field: 'id_field',
  id_hospital: 'id_hospital',
  id_expedient: 'id_expedient',
  first_day: 'first_day'
} as const

export type DoctorsScalarFieldEnum = (typeof DoctorsScalarFieldEnum)[keyof typeof DoctorsScalarFieldEnum]


export const ExpedientsScalarFieldEnum = {
  id: 'id',
  duration: 'duration',
  description: 'description'
} as const

export type ExpedientsScalarFieldEnum = (typeof ExpedientsScalarFieldEnum)[keyof typeof ExpedientsScalarFieldEnum]


export const FieldsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
} as const

export type FieldsScalarFieldEnum = (typeof FieldsScalarFieldEnum)[keyof typeof FieldsScalarFieldEnum]


export const HospitalsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  street: 'street',
  number: 'number',
  district: 'district',
  cep: 'cep',
  city: 'city',
  uf: 'uf'
} as const

export type HospitalsScalarFieldEnum = (typeof HospitalsScalarFieldEnum)[keyof typeof HospitalsScalarFieldEnum]


export const RegistersScalarFieldEnum = {
  name: 'name',
  cpf: 'cpf',
  gender: 'gender',
  birth: 'birth',
  email: 'email',
  password: 'password',
  type: 'type'
} as const

export type RegistersScalarFieldEnum = (typeof RegistersScalarFieldEnum)[keyof typeof RegistersScalarFieldEnum]


export const WeekdaysScalarFieldEnum = {
  id_expedient: 'id_expedient',
  weekday: 'weekday',
  week: 'week',
  start: 'start',
  end: 'end',
  break: 'break',
  time_break: 'time_break'
} as const

export type WeekdaysScalarFieldEnum = (typeof WeekdaysScalarFieldEnum)[keyof typeof WeekdaysScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const appointmentsOrderByRelevanceFieldEnum = {
  email_doctor: 'email_doctor',
  email_patient: 'email_patient'
} as const

export type appointmentsOrderByRelevanceFieldEnum = (typeof appointmentsOrderByRelevanceFieldEnum)[keyof typeof appointmentsOrderByRelevanceFieldEnum]


export const doctorsOrderByRelevanceFieldEnum = {
  email: 'email'
} as const

export type doctorsOrderByRelevanceFieldEnum = (typeof doctorsOrderByRelevanceFieldEnum)[keyof typeof doctorsOrderByRelevanceFieldEnum]


export const expedientsOrderByRelevanceFieldEnum = {
  description: 'description'
} as const

export type expedientsOrderByRelevanceFieldEnum = (typeof expedientsOrderByRelevanceFieldEnum)[keyof typeof expedientsOrderByRelevanceFieldEnum]


export const fieldsOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description'
} as const

export type fieldsOrderByRelevanceFieldEnum = (typeof fieldsOrderByRelevanceFieldEnum)[keyof typeof fieldsOrderByRelevanceFieldEnum]


export const hospitalsOrderByRelevanceFieldEnum = {
  name: 'name',
  street: 'street',
  district: 'district',
  cep: 'cep',
  city: 'city',
  uf: 'uf'
} as const

export type hospitalsOrderByRelevanceFieldEnum = (typeof hospitalsOrderByRelevanceFieldEnum)[keyof typeof hospitalsOrderByRelevanceFieldEnum]


export const registersOrderByRelevanceFieldEnum = {
  name: 'name',
  cpf: 'cpf',
  gender: 'gender',
  email: 'email',
  password: 'password'
} as const

export type registersOrderByRelevanceFieldEnum = (typeof registersOrderByRelevanceFieldEnum)[keyof typeof registersOrderByRelevanceFieldEnum]


export const weekdaysOrderByRelevanceFieldEnum = {
  weekday: 'weekday'
} as const

export type weekdaysOrderByRelevanceFieldEnum = (typeof weekdaysOrderByRelevanceFieldEnum)[keyof typeof weekdaysOrderByRelevanceFieldEnum]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}


export type Datasource = {
  url?: string
}
export type Datasources = {
  db?: Datasource
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export interface PrismaClientOptions {
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasources?: Datasources
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasourceUrl?: string
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging#the-log-option).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-planetscale`
   */
  adapter?: runtime.SqlDriverAdapterFactory | null
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
}
export type GlobalOmitConfig = {
  appointments?: Prisma.appointmentsOmit
  doctors?: Prisma.doctorsOmit
  expedients?: Prisma.expedientsOmit
  fields?: Prisma.fieldsOmit
  hospitals?: Prisma.hospitalsOmit
  registers?: Prisma.registersOmit
  weekdays?: Prisma.weekdaysOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

