
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/appointments.ts'
export type * from './models/doctors.ts'
export type * from './models/expedients.ts'
export type * from './models/fields.ts'
export type * from './models/hospitals.ts'
export type * from './models/registers.ts'
export type * from './models/weekdays.ts'
export type * from './commonInputTypes.ts'