USE db_filazero;

INSERT INTO registers
(name, cpf, gender, birth, email, password, type)
VALUES
("Mateus Pereira", "102.102.102-05", "M", "2006-11-01", "mateus@gmail.com", 0),
("Felipe Takahashi", "302.312.102-56", "M", "2006-03-09", "felipe@gmail.com", 0),
("Pedro de Alcântara", "422.102.102-06", "M", "1980-05-04", "pedro@gmail.com", 1),
("João Carlos", "402.155.152-03", "M", "1998-12-14", "joao@gmail.com", 1),
("Leopoldo Salvador", "132.102.102-41", "M", "1970-01-17", "leopoldo@gmail.com", 1),
("Bibiano Francisco", "702.130.102-41", "M", "1968-04-03", "bibiano@gmail.com", 1),
("Xavier de Paula", "902.103.102-01", "M", "1964-08-05", "xavier@gmail.com", 1),
("Leocádio Miguel", "702.102.102-75", "M", "1976-03-07", "leocadio@gmail.com", 1),   
("Gabriel Rafael", "302.102.302-89", "M", "1961-05-08", "gabriel@gmail.com", 1),
("Urraca de Leão", "102.102.108-99", "F", "1978-02-15", "urraca@gmail.com", 1),
("Luiz Gonzaga", "102.103.158-09", "M", "1958-06-18", "gonzaga@gmail.com", 1),
("Francisco Antônio", "312.102.702-77", "M", "1967-08-04", "antonio@gmail.com", 1),
("Joaquim José", "102.102.402-07", "M", "1974-05-25", "joaquim@gmail.com", 1),
("Jaime Viseu", "202.102.102-08", "M", "1977-03-19", "jaime@gmail.com", 1),
("Gonzaga Pascoal", "103.104.132-91", "M", "1969-11-30", "pascoal@gmail.com", 2),
("Cipriano Bourbon", "802.102.102-21", "M", "1966-09-29", "cipriano@gmail.com", 2),
("Serafim de Bragança", "137.102.102-11", "M", "1964-03-15", "serafim@gmail.com", 2),
("Teodósio de Gusmão", "902.101.102-31", "M", "1962", "teodosio@gmail.com", 2),
("Monio Guterres", "102.182.102-81", "M", "1971-09-23", "guterres@gmail.com", 2),
("Teresa Afonso", "102.152.102-08", "F", "1969-04-27", "teresa@gmail.com", 2),
("Filipe de Espanha", "102.552.102-01", "M", "1981-05-22", "filipe@gmail.com", 2),
("João Sebastião", "102.166.102-07", "M", "1979-07-01", "sebastiao@gmail.com", 2),
("Jacques de Magalhães", "106.132.102-22", "M", "1968-09-12", "jacques@gmail.com", 2),
("Manuel Teles", "102.108.109-65", "M", "1971-02-28", "manuel@gmail.com", 2),
("Duarte Ribeiro", "102.902.102-04", "M", "1984", "duarte@gmail.com", 2),
("Fernão Dias", "102.108.102-51", "M", "1969-12-20", "fernao@gmail.com", 2),
("Paes Leme", "102.172.752-06", "M", "1965-02-23", "paes.leme@gmail.com", 2),
("Francisco Dias Velho", "105.142.102-04", "M", "1963-07-30", "dias.velho@gmail.com", 2),
("Lourenço Castanho", "102.808.132-41", "M", "1972-02-20", "lourenco@gmail.com", 2),
("Antônio Raposo Tavares", "332.102.102-51", "M", "1979-10-23", "raposo@gmail.com", 2),
("Pedro Vaz de Barros", "103.302.102-21", "M", "1962-04-02", "pedro.barros@gmail.com", 2),  
("André de Leão", "102.108.144-03", "M", "1975-04-23", "andre@gmail.com", 2), 
("Nicolau Barreto", "992.142.142-03", "M", "1980-09-14", "nicolau@gmail.com", 2)

INSERT INTO hospitals (name, street, number, district, cep, city, uf)
VALUES
("São Lucas Evangelista", "Isabel de Bragança", 180, "Imperador Pedro I", "17580-000", "Pompéia", "SP"),
("São Camilo de Léllis", "Carlos Frederico Lacerda", 197, "Presidente Prudente", "17580-000", "Pompéia", "SP")

INSERT INTO fields (name, description)
VALUES
(1, "Acupuntura", "Aplica técnicas de estimulação de pontos específicos do corpo, como agulhas, para tratar doenças, aliviar dores e promover saúde, conforme princípios da medicina tradicional chinesa."),
(2, "Alergia e Imunologia", "Diagnostica e trata doenças alérgicas e imunológicas, como asma, rinite e imunodeficiências, com foco em prevenção e manejo clínico."),
(3, "Anestesiologia", "Administra anestesia em procedimentos cirúrgicos, monitora pacientes em cirurgias e trata dor aguda e crônica, garantindo segurança perioperatória."),
(4, "Angiologia", "Diagnostica e trata clinicamente doenças dos sistemas vascular arterial, venoso e linfático, como varizes e tromboses."),
(5, "Cancerologia (Oncologia Clínica)", "Foca no diagnóstico, tratamento clínico e acompanhamento de pacientes com câncer, utilizando terapias como quimioterapia e imunoterapia."),
(6, "Cardiologia", "Diagnostica, trata e previne doenças cardiovasculares, como hipertensão, insuficiência cardíaca e arritmias, com exames como eletrocardiograma."),
(7, "Cirurgia Cardiovascular", "Realiza intervenções cirúrgicas no coração e grandes vasos, como revascularização miocárdica e correção de aneurismas."),
(8, "Cirurgia da Mão", "Trata cirurgicamente lesões, traumas e doenças da mão e punho, como fraturas e síndromes compressivas."),
(9, "Cirurgia de Cabeça e Pescoço", "Realiza procedimentos cirúrgicos em tumores, glândulas salivares e outras estruturas da região cervical e craniofacial."),
(10, "Cirurgia do Aparelho Digestivo", "Executa cirurgias nos órgãos digestivos, como estômago, intestino e fígado, para tratar doenças como câncer e obstruções."),
(11, "Cirurgia Geral", "Realiza procedimentos cirúrgicos amplos, especialmente no abdômen, como apendicectomias, colecistectomias e hernioplastias."),
(12, "Cirurgia Pediátrica", "Trata cirurgicamente condições em crianças, como malformações congênitas e traumas, com abordagem específica para faixa etária pediátrica."),
(13, "Cirurgia Plástica", "Realiza procedimentos reconstrutivos (ex. reparo de queimaduras) e estéticos (ex. lipoaspiração), visando funcionalidade e estética."),
(14, "Cirurgia Torácica", "Opera doenças do tórax, como câncer de pulmão, pneumotórax e malformações torácicas, excluindo o coração."),
(15, "Cirurgia Vascular", "Realiza cirurgias nos sistemas arterial, venoso e linfático, como tratamento de aneurismas e varizes."),
(16, "Clínica Médica (Medicina Interna)", "Diagnostica e trata doenças sistêmicas em adultos, coordenando cuidados gerais e integrando especialidades."),
(17, "Coloproctologia", "Diagnostica e trata doenças do cólon, reto e ânus, como hemorroidas, fissuras e câncer colorretal."),
(18, "Dermatologia", "Trata doenças da pele, mucosas, cabelos e unhas, incluindo infecções, alergias e câncer de pele."),
(19, "Endoscopia", "Realiza exames e procedimentos minimamente invasivos, como endoscopia digestiva, para diagnóstico e tratamento de doenças internas."),
(20, "Endocrinologia e Metabologia", "Trata distúrbios hormonais e metabólicos, como diabetes, doenças da tireoide e obesidade."),
(21, "Fisiatria (Medicina Física e Reabilitação)", "Promove reabilitação funcional em pacientes com deficiências motoras ou neurológicas, como após AVC."),
(22, "Gastroenterologia", "Diagnostica e trata doenças do sistema digestivo, incluindo esôfago, estômago, fígado e pâncreas."),
(23, "Genética Médica", "Diagnostica e gerencia doenças genéticas e hereditárias, como síndromes raras, com aconselhamento genético."),
(24, "Geriatria", "Cuida da saúde de idosos, tratando doenças crônicas e promovendo qualidade de vida e funcionalidade."),
(25, "Ginecologia e Obstetrícia", "Trata a saúde reprodutiva feminina, incluindo gestação, parto e doenças ginecológicas."),
(26, "Hematologia e Hemoterapia", "Diagnostica e trata doenças do sangue, como anemias e leucemias, e gerencia transfusões."),
(27, "Homeopatia", "Trata doenças com medicamentos homeopáticos, baseando-se no princípio da similitude e doses mínimas."),
(28, "Infectologia", "Diagnostica e trata infecções bacterianas, virais, fúngicas e parasitárias, como HIV e hepatites."),
(29, "Mastologia", "Diagnostica e trata doenças da mama, com foco em câncer e condições benignas."),
(30, "Medicina de Emergência", "Atende situações agudas e emergências, como traumas, infartos e intoxicações, em pronto-socorro."),
(31, "Medicina de Família e Comunidade", "Oferece cuidado integral e contínuo na atenção primária, com foco em prevenção e promoção da saúde."),
(32, "Medicina do Esporte", "Previne, diagnostica e trata lesões esportivas, além de otimizar desempenho físico."),
(33, "Medicina do Trabalho", "Promove saúde ocupacional, prevenindo e tratando doenças relacionadas ao ambiente laboral."),
(34, "Medicina do Tráfego", "Avalia condições de saúde de condutores para garantir segurança no trânsito."),
(35, "Medicina Intensiva", "Cuida de pacientes críticos em unidades de terapia intensiva, com suporte avançado à vida."),
(36, "Medicina Legal e Perícia Médica", "Aplica conhecimentos médicos em contextos judiciais, como perícias e necropsias."),
(37, "Medicina Nuclear", "Usa materiais radioativos para diagnóstico (ex. cintilografia) e tratamento de doenças."),
(38, "Medicina Preventiva e Social", "Promove saúde coletiva, com foco em prevenção de doenças e vigilância epidemiológica."),
(39, "Nefrologia", "Diagnostica e trata doenças renais, como insuficiência renal, e gerencia terapias como diálise."),
(40, "Neurocirurgia", "Realiza cirurgias no sistema nervoso central e periférico, como tumores cerebrais e aneurismas."),
(41, "Neurologia", "Diagnostica e trata doenças do sistema nervoso, como epilepsia, AVC e demências."),
(42, "Nutrologia", "Diagnostica e trata distúrbios nutricionais, promovendo saúde por meio da alimentação adequada."),
(43, "Oftalmologia", "Trata doenças dos olhos e anexos, como catarata, glaucoma e retinopatias."),
(44, "Ortopedia e Traumatologia", "Diagnostica e trata doenças e traumas do sistema musculoesquelético, como fraturas."),
(45, "Otorrinolaringologia", "Trata doenças do ouvido, nariz, garganta e laringe, como sinusites e otites."),
(46, "Patologia", "Analisa tecidos e fluidos corporais para diagnosticar doenças, como câncer."),
(47, "Patologia Clínica/Medicina Laboratorial", "Realiza e interpreta exames laboratoriais, como hemogramas e testes bioquímicos."),
(48, "Pediatria", "Cuida da saúde de crianças e adolescentes, com foco em crescimento, desenvolvimento e prevenção."),
(49, "Pneumologia", "Trata doenças do sistema respiratório, como asma, DPOC e infecções pulmonares."),
(50, "Psiquiatria", "Diagnostica e trata transtornos mentais, como depressão, ansiedade e esquizofrenia."),
(51, "Radiologia e Diagnóstico por Imagem", "Realiza e interpreta exames de imagem, como raio-X, tomografia e ressonância."),
(52, "Radioterapia", "Trata doenças, principalmente câncer, com radiação ionizante."),
(53, "Reumatologia", "Diagnostica e trata doenças reumáticas e autoimunes, como artrite reumatoide e lúpus."),
(54, "Urologia", "Trata doenças do sistema urinário e reprodutor masculino, como cálculos renais e câncer de próstata."),
(55, "Medicina Paliativa", "Cuida de pacientes com doenças terminais, focando em alívio de sintomas e qualidade de vida.");

INSERT INTO doctors (email, field, id_hospital, duration)
("pascoal@gmail.com", "", 1, ""),
("cipriano@gmail.com", "", 1, ""),
("serafim@gmail.com", "", 1, ""),
("teodosio@gmail.com", "", 1, ""),
("guterres@gmail.com", "", 1, ""),
("teresa@gmail.com", "", 1, ""),
("filipe@gmail.com", "", 1, ""),
("sebastiao@gmail.com", "", 1, ""),
("jacques@gmail.com", "", 1, ""),
("manuel@gmail.com", "", 1, ""),
("duarte@gmail.com", "", 1, ""),
("fernao@gmail.com", "", 1, ""),
("paes.leme@gmail.com", "", 1, ""),
("dias.velho@gmail.com", "", 1, ""),
("lourenco@gmail.com", "", 1, ""),
("raposo@gmail.com", "", 1, ""),
("pedro.barros@gmail.com", "", 1, ""),
("andre@gmail.com", "", 1, ""),
("nicolau@gmail.com", "", 1, "")
