
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `appointments` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model appointments
 * 
 */
export type appointmentsModel = runtime.Types.Result.DefaultSelection<Prisma.$appointmentsPayload>

export type AggregateAppointments = {
  _count: AppointmentsCountAggregateOutputType | null
  _avg: AppointmentsAvgAggregateOutputType | null
  _sum: AppointmentsSumAggregateOutputType | null
  _min: AppointmentsMinAggregateOutputType | null
  _max: AppointmentsMaxAggregateOutputType | null
}

export type AppointmentsAvgAggregateOutputType = {
  id: number | null
}

export type AppointmentsSumAggregateOutputType = {
  id: number | null
}

export type AppointmentsMinAggregateOutputType = {
  id: number | null
  email_doctor: string | null
  email_patient: string | null
  date: Date | null
  hour: Date | null
  registered: Date | null
}

export type AppointmentsMaxAggregateOutputType = {
  id: number | null
  email_doctor: string | null
  email_patient: string | null
  date: Date | null
  hour: Date | null
  registered: Date | null
}

export type AppointmentsCountAggregateOutputType = {
  id: number
  email_doctor: number
  email_patient: number
  date: number
  hour: number
  registered: number
  _all: number
}


export type AppointmentsAvgAggregateInputType = {
  id?: true
}

export type AppointmentsSumAggregateInputType = {
  id?: true
}

export type AppointmentsMinAggregateInputType = {
  id?: true
  email_doctor?: true
  email_patient?: true
  date?: true
  hour?: true
  registered?: true
}

export type AppointmentsMaxAggregateInputType = {
  id?: true
  email_doctor?: true
  email_patient?: true
  date?: true
  hour?: true
  registered?: true
}

export type AppointmentsCountAggregateInputType = {
  id?: true
  email_doctor?: true
  email_patient?: true
  date?: true
  hour?: true
  registered?: true
  _all?: true
}

export type AppointmentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which appointments to aggregate.
   */
  where?: Prisma.appointmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of appointments to fetch.
   */
  orderBy?: Prisma.appointmentsOrderByWithRelationInput | Prisma.appointmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.appointmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` appointments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` appointments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned appointments
  **/
  _count?: true | AppointmentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AppointmentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AppointmentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AppointmentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AppointmentsMaxAggregateInputType
}

export type GetAppointmentsAggregateType<T extends AppointmentsAggregateArgs> = {
      [P in keyof T & keyof AggregateAppointments]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAppointments[P]>
    : Prisma.GetScalarType<T[P], AggregateAppointments[P]>
}




export type appointmentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.appointmentsWhereInput
  orderBy?: Prisma.appointmentsOrderByWithAggregationInput | Prisma.appointmentsOrderByWithAggregationInput[]
  by: Prisma.AppointmentsScalarFieldEnum[] | Prisma.AppointmentsScalarFieldEnum
  having?: Prisma.appointmentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AppointmentsCountAggregateInputType | true
  _avg?: AppointmentsAvgAggregateInputType
  _sum?: AppointmentsSumAggregateInputType
  _min?: AppointmentsMinAggregateInputType
  _max?: AppointmentsMaxAggregateInputType
}

export type AppointmentsGroupByOutputType = {
  id: number
  email_doctor: string
  email_patient: string
  date: Date
  hour: Date
  registered: Date | null
  _count: AppointmentsCountAggregateOutputType | null
  _avg: AppointmentsAvgAggregateOutputType | null
  _sum: AppointmentsSumAggregateOutputType | null
  _min: AppointmentsMinAggregateOutputType | null
  _max: AppointmentsMaxAggregateOutputType | null
}

type GetAppointmentsGroupByPayload<T extends appointmentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AppointmentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AppointmentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AppointmentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AppointmentsGroupByOutputType[P]>
      }
    >
  >



export type appointmentsWhereInput = {
  AND?: Prisma.appointmentsWhereInput | Prisma.appointmentsWhereInput[]
  OR?: Prisma.appointmentsWhereInput[]
  NOT?: Prisma.appointmentsWhereInput | Prisma.appointmentsWhereInput[]
  id?: Prisma.IntFilter<"appointments"> | number
  email_doctor?: Prisma.StringFilter<"appointments"> | string
  email_patient?: Prisma.StringFilter<"appointments"> | string
  date?: Prisma.DateTimeFilter<"appointments"> | Date | string
  hour?: Prisma.DateTimeFilter<"appointments"> | Date | string
  registered?: Prisma.DateTimeNullableFilter<"appointments"> | Date | string | null
  doctors?: Prisma.XOR<Prisma.DoctorsScalarRelationFilter, Prisma.doctorsWhereInput>
  registers?: Prisma.XOR<Prisma.RegistersScalarRelationFilter, Prisma.registersWhereInput>
}

export type appointmentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email_doctor?: Prisma.SortOrder
  email_patient?: Prisma.SortOrder
  date?: Prisma.SortOrder
  hour?: Prisma.SortOrder
  registered?: Prisma.SortOrderInput | Prisma.SortOrder
  doctors?: Prisma.doctorsOrderByWithRelationInput
  registers?: Prisma.registersOrderByWithRelationInput
  _relevance?: Prisma.appointmentsOrderByRelevanceInput
}

export type appointmentsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  email_doctor_date_hour?: Prisma.appointmentsEmail_doctorDateHourCompoundUniqueInput
  AND?: Prisma.appointmentsWhereInput | Prisma.appointmentsWhereInput[]
  OR?: Prisma.appointmentsWhereInput[]
  NOT?: Prisma.appointmentsWhereInput | Prisma.appointmentsWhereInput[]
  email_doctor?: Prisma.StringFilter<"appointments"> | string
  email_patient?: Prisma.StringFilter<"appointments"> | string
  date?: Prisma.DateTimeFilter<"appointments"> | Date | string
  hour?: Prisma.DateTimeFilter<"appointments"> | Date | string
  registered?: Prisma.DateTimeNullableFilter<"appointments"> | Date | string | null
  doctors?: Prisma.XOR<Prisma.DoctorsScalarRelationFilter, Prisma.doctorsWhereInput>
  registers?: Prisma.XOR<Prisma.RegistersScalarRelationFilter, Prisma.registersWhereInput>
}, "id" | "email_doctor_date_hour">

export type appointmentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email_doctor?: Prisma.SortOrder
  email_patient?: Prisma.SortOrder
  date?: Prisma.SortOrder
  hour?: Prisma.SortOrder
  registered?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.appointmentsCountOrderByAggregateInput
  _avg?: Prisma.appointmentsAvgOrderByAggregateInput
  _max?: Prisma.appointmentsMaxOrderByAggregateInput
  _min?: Prisma.appointmentsMinOrderByAggregateInput
  _sum?: Prisma.appointmentsSumOrderByAggregateInput
}

export type appointmentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.appointmentsScalarWhereWithAggregatesInput | Prisma.appointmentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.appointmentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.appointmentsScalarWhereWithAggregatesInput | Prisma.appointmentsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"appointments"> | number
  email_doctor?: Prisma.StringWithAggregatesFilter<"appointments"> | string
  email_patient?: Prisma.StringWithAggregatesFilter<"appointments"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"appointments"> | Date | string
  hour?: Prisma.DateTimeWithAggregatesFilter<"appointments"> | Date | string
  registered?: Prisma.DateTimeNullableWithAggregatesFilter<"appointments"> | Date | string | null
}

export type appointmentsCreateInput = {
  date: Date | string
  hour: Date | string
  registered?: Date | string | null
  doctors: Prisma.doctorsCreateNestedOneWithoutAppointmentsInput
  registers: Prisma.registersCreateNestedOneWithoutAppointmentsInput
}

export type appointmentsUncheckedCreateInput = {
  id?: number
  email_doctor: string
  email_patient: string
  date: Date | string
  hour: Date | string
  registered?: Date | string | null
}

export type appointmentsUpdateInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hour?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registered?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  doctors?: Prisma.doctorsUpdateOneRequiredWithoutAppointmentsNestedInput
  registers?: Prisma.registersUpdateOneRequiredWithoutAppointmentsNestedInput
}

export type appointmentsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  email_doctor?: Prisma.StringFieldUpdateOperationsInput | string
  email_patient?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hour?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registered?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type appointmentsCreateManyInput = {
  id?: number
  email_doctor: string
  email_patient: string
  date: Date | string
  hour: Date | string
  registered?: Date | string | null
}

export type appointmentsUpdateManyMutationInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hour?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registered?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type appointmentsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  email_doctor?: Prisma.StringFieldUpdateOperationsInput | string
  email_patient?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hour?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registered?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type appointmentsOrderByRelevanceInput = {
  fields: Prisma.appointmentsOrderByRelevanceFieldEnum | Prisma.appointmentsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type appointmentsEmail_doctorDateHourCompoundUniqueInput = {
  email_doctor: string
  date: Date | string
  hour: Date | string
}

export type appointmentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email_doctor?: Prisma.SortOrder
  email_patient?: Prisma.SortOrder
  date?: Prisma.SortOrder
  hour?: Prisma.SortOrder
  registered?: Prisma.SortOrder
}

export type appointmentsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type appointmentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email_doctor?: Prisma.SortOrder
  email_patient?: Prisma.SortOrder
  date?: Prisma.SortOrder
  hour?: Prisma.SortOrder
  registered?: Prisma.SortOrder
}

export type appointmentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email_doctor?: Prisma.SortOrder
  email_patient?: Prisma.SortOrder
  date?: Prisma.SortOrder
  hour?: Prisma.SortOrder
  registered?: Prisma.SortOrder
}

export type appointmentsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type AppointmentsListRelationFilter = {
  every?: Prisma.appointmentsWhereInput
  some?: Prisma.appointmentsWhereInput
  none?: Prisma.appointmentsWhereInput
}

export type appointmentsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type appointmentsCreateNestedManyWithoutDoctorsInput = {
  create?: Prisma.XOR<Prisma.appointmentsCreateWithoutDoctorsInput, Prisma.appointmentsUncheckedCreateWithoutDoctorsInput> | Prisma.appointmentsCreateWithoutDoctorsInput[] | Prisma.appointmentsUncheckedCreateWithoutDoctorsInput[]
  connectOrCreate?: Prisma.appointmentsCreateOrConnectWithoutDoctorsInput | Prisma.appointmentsCreateOrConnectWithoutDoctorsInput[]
  createMany?: Prisma.appointmentsCreateManyDoctorsInputEnvelope
  connect?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
}

export type appointmentsUncheckedCreateNestedManyWithoutDoctorsInput = {
  create?: Prisma.XOR<Prisma.appointmentsCreateWithoutDoctorsInput, Prisma.appointmentsUncheckedCreateWithoutDoctorsInput> | Prisma.appointmentsCreateWithoutDoctorsInput[] | Prisma.appointmentsUncheckedCreateWithoutDoctorsInput[]
  connectOrCreate?: Prisma.appointmentsCreateOrConnectWithoutDoctorsInput | Prisma.appointmentsCreateOrConnectWithoutDoctorsInput[]
  createMany?: Prisma.appointmentsCreateManyDoctorsInputEnvelope
  connect?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
}

export type appointmentsUpdateManyWithoutDoctorsNestedInput = {
  create?: Prisma.XOR<Prisma.appointmentsCreateWithoutDoctorsInput, Prisma.appointmentsUncheckedCreateWithoutDoctorsInput> | Prisma.appointmentsCreateWithoutDoctorsInput[] | Prisma.appointmentsUncheckedCreateWithoutDoctorsInput[]
  connectOrCreate?: Prisma.appointmentsCreateOrConnectWithoutDoctorsInput | Prisma.appointmentsCreateOrConnectWithoutDoctorsInput[]
  upsert?: Prisma.appointmentsUpsertWithWhereUniqueWithoutDoctorsInput | Prisma.appointmentsUpsertWithWhereUniqueWithoutDoctorsInput[]
  createMany?: Prisma.appointmentsCreateManyDoctorsInputEnvelope
  set?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  disconnect?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  delete?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  connect?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  update?: Prisma.appointmentsUpdateWithWhereUniqueWithoutDoctorsInput | Prisma.appointmentsUpdateWithWhereUniqueWithoutDoctorsInput[]
  updateMany?: Prisma.appointmentsUpdateManyWithWhereWithoutDoctorsInput | Prisma.appointmentsUpdateManyWithWhereWithoutDoctorsInput[]
  deleteMany?: Prisma.appointmentsScalarWhereInput | Prisma.appointmentsScalarWhereInput[]
}

export type appointmentsUncheckedUpdateManyWithoutDoctorsNestedInput = {
  create?: Prisma.XOR<Prisma.appointmentsCreateWithoutDoctorsInput, Prisma.appointmentsUncheckedCreateWithoutDoctorsInput> | Prisma.appointmentsCreateWithoutDoctorsInput[] | Prisma.appointmentsUncheckedCreateWithoutDoctorsInput[]
  connectOrCreate?: Prisma.appointmentsCreateOrConnectWithoutDoctorsInput | Prisma.appointmentsCreateOrConnectWithoutDoctorsInput[]
  upsert?: Prisma.appointmentsUpsertWithWhereUniqueWithoutDoctorsInput | Prisma.appointmentsUpsertWithWhereUniqueWithoutDoctorsInput[]
  createMany?: Prisma.appointmentsCreateManyDoctorsInputEnvelope
  set?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  disconnect?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  delete?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  connect?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  update?: Prisma.appointmentsUpdateWithWhereUniqueWithoutDoctorsInput | Prisma.appointmentsUpdateWithWhereUniqueWithoutDoctorsInput[]
  updateMany?: Prisma.appointmentsUpdateManyWithWhereWithoutDoctorsInput | Prisma.appointmentsUpdateManyWithWhereWithoutDoctorsInput[]
  deleteMany?: Prisma.appointmentsScalarWhereInput | Prisma.appointmentsScalarWhereInput[]
}

export type appointmentsCreateNestedManyWithoutRegistersInput = {
  create?: Prisma.XOR<Prisma.appointmentsCreateWithoutRegistersInput, Prisma.appointmentsUncheckedCreateWithoutRegistersInput> | Prisma.appointmentsCreateWithoutRegistersInput[] | Prisma.appointmentsUncheckedCreateWithoutRegistersInput[]
  connectOrCreate?: Prisma.appointmentsCreateOrConnectWithoutRegistersInput | Prisma.appointmentsCreateOrConnectWithoutRegistersInput[]
  createMany?: Prisma.appointmentsCreateManyRegistersInputEnvelope
  connect?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
}

export type appointmentsUncheckedCreateNestedManyWithoutRegistersInput = {
  create?: Prisma.XOR<Prisma.appointmentsCreateWithoutRegistersInput, Prisma.appointmentsUncheckedCreateWithoutRegistersInput> | Prisma.appointmentsCreateWithoutRegistersInput[] | Prisma.appointmentsUncheckedCreateWithoutRegistersInput[]
  connectOrCreate?: Prisma.appointmentsCreateOrConnectWithoutRegistersInput | Prisma.appointmentsCreateOrConnectWithoutRegistersInput[]
  createMany?: Prisma.appointmentsCreateManyRegistersInputEnvelope
  connect?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
}

export type appointmentsUpdateManyWithoutRegistersNestedInput = {
  create?: Prisma.XOR<Prisma.appointmentsCreateWithoutRegistersInput, Prisma.appointmentsUncheckedCreateWithoutRegistersInput> | Prisma.appointmentsCreateWithoutRegistersInput[] | Prisma.appointmentsUncheckedCreateWithoutRegistersInput[]
  connectOrCreate?: Prisma.appointmentsCreateOrConnectWithoutRegistersInput | Prisma.appointmentsCreateOrConnectWithoutRegistersInput[]
  upsert?: Prisma.appointmentsUpsertWithWhereUniqueWithoutRegistersInput | Prisma.appointmentsUpsertWithWhereUniqueWithoutRegistersInput[]
  createMany?: Prisma.appointmentsCreateManyRegistersInputEnvelope
  set?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  disconnect?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  delete?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  connect?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  update?: Prisma.appointmentsUpdateWithWhereUniqueWithoutRegistersInput | Prisma.appointmentsUpdateWithWhereUniqueWithoutRegistersInput[]
  updateMany?: Prisma.appointmentsUpdateManyWithWhereWithoutRegistersInput | Prisma.appointmentsUpdateManyWithWhereWithoutRegistersInput[]
  deleteMany?: Prisma.appointmentsScalarWhereInput | Prisma.appointmentsScalarWhereInput[]
}

export type appointmentsUncheckedUpdateManyWithoutRegistersNestedInput = {
  create?: Prisma.XOR<Prisma.appointmentsCreateWithoutRegistersInput, Prisma.appointmentsUncheckedCreateWithoutRegistersInput> | Prisma.appointmentsCreateWithoutRegistersInput[] | Prisma.appointmentsUncheckedCreateWithoutRegistersInput[]
  connectOrCreate?: Prisma.appointmentsCreateOrConnectWithoutRegistersInput | Prisma.appointmentsCreateOrConnectWithoutRegistersInput[]
  upsert?: Prisma.appointmentsUpsertWithWhereUniqueWithoutRegistersInput | Prisma.appointmentsUpsertWithWhereUniqueWithoutRegistersInput[]
  createMany?: Prisma.appointmentsCreateManyRegistersInputEnvelope
  set?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  disconnect?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  delete?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  connect?: Prisma.appointmentsWhereUniqueInput | Prisma.appointmentsWhereUniqueInput[]
  update?: Prisma.appointmentsUpdateWithWhereUniqueWithoutRegistersInput | Prisma.appointmentsUpdateWithWhereUniqueWithoutRegistersInput[]
  updateMany?: Prisma.appointmentsUpdateManyWithWhereWithoutRegistersInput | Prisma.appointmentsUpdateManyWithWhereWithoutRegistersInput[]
  deleteMany?: Prisma.appointmentsScalarWhereInput | Prisma.appointmentsScalarWhereInput[]
}

export type appointmentsCreateWithoutDoctorsInput = {
  date: Date | string
  hour: Date | string
  registered?: Date | string | null
  registers: Prisma.registersCreateNestedOneWithoutAppointmentsInput
}

export type appointmentsUncheckedCreateWithoutDoctorsInput = {
  id?: number
  email_patient: string
  date: Date | string
  hour: Date | string
  registered?: Date | string | null
}

export type appointmentsCreateOrConnectWithoutDoctorsInput = {
  where: Prisma.appointmentsWhereUniqueInput
  create: Prisma.XOR<Prisma.appointmentsCreateWithoutDoctorsInput, Prisma.appointmentsUncheckedCreateWithoutDoctorsInput>
}

export type appointmentsCreateManyDoctorsInputEnvelope = {
  data: Prisma.appointmentsCreateManyDoctorsInput | Prisma.appointmentsCreateManyDoctorsInput[]
  skipDuplicates?: boolean
}

export type appointmentsUpsertWithWhereUniqueWithoutDoctorsInput = {
  where: Prisma.appointmentsWhereUniqueInput
  update: Prisma.XOR<Prisma.appointmentsUpdateWithoutDoctorsInput, Prisma.appointmentsUncheckedUpdateWithoutDoctorsInput>
  create: Prisma.XOR<Prisma.appointmentsCreateWithoutDoctorsInput, Prisma.appointmentsUncheckedCreateWithoutDoctorsInput>
}

export type appointmentsUpdateWithWhereUniqueWithoutDoctorsInput = {
  where: Prisma.appointmentsWhereUniqueInput
  data: Prisma.XOR<Prisma.appointmentsUpdateWithoutDoctorsInput, Prisma.appointmentsUncheckedUpdateWithoutDoctorsInput>
}

export type appointmentsUpdateManyWithWhereWithoutDoctorsInput = {
  where: Prisma.appointmentsScalarWhereInput
  data: Prisma.XOR<Prisma.appointmentsUpdateManyMutationInput, Prisma.appointmentsUncheckedUpdateManyWithoutDoctorsInput>
}

export type appointmentsScalarWhereInput = {
  AND?: Prisma.appointmentsScalarWhereInput | Prisma.appointmentsScalarWhereInput[]
  OR?: Prisma.appointmentsScalarWhereInput[]
  NOT?: Prisma.appointmentsScalarWhereInput | Prisma.appointmentsScalarWhereInput[]
  id?: Prisma.IntFilter<"appointments"> | number
  email_doctor?: Prisma.StringFilter<"appointments"> | string
  email_patient?: Prisma.StringFilter<"appointments"> | string
  date?: Prisma.DateTimeFilter<"appointments"> | Date | string
  hour?: Prisma.DateTimeFilter<"appointments"> | Date | string
  registered?: Prisma.DateTimeNullableFilter<"appointments"> | Date | string | null
}

export type appointmentsCreateWithoutRegistersInput = {
  date: Date | string
  hour: Date | string
  registered?: Date | string | null
  doctors: Prisma.doctorsCreateNestedOneWithoutAppointmentsInput
}

export type appointmentsUncheckedCreateWithoutRegistersInput = {
  id?: number
  email_doctor: string
  date: Date | string
  hour: Date | string
  registered?: Date | string | null
}

export type appointmentsCreateOrConnectWithoutRegistersInput = {
  where: Prisma.appointmentsWhereUniqueInput
  create: Prisma.XOR<Prisma.appointmentsCreateWithoutRegistersInput, Prisma.appointmentsUncheckedCreateWithoutRegistersInput>
}

export type appointmentsCreateManyRegistersInputEnvelope = {
  data: Prisma.appointmentsCreateManyRegistersInput | Prisma.appointmentsCreateManyRegistersInput[]
  skipDuplicates?: boolean
}

export type appointmentsUpsertWithWhereUniqueWithoutRegistersInput = {
  where: Prisma.appointmentsWhereUniqueInput
  update: Prisma.XOR<Prisma.appointmentsUpdateWithoutRegistersInput, Prisma.appointmentsUncheckedUpdateWithoutRegistersInput>
  create: Prisma.XOR<Prisma.appointmentsCreateWithoutRegistersInput, Prisma.appointmentsUncheckedCreateWithoutRegistersInput>
}

export type appointmentsUpdateWithWhereUniqueWithoutRegistersInput = {
  where: Prisma.appointmentsWhereUniqueInput
  data: Prisma.XOR<Prisma.appointmentsUpdateWithoutRegistersInput, Prisma.appointmentsUncheckedUpdateWithoutRegistersInput>
}

export type appointmentsUpdateManyWithWhereWithoutRegistersInput = {
  where: Prisma.appointmentsScalarWhereInput
  data: Prisma.XOR<Prisma.appointmentsUpdateManyMutationInput, Prisma.appointmentsUncheckedUpdateManyWithoutRegistersInput>
}

export type appointmentsCreateManyDoctorsInput = {
  id?: number
  email_patient: string
  date: Date | string
  hour: Date | string
  registered?: Date | string | null
}

export type appointmentsUpdateWithoutDoctorsInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hour?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registered?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  registers?: Prisma.registersUpdateOneRequiredWithoutAppointmentsNestedInput
}

export type appointmentsUncheckedUpdateWithoutDoctorsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  email_patient?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hour?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registered?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type appointmentsUncheckedUpdateManyWithoutDoctorsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  email_patient?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hour?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registered?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type appointmentsCreateManyRegistersInput = {
  id?: number
  email_doctor: string
  date: Date | string
  hour: Date | string
  registered?: Date | string | null
}

export type appointmentsUpdateWithoutRegistersInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hour?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registered?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  doctors?: Prisma.doctorsUpdateOneRequiredWithoutAppointmentsNestedInput
}

export type appointmentsUncheckedUpdateWithoutRegistersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  email_doctor?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hour?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registered?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type appointmentsUncheckedUpdateManyWithoutRegistersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  email_doctor?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hour?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registered?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type appointmentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email_doctor?: boolean
  email_patient?: boolean
  date?: boolean
  hour?: boolean
  registered?: boolean
  doctors?: boolean | Prisma.doctorsDefaultArgs<ExtArgs>
  registers?: boolean | Prisma.registersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appointments"]>



export type appointmentsSelectScalar = {
  id?: boolean
  email_doctor?: boolean
  email_patient?: boolean
  date?: boolean
  hour?: boolean
  registered?: boolean
}

export type appointmentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email_doctor" | "email_patient" | "date" | "hour" | "registered", ExtArgs["result"]["appointments"]>
export type appointmentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  doctors?: boolean | Prisma.doctorsDefaultArgs<ExtArgs>
  registers?: boolean | Prisma.registersDefaultArgs<ExtArgs>
}

export type $appointmentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "appointments"
  objects: {
    doctors: Prisma.$doctorsPayload<ExtArgs>
    registers: Prisma.$registersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    email_doctor: string
    email_patient: string
    date: Date
    hour: Date
    registered: Date | null
  }, ExtArgs["result"]["appointments"]>
  composites: {}
}

export type appointmentsGetPayload<S extends boolean | null | undefined | appointmentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$appointmentsPayload, S>

export type appointmentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<appointmentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AppointmentsCountAggregateInputType | true
  }

export interface appointmentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['appointments'], meta: { name: 'appointments' } }
  /**
   * Find zero or one Appointments that matches the filter.
   * @param {appointmentsFindUniqueArgs} args - Arguments to find a Appointments
   * @example
   * // Get one Appointments
   * const appointments = await prisma.appointments.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends appointmentsFindUniqueArgs>(args: Prisma.SelectSubset<T, appointmentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__appointmentsClient<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Appointments that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {appointmentsFindUniqueOrThrowArgs} args - Arguments to find a Appointments
   * @example
   * // Get one Appointments
   * const appointments = await prisma.appointments.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends appointmentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, appointmentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__appointmentsClient<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Appointments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {appointmentsFindFirstArgs} args - Arguments to find a Appointments
   * @example
   * // Get one Appointments
   * const appointments = await prisma.appointments.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends appointmentsFindFirstArgs>(args?: Prisma.SelectSubset<T, appointmentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__appointmentsClient<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Appointments that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {appointmentsFindFirstOrThrowArgs} args - Arguments to find a Appointments
   * @example
   * // Get one Appointments
   * const appointments = await prisma.appointments.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends appointmentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, appointmentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__appointmentsClient<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Appointments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {appointmentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Appointments
   * const appointments = await prisma.appointments.findMany()
   * 
   * // Get first 10 Appointments
   * const appointments = await prisma.appointments.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const appointmentsWithIdOnly = await prisma.appointments.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends appointmentsFindManyArgs>(args?: Prisma.SelectSubset<T, appointmentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Appointments.
   * @param {appointmentsCreateArgs} args - Arguments to create a Appointments.
   * @example
   * // Create one Appointments
   * const Appointments = await prisma.appointments.create({
   *   data: {
   *     // ... data to create a Appointments
   *   }
   * })
   * 
   */
  create<T extends appointmentsCreateArgs>(args: Prisma.SelectSubset<T, appointmentsCreateArgs<ExtArgs>>): Prisma.Prisma__appointmentsClient<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Appointments.
   * @param {appointmentsCreateManyArgs} args - Arguments to create many Appointments.
   * @example
   * // Create many Appointments
   * const appointments = await prisma.appointments.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends appointmentsCreateManyArgs>(args?: Prisma.SelectSubset<T, appointmentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Appointments.
   * @param {appointmentsDeleteArgs} args - Arguments to delete one Appointments.
   * @example
   * // Delete one Appointments
   * const Appointments = await prisma.appointments.delete({
   *   where: {
   *     // ... filter to delete one Appointments
   *   }
   * })
   * 
   */
  delete<T extends appointmentsDeleteArgs>(args: Prisma.SelectSubset<T, appointmentsDeleteArgs<ExtArgs>>): Prisma.Prisma__appointmentsClient<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Appointments.
   * @param {appointmentsUpdateArgs} args - Arguments to update one Appointments.
   * @example
   * // Update one Appointments
   * const appointments = await prisma.appointments.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends appointmentsUpdateArgs>(args: Prisma.SelectSubset<T, appointmentsUpdateArgs<ExtArgs>>): Prisma.Prisma__appointmentsClient<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Appointments.
   * @param {appointmentsDeleteManyArgs} args - Arguments to filter Appointments to delete.
   * @example
   * // Delete a few Appointments
   * const { count } = await prisma.appointments.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends appointmentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, appointmentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Appointments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {appointmentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Appointments
   * const appointments = await prisma.appointments.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends appointmentsUpdateManyArgs>(args: Prisma.SelectSubset<T, appointmentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Appointments.
   * @param {appointmentsUpsertArgs} args - Arguments to update or create a Appointments.
   * @example
   * // Update or create a Appointments
   * const appointments = await prisma.appointments.upsert({
   *   create: {
   *     // ... data to create a Appointments
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Appointments we want to update
   *   }
   * })
   */
  upsert<T extends appointmentsUpsertArgs>(args: Prisma.SelectSubset<T, appointmentsUpsertArgs<ExtArgs>>): Prisma.Prisma__appointmentsClient<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Appointments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {appointmentsCountArgs} args - Arguments to filter Appointments to count.
   * @example
   * // Count the number of Appointments
   * const count = await prisma.appointments.count({
   *   where: {
   *     // ... the filter for the Appointments we want to count
   *   }
   * })
  **/
  count<T extends appointmentsCountArgs>(
    args?: Prisma.Subset<T, appointmentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AppointmentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Appointments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AppointmentsAggregateArgs>(args: Prisma.Subset<T, AppointmentsAggregateArgs>): Prisma.PrismaPromise<GetAppointmentsAggregateType<T>>

  /**
   * Group by Appointments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {appointmentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends appointmentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: appointmentsGroupByArgs['orderBy'] }
      : { orderBy?: appointmentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, appointmentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAppointmentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the appointments model
 */
readonly fields: appointmentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for appointments.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__appointmentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  doctors<T extends Prisma.doctorsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.doctorsDefaultArgs<ExtArgs>>): Prisma.Prisma__doctorsClient<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  registers<T extends Prisma.registersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.registersDefaultArgs<ExtArgs>>): Prisma.Prisma__registersClient<runtime.Types.Result.GetResult<Prisma.$registersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the appointments model
 */
export interface appointmentsFieldRefs {
  readonly id: Prisma.FieldRef<"appointments", 'Int'>
  readonly email_doctor: Prisma.FieldRef<"appointments", 'String'>
  readonly email_patient: Prisma.FieldRef<"appointments", 'String'>
  readonly date: Prisma.FieldRef<"appointments", 'DateTime'>
  readonly hour: Prisma.FieldRef<"appointments", 'DateTime'>
  readonly registered: Prisma.FieldRef<"appointments", 'DateTime'>
}
    

// Custom InputTypes
/**
 * appointments findUnique
 */
export type appointmentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  /**
   * Filter, which appointments to fetch.
   */
  where: Prisma.appointmentsWhereUniqueInput
}

/**
 * appointments findUniqueOrThrow
 */
export type appointmentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  /**
   * Filter, which appointments to fetch.
   */
  where: Prisma.appointmentsWhereUniqueInput
}

/**
 * appointments findFirst
 */
export type appointmentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  /**
   * Filter, which appointments to fetch.
   */
  where?: Prisma.appointmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of appointments to fetch.
   */
  orderBy?: Prisma.appointmentsOrderByWithRelationInput | Prisma.appointmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for appointments.
   */
  cursor?: Prisma.appointmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` appointments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` appointments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of appointments.
   */
  distinct?: Prisma.AppointmentsScalarFieldEnum | Prisma.AppointmentsScalarFieldEnum[]
}

/**
 * appointments findFirstOrThrow
 */
export type appointmentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  /**
   * Filter, which appointments to fetch.
   */
  where?: Prisma.appointmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of appointments to fetch.
   */
  orderBy?: Prisma.appointmentsOrderByWithRelationInput | Prisma.appointmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for appointments.
   */
  cursor?: Prisma.appointmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` appointments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` appointments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of appointments.
   */
  distinct?: Prisma.AppointmentsScalarFieldEnum | Prisma.AppointmentsScalarFieldEnum[]
}

/**
 * appointments findMany
 */
export type appointmentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  /**
   * Filter, which appointments to fetch.
   */
  where?: Prisma.appointmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of appointments to fetch.
   */
  orderBy?: Prisma.appointmentsOrderByWithRelationInput | Prisma.appointmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing appointments.
   */
  cursor?: Prisma.appointmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` appointments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` appointments.
   */
  skip?: number
  distinct?: Prisma.AppointmentsScalarFieldEnum | Prisma.AppointmentsScalarFieldEnum[]
}

/**
 * appointments create
 */
export type appointmentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  /**
   * The data needed to create a appointments.
   */
  data: Prisma.XOR<Prisma.appointmentsCreateInput, Prisma.appointmentsUncheckedCreateInput>
}

/**
 * appointments createMany
 */
export type appointmentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many appointments.
   */
  data: Prisma.appointmentsCreateManyInput | Prisma.appointmentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * appointments update
 */
export type appointmentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  /**
   * The data needed to update a appointments.
   */
  data: Prisma.XOR<Prisma.appointmentsUpdateInput, Prisma.appointmentsUncheckedUpdateInput>
  /**
   * Choose, which appointments to update.
   */
  where: Prisma.appointmentsWhereUniqueInput
}

/**
 * appointments updateMany
 */
export type appointmentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update appointments.
   */
  data: Prisma.XOR<Prisma.appointmentsUpdateManyMutationInput, Prisma.appointmentsUncheckedUpdateManyInput>
  /**
   * Filter which appointments to update
   */
  where?: Prisma.appointmentsWhereInput
  /**
   * Limit how many appointments to update.
   */
  limit?: number
}

/**
 * appointments upsert
 */
export type appointmentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  /**
   * The filter to search for the appointments to update in case it exists.
   */
  where: Prisma.appointmentsWhereUniqueInput
  /**
   * In case the appointments found by the `where` argument doesn't exist, create a new appointments with this data.
   */
  create: Prisma.XOR<Prisma.appointmentsCreateInput, Prisma.appointmentsUncheckedCreateInput>
  /**
   * In case the appointments was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.appointmentsUpdateInput, Prisma.appointmentsUncheckedUpdateInput>
}

/**
 * appointments delete
 */
export type appointmentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  /**
   * Filter which appointments to delete.
   */
  where: Prisma.appointmentsWhereUniqueInput
}

/**
 * appointments deleteMany
 */
export type appointmentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which appointments to delete
   */
  where?: Prisma.appointmentsWhereInput
  /**
   * Limit how many appointments to delete.
   */
  limit?: number
}

/**
 * appointments without action
 */
export type appointmentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
}
