
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `doctors` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model doctors
 * 
 */
export type doctorsModel = runtime.Types.Result.DefaultSelection<Prisma.$doctorsPayload>

export type AggregateDoctors = {
  _count: DoctorsCountAggregateOutputType | null
  _avg: DoctorsAvgAggregateOutputType | null
  _sum: DoctorsSumAggregateOutputType | null
  _min: DoctorsMinAggregateOutputType | null
  _max: DoctorsMaxAggregateOutputType | null
}

export type DoctorsAvgAggregateOutputType = {
  id_field: number | null
  id_hospital: number | null
  id_expedient: number | null
}

export type DoctorsSumAggregateOutputType = {
  id_field: number | null
  id_hospital: number | null
  id_expedient: number | null
}

export type DoctorsMinAggregateOutputType = {
  email: string | null
  id_field: number | null
  id_hospital: number | null
  id_expedient: number | null
  first_day: Date | null
}

export type DoctorsMaxAggregateOutputType = {
  email: string | null
  id_field: number | null
  id_hospital: number | null
  id_expedient: number | null
  first_day: Date | null
}

export type DoctorsCountAggregateOutputType = {
  email: number
  id_field: number
  id_hospital: number
  id_expedient: number
  first_day: number
  _all: number
}


export type DoctorsAvgAggregateInputType = {
  id_field?: true
  id_hospital?: true
  id_expedient?: true
}

export type DoctorsSumAggregateInputType = {
  id_field?: true
  id_hospital?: true
  id_expedient?: true
}

export type DoctorsMinAggregateInputType = {
  email?: true
  id_field?: true
  id_hospital?: true
  id_expedient?: true
  first_day?: true
}

export type DoctorsMaxAggregateInputType = {
  email?: true
  id_field?: true
  id_hospital?: true
  id_expedient?: true
  first_day?: true
}

export type DoctorsCountAggregateInputType = {
  email?: true
  id_field?: true
  id_hospital?: true
  id_expedient?: true
  first_day?: true
  _all?: true
}

export type DoctorsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which doctors to aggregate.
   */
  where?: Prisma.doctorsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of doctors to fetch.
   */
  orderBy?: Prisma.doctorsOrderByWithRelationInput | Prisma.doctorsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.doctorsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` doctors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` doctors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned doctors
  **/
  _count?: true | DoctorsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DoctorsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DoctorsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DoctorsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DoctorsMaxAggregateInputType
}

export type GetDoctorsAggregateType<T extends DoctorsAggregateArgs> = {
      [P in keyof T & keyof AggregateDoctors]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDoctors[P]>
    : Prisma.GetScalarType<T[P], AggregateDoctors[P]>
}




export type doctorsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.doctorsWhereInput
  orderBy?: Prisma.doctorsOrderByWithAggregationInput | Prisma.doctorsOrderByWithAggregationInput[]
  by: Prisma.DoctorsScalarFieldEnum[] | Prisma.DoctorsScalarFieldEnum
  having?: Prisma.doctorsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DoctorsCountAggregateInputType | true
  _avg?: DoctorsAvgAggregateInputType
  _sum?: DoctorsSumAggregateInputType
  _min?: DoctorsMinAggregateInputType
  _max?: DoctorsMaxAggregateInputType
}

export type DoctorsGroupByOutputType = {
  email: string
  id_field: number
  id_hospital: number
  id_expedient: number
  first_day: Date
  _count: DoctorsCountAggregateOutputType | null
  _avg: DoctorsAvgAggregateOutputType | null
  _sum: DoctorsSumAggregateOutputType | null
  _min: DoctorsMinAggregateOutputType | null
  _max: DoctorsMaxAggregateOutputType | null
}

type GetDoctorsGroupByPayload<T extends doctorsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DoctorsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DoctorsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DoctorsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DoctorsGroupByOutputType[P]>
      }
    >
  >



export type doctorsWhereInput = {
  AND?: Prisma.doctorsWhereInput | Prisma.doctorsWhereInput[]
  OR?: Prisma.doctorsWhereInput[]
  NOT?: Prisma.doctorsWhereInput | Prisma.doctorsWhereInput[]
  email?: Prisma.StringFilter<"doctors"> | string
  id_field?: Prisma.IntFilter<"doctors"> | number
  id_hospital?: Prisma.IntFilter<"doctors"> | number
  id_expedient?: Prisma.IntFilter<"doctors"> | number
  first_day?: Prisma.DateTimeFilter<"doctors"> | Date | string
  appointments?: Prisma.AppointmentsListRelationFilter
  registers?: Prisma.XOR<Prisma.RegistersScalarRelationFilter, Prisma.registersWhereInput>
  fields?: Prisma.XOR<Prisma.FieldsScalarRelationFilter, Prisma.fieldsWhereInput>
  hospitals?: Prisma.XOR<Prisma.HospitalsScalarRelationFilter, Prisma.hospitalsWhereInput>
  expedients?: Prisma.XOR<Prisma.ExpedientsScalarRelationFilter, Prisma.expedientsWhereInput>
}

export type doctorsOrderByWithRelationInput = {
  email?: Prisma.SortOrder
  id_field?: Prisma.SortOrder
  id_hospital?: Prisma.SortOrder
  id_expedient?: Prisma.SortOrder
  first_day?: Prisma.SortOrder
  appointments?: Prisma.appointmentsOrderByRelationAggregateInput
  registers?: Prisma.registersOrderByWithRelationInput
  fields?: Prisma.fieldsOrderByWithRelationInput
  hospitals?: Prisma.hospitalsOrderByWithRelationInput
  expedients?: Prisma.expedientsOrderByWithRelationInput
  _relevance?: Prisma.doctorsOrderByRelevanceInput
}

export type doctorsWhereUniqueInput = Prisma.AtLeast<{
  email?: string
  AND?: Prisma.doctorsWhereInput | Prisma.doctorsWhereInput[]
  OR?: Prisma.doctorsWhereInput[]
  NOT?: Prisma.doctorsWhereInput | Prisma.doctorsWhereInput[]
  id_field?: Prisma.IntFilter<"doctors"> | number
  id_hospital?: Prisma.IntFilter<"doctors"> | number
  id_expedient?: Prisma.IntFilter<"doctors"> | number
  first_day?: Prisma.DateTimeFilter<"doctors"> | Date | string
  appointments?: Prisma.AppointmentsListRelationFilter
  registers?: Prisma.XOR<Prisma.RegistersScalarRelationFilter, Prisma.registersWhereInput>
  fields?: Prisma.XOR<Prisma.FieldsScalarRelationFilter, Prisma.fieldsWhereInput>
  hospitals?: Prisma.XOR<Prisma.HospitalsScalarRelationFilter, Prisma.hospitalsWhereInput>
  expedients?: Prisma.XOR<Prisma.ExpedientsScalarRelationFilter, Prisma.expedientsWhereInput>
}, "email">

export type doctorsOrderByWithAggregationInput = {
  email?: Prisma.SortOrder
  id_field?: Prisma.SortOrder
  id_hospital?: Prisma.SortOrder
  id_expedient?: Prisma.SortOrder
  first_day?: Prisma.SortOrder
  _count?: Prisma.doctorsCountOrderByAggregateInput
  _avg?: Prisma.doctorsAvgOrderByAggregateInput
  _max?: Prisma.doctorsMaxOrderByAggregateInput
  _min?: Prisma.doctorsMinOrderByAggregateInput
  _sum?: Prisma.doctorsSumOrderByAggregateInput
}

export type doctorsScalarWhereWithAggregatesInput = {
  AND?: Prisma.doctorsScalarWhereWithAggregatesInput | Prisma.doctorsScalarWhereWithAggregatesInput[]
  OR?: Prisma.doctorsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.doctorsScalarWhereWithAggregatesInput | Prisma.doctorsScalarWhereWithAggregatesInput[]
  email?: Prisma.StringWithAggregatesFilter<"doctors"> | string
  id_field?: Prisma.IntWithAggregatesFilter<"doctors"> | number
  id_hospital?: Prisma.IntWithAggregatesFilter<"doctors"> | number
  id_expedient?: Prisma.IntWithAggregatesFilter<"doctors"> | number
  first_day?: Prisma.DateTimeWithAggregatesFilter<"doctors"> | Date | string
}

export type doctorsCreateInput = {
  first_day?: Date | string
  appointments?: Prisma.appointmentsCreateNestedManyWithoutDoctorsInput
  registers: Prisma.registersCreateNestedOneWithoutDoctorsInput
  fields: Prisma.fieldsCreateNestedOneWithoutDoctorsInput
  hospitals: Prisma.hospitalsCreateNestedOneWithoutDoctorsInput
  expedients: Prisma.expedientsCreateNestedOneWithoutDoctorsInput
}

export type doctorsUncheckedCreateInput = {
  email: string
  id_field: number
  id_hospital: number
  id_expedient: number
  first_day?: Date | string
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutDoctorsInput
}

export type doctorsUpdateInput = {
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.appointmentsUpdateManyWithoutDoctorsNestedInput
  registers?: Prisma.registersUpdateOneRequiredWithoutDoctorsNestedInput
  fields?: Prisma.fieldsUpdateOneRequiredWithoutDoctorsNestedInput
  hospitals?: Prisma.hospitalsUpdateOneRequiredWithoutDoctorsNestedInput
  expedients?: Prisma.expedientsUpdateOneRequiredWithoutDoctorsNestedInput
}

export type doctorsUncheckedUpdateInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  id_field?: Prisma.IntFieldUpdateOperationsInput | number
  id_hospital?: Prisma.IntFieldUpdateOperationsInput | number
  id_expedient?: Prisma.IntFieldUpdateOperationsInput | number
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutDoctorsNestedInput
}

export type doctorsCreateManyInput = {
  email: string
  id_field: number
  id_hospital: number
  id_expedient: number
  first_day?: Date | string
}

export type doctorsUpdateManyMutationInput = {
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type doctorsUncheckedUpdateManyInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  id_field?: Prisma.IntFieldUpdateOperationsInput | number
  id_hospital?: Prisma.IntFieldUpdateOperationsInput | number
  id_expedient?: Prisma.IntFieldUpdateOperationsInput | number
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DoctorsScalarRelationFilter = {
  is?: Prisma.doctorsWhereInput
  isNot?: Prisma.doctorsWhereInput
}

export type doctorsOrderByRelevanceInput = {
  fields: Prisma.doctorsOrderByRelevanceFieldEnum | Prisma.doctorsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type doctorsCountOrderByAggregateInput = {
  email?: Prisma.SortOrder
  id_field?: Prisma.SortOrder
  id_hospital?: Prisma.SortOrder
  id_expedient?: Prisma.SortOrder
  first_day?: Prisma.SortOrder
}

export type doctorsAvgOrderByAggregateInput = {
  id_field?: Prisma.SortOrder
  id_hospital?: Prisma.SortOrder
  id_expedient?: Prisma.SortOrder
}

export type doctorsMaxOrderByAggregateInput = {
  email?: Prisma.SortOrder
  id_field?: Prisma.SortOrder
  id_hospital?: Prisma.SortOrder
  id_expedient?: Prisma.SortOrder
  first_day?: Prisma.SortOrder
}

export type doctorsMinOrderByAggregateInput = {
  email?: Prisma.SortOrder
  id_field?: Prisma.SortOrder
  id_hospital?: Prisma.SortOrder
  id_expedient?: Prisma.SortOrder
  first_day?: Prisma.SortOrder
}

export type doctorsSumOrderByAggregateInput = {
  id_field?: Prisma.SortOrder
  id_hospital?: Prisma.SortOrder
  id_expedient?: Prisma.SortOrder
}

export type DoctorsListRelationFilter = {
  every?: Prisma.doctorsWhereInput
  some?: Prisma.doctorsWhereInput
  none?: Prisma.doctorsWhereInput
}

export type doctorsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DoctorsNullableScalarRelationFilter = {
  is?: Prisma.doctorsWhereInput | null
  isNot?: Prisma.doctorsWhereInput | null
}

export type doctorsCreateNestedOneWithoutAppointmentsInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutAppointmentsInput, Prisma.doctorsUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutAppointmentsInput
  connect?: Prisma.doctorsWhereUniqueInput
}

export type doctorsUpdateOneRequiredWithoutAppointmentsNestedInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutAppointmentsInput, Prisma.doctorsUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutAppointmentsInput
  upsert?: Prisma.doctorsUpsertWithoutAppointmentsInput
  connect?: Prisma.doctorsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.doctorsUpdateToOneWithWhereWithoutAppointmentsInput, Prisma.doctorsUpdateWithoutAppointmentsInput>, Prisma.doctorsUncheckedUpdateWithoutAppointmentsInput>
}

export type doctorsCreateNestedManyWithoutExpedientsInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutExpedientsInput, Prisma.doctorsUncheckedCreateWithoutExpedientsInput> | Prisma.doctorsCreateWithoutExpedientsInput[] | Prisma.doctorsUncheckedCreateWithoutExpedientsInput[]
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutExpedientsInput | Prisma.doctorsCreateOrConnectWithoutExpedientsInput[]
  createMany?: Prisma.doctorsCreateManyExpedientsInputEnvelope
  connect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
}

export type doctorsUncheckedCreateNestedManyWithoutExpedientsInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutExpedientsInput, Prisma.doctorsUncheckedCreateWithoutExpedientsInput> | Prisma.doctorsCreateWithoutExpedientsInput[] | Prisma.doctorsUncheckedCreateWithoutExpedientsInput[]
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutExpedientsInput | Prisma.doctorsCreateOrConnectWithoutExpedientsInput[]
  createMany?: Prisma.doctorsCreateManyExpedientsInputEnvelope
  connect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
}

export type doctorsUpdateManyWithoutExpedientsNestedInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutExpedientsInput, Prisma.doctorsUncheckedCreateWithoutExpedientsInput> | Prisma.doctorsCreateWithoutExpedientsInput[] | Prisma.doctorsUncheckedCreateWithoutExpedientsInput[]
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutExpedientsInput | Prisma.doctorsCreateOrConnectWithoutExpedientsInput[]
  upsert?: Prisma.doctorsUpsertWithWhereUniqueWithoutExpedientsInput | Prisma.doctorsUpsertWithWhereUniqueWithoutExpedientsInput[]
  createMany?: Prisma.doctorsCreateManyExpedientsInputEnvelope
  set?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  disconnect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  delete?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  connect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  update?: Prisma.doctorsUpdateWithWhereUniqueWithoutExpedientsInput | Prisma.doctorsUpdateWithWhereUniqueWithoutExpedientsInput[]
  updateMany?: Prisma.doctorsUpdateManyWithWhereWithoutExpedientsInput | Prisma.doctorsUpdateManyWithWhereWithoutExpedientsInput[]
  deleteMany?: Prisma.doctorsScalarWhereInput | Prisma.doctorsScalarWhereInput[]
}

export type doctorsUncheckedUpdateManyWithoutExpedientsNestedInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutExpedientsInput, Prisma.doctorsUncheckedCreateWithoutExpedientsInput> | Prisma.doctorsCreateWithoutExpedientsInput[] | Prisma.doctorsUncheckedCreateWithoutExpedientsInput[]
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutExpedientsInput | Prisma.doctorsCreateOrConnectWithoutExpedientsInput[]
  upsert?: Prisma.doctorsUpsertWithWhereUniqueWithoutExpedientsInput | Prisma.doctorsUpsertWithWhereUniqueWithoutExpedientsInput[]
  createMany?: Prisma.doctorsCreateManyExpedientsInputEnvelope
  set?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  disconnect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  delete?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  connect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  update?: Prisma.doctorsUpdateWithWhereUniqueWithoutExpedientsInput | Prisma.doctorsUpdateWithWhereUniqueWithoutExpedientsInput[]
  updateMany?: Prisma.doctorsUpdateManyWithWhereWithoutExpedientsInput | Prisma.doctorsUpdateManyWithWhereWithoutExpedientsInput[]
  deleteMany?: Prisma.doctorsScalarWhereInput | Prisma.doctorsScalarWhereInput[]
}

export type doctorsCreateNestedManyWithoutFieldsInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutFieldsInput, Prisma.doctorsUncheckedCreateWithoutFieldsInput> | Prisma.doctorsCreateWithoutFieldsInput[] | Prisma.doctorsUncheckedCreateWithoutFieldsInput[]
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutFieldsInput | Prisma.doctorsCreateOrConnectWithoutFieldsInput[]
  createMany?: Prisma.doctorsCreateManyFieldsInputEnvelope
  connect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
}

export type doctorsUncheckedCreateNestedManyWithoutFieldsInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutFieldsInput, Prisma.doctorsUncheckedCreateWithoutFieldsInput> | Prisma.doctorsCreateWithoutFieldsInput[] | Prisma.doctorsUncheckedCreateWithoutFieldsInput[]
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutFieldsInput | Prisma.doctorsCreateOrConnectWithoutFieldsInput[]
  createMany?: Prisma.doctorsCreateManyFieldsInputEnvelope
  connect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
}

export type doctorsUpdateManyWithoutFieldsNestedInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutFieldsInput, Prisma.doctorsUncheckedCreateWithoutFieldsInput> | Prisma.doctorsCreateWithoutFieldsInput[] | Prisma.doctorsUncheckedCreateWithoutFieldsInput[]
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutFieldsInput | Prisma.doctorsCreateOrConnectWithoutFieldsInput[]
  upsert?: Prisma.doctorsUpsertWithWhereUniqueWithoutFieldsInput | Prisma.doctorsUpsertWithWhereUniqueWithoutFieldsInput[]
  createMany?: Prisma.doctorsCreateManyFieldsInputEnvelope
  set?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  disconnect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  delete?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  connect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  update?: Prisma.doctorsUpdateWithWhereUniqueWithoutFieldsInput | Prisma.doctorsUpdateWithWhereUniqueWithoutFieldsInput[]
  updateMany?: Prisma.doctorsUpdateManyWithWhereWithoutFieldsInput | Prisma.doctorsUpdateManyWithWhereWithoutFieldsInput[]
  deleteMany?: Prisma.doctorsScalarWhereInput | Prisma.doctorsScalarWhereInput[]
}

export type doctorsUncheckedUpdateManyWithoutFieldsNestedInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutFieldsInput, Prisma.doctorsUncheckedCreateWithoutFieldsInput> | Prisma.doctorsCreateWithoutFieldsInput[] | Prisma.doctorsUncheckedCreateWithoutFieldsInput[]
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutFieldsInput | Prisma.doctorsCreateOrConnectWithoutFieldsInput[]
  upsert?: Prisma.doctorsUpsertWithWhereUniqueWithoutFieldsInput | Prisma.doctorsUpsertWithWhereUniqueWithoutFieldsInput[]
  createMany?: Prisma.doctorsCreateManyFieldsInputEnvelope
  set?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  disconnect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  delete?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  connect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  update?: Prisma.doctorsUpdateWithWhereUniqueWithoutFieldsInput | Prisma.doctorsUpdateWithWhereUniqueWithoutFieldsInput[]
  updateMany?: Prisma.doctorsUpdateManyWithWhereWithoutFieldsInput | Prisma.doctorsUpdateManyWithWhereWithoutFieldsInput[]
  deleteMany?: Prisma.doctorsScalarWhereInput | Prisma.doctorsScalarWhereInput[]
}

export type doctorsCreateNestedManyWithoutHospitalsInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutHospitalsInput, Prisma.doctorsUncheckedCreateWithoutHospitalsInput> | Prisma.doctorsCreateWithoutHospitalsInput[] | Prisma.doctorsUncheckedCreateWithoutHospitalsInput[]
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutHospitalsInput | Prisma.doctorsCreateOrConnectWithoutHospitalsInput[]
  createMany?: Prisma.doctorsCreateManyHospitalsInputEnvelope
  connect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
}

export type doctorsUncheckedCreateNestedManyWithoutHospitalsInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutHospitalsInput, Prisma.doctorsUncheckedCreateWithoutHospitalsInput> | Prisma.doctorsCreateWithoutHospitalsInput[] | Prisma.doctorsUncheckedCreateWithoutHospitalsInput[]
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutHospitalsInput | Prisma.doctorsCreateOrConnectWithoutHospitalsInput[]
  createMany?: Prisma.doctorsCreateManyHospitalsInputEnvelope
  connect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
}

export type doctorsUpdateManyWithoutHospitalsNestedInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutHospitalsInput, Prisma.doctorsUncheckedCreateWithoutHospitalsInput> | Prisma.doctorsCreateWithoutHospitalsInput[] | Prisma.doctorsUncheckedCreateWithoutHospitalsInput[]
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutHospitalsInput | Prisma.doctorsCreateOrConnectWithoutHospitalsInput[]
  upsert?: Prisma.doctorsUpsertWithWhereUniqueWithoutHospitalsInput | Prisma.doctorsUpsertWithWhereUniqueWithoutHospitalsInput[]
  createMany?: Prisma.doctorsCreateManyHospitalsInputEnvelope
  set?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  disconnect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  delete?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  connect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  update?: Prisma.doctorsUpdateWithWhereUniqueWithoutHospitalsInput | Prisma.doctorsUpdateWithWhereUniqueWithoutHospitalsInput[]
  updateMany?: Prisma.doctorsUpdateManyWithWhereWithoutHospitalsInput | Prisma.doctorsUpdateManyWithWhereWithoutHospitalsInput[]
  deleteMany?: Prisma.doctorsScalarWhereInput | Prisma.doctorsScalarWhereInput[]
}

export type doctorsUncheckedUpdateManyWithoutHospitalsNestedInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutHospitalsInput, Prisma.doctorsUncheckedCreateWithoutHospitalsInput> | Prisma.doctorsCreateWithoutHospitalsInput[] | Prisma.doctorsUncheckedCreateWithoutHospitalsInput[]
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutHospitalsInput | Prisma.doctorsCreateOrConnectWithoutHospitalsInput[]
  upsert?: Prisma.doctorsUpsertWithWhereUniqueWithoutHospitalsInput | Prisma.doctorsUpsertWithWhereUniqueWithoutHospitalsInput[]
  createMany?: Prisma.doctorsCreateManyHospitalsInputEnvelope
  set?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  disconnect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  delete?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  connect?: Prisma.doctorsWhereUniqueInput | Prisma.doctorsWhereUniqueInput[]
  update?: Prisma.doctorsUpdateWithWhereUniqueWithoutHospitalsInput | Prisma.doctorsUpdateWithWhereUniqueWithoutHospitalsInput[]
  updateMany?: Prisma.doctorsUpdateManyWithWhereWithoutHospitalsInput | Prisma.doctorsUpdateManyWithWhereWithoutHospitalsInput[]
  deleteMany?: Prisma.doctorsScalarWhereInput | Prisma.doctorsScalarWhereInput[]
}

export type doctorsCreateNestedOneWithoutRegistersInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutRegistersInput, Prisma.doctorsUncheckedCreateWithoutRegistersInput>
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutRegistersInput
  connect?: Prisma.doctorsWhereUniqueInput
}

export type doctorsUncheckedCreateNestedOneWithoutRegistersInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutRegistersInput, Prisma.doctorsUncheckedCreateWithoutRegistersInput>
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutRegistersInput
  connect?: Prisma.doctorsWhereUniqueInput
}

export type doctorsUpdateOneWithoutRegistersNestedInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutRegistersInput, Prisma.doctorsUncheckedCreateWithoutRegistersInput>
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutRegistersInput
  upsert?: Prisma.doctorsUpsertWithoutRegistersInput
  disconnect?: Prisma.doctorsWhereInput | boolean
  delete?: Prisma.doctorsWhereInput | boolean
  connect?: Prisma.doctorsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.doctorsUpdateToOneWithWhereWithoutRegistersInput, Prisma.doctorsUpdateWithoutRegistersInput>, Prisma.doctorsUncheckedUpdateWithoutRegistersInput>
}

export type doctorsUncheckedUpdateOneWithoutRegistersNestedInput = {
  create?: Prisma.XOR<Prisma.doctorsCreateWithoutRegistersInput, Prisma.doctorsUncheckedCreateWithoutRegistersInput>
  connectOrCreate?: Prisma.doctorsCreateOrConnectWithoutRegistersInput
  upsert?: Prisma.doctorsUpsertWithoutRegistersInput
  disconnect?: Prisma.doctorsWhereInput | boolean
  delete?: Prisma.doctorsWhereInput | boolean
  connect?: Prisma.doctorsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.doctorsUpdateToOneWithWhereWithoutRegistersInput, Prisma.doctorsUpdateWithoutRegistersInput>, Prisma.doctorsUncheckedUpdateWithoutRegistersInput>
}

export type doctorsCreateWithoutAppointmentsInput = {
  first_day?: Date | string
  registers: Prisma.registersCreateNestedOneWithoutDoctorsInput
  fields: Prisma.fieldsCreateNestedOneWithoutDoctorsInput
  hospitals: Prisma.hospitalsCreateNestedOneWithoutDoctorsInput
  expedients: Prisma.expedientsCreateNestedOneWithoutDoctorsInput
}

export type doctorsUncheckedCreateWithoutAppointmentsInput = {
  email: string
  id_field: number
  id_hospital: number
  id_expedient: number
  first_day?: Date | string
}

export type doctorsCreateOrConnectWithoutAppointmentsInput = {
  where: Prisma.doctorsWhereUniqueInput
  create: Prisma.XOR<Prisma.doctorsCreateWithoutAppointmentsInput, Prisma.doctorsUncheckedCreateWithoutAppointmentsInput>
}

export type doctorsUpsertWithoutAppointmentsInput = {
  update: Prisma.XOR<Prisma.doctorsUpdateWithoutAppointmentsInput, Prisma.doctorsUncheckedUpdateWithoutAppointmentsInput>
  create: Prisma.XOR<Prisma.doctorsCreateWithoutAppointmentsInput, Prisma.doctorsUncheckedCreateWithoutAppointmentsInput>
  where?: Prisma.doctorsWhereInput
}

export type doctorsUpdateToOneWithWhereWithoutAppointmentsInput = {
  where?: Prisma.doctorsWhereInput
  data: Prisma.XOR<Prisma.doctorsUpdateWithoutAppointmentsInput, Prisma.doctorsUncheckedUpdateWithoutAppointmentsInput>
}

export type doctorsUpdateWithoutAppointmentsInput = {
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registers?: Prisma.registersUpdateOneRequiredWithoutDoctorsNestedInput
  fields?: Prisma.fieldsUpdateOneRequiredWithoutDoctorsNestedInput
  hospitals?: Prisma.hospitalsUpdateOneRequiredWithoutDoctorsNestedInput
  expedients?: Prisma.expedientsUpdateOneRequiredWithoutDoctorsNestedInput
}

export type doctorsUncheckedUpdateWithoutAppointmentsInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  id_field?: Prisma.IntFieldUpdateOperationsInput | number
  id_hospital?: Prisma.IntFieldUpdateOperationsInput | number
  id_expedient?: Prisma.IntFieldUpdateOperationsInput | number
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type doctorsCreateWithoutExpedientsInput = {
  first_day?: Date | string
  appointments?: Prisma.appointmentsCreateNestedManyWithoutDoctorsInput
  registers: Prisma.registersCreateNestedOneWithoutDoctorsInput
  fields: Prisma.fieldsCreateNestedOneWithoutDoctorsInput
  hospitals: Prisma.hospitalsCreateNestedOneWithoutDoctorsInput
}

export type doctorsUncheckedCreateWithoutExpedientsInput = {
  email: string
  id_field: number
  id_hospital: number
  first_day?: Date | string
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutDoctorsInput
}

export type doctorsCreateOrConnectWithoutExpedientsInput = {
  where: Prisma.doctorsWhereUniqueInput
  create: Prisma.XOR<Prisma.doctorsCreateWithoutExpedientsInput, Prisma.doctorsUncheckedCreateWithoutExpedientsInput>
}

export type doctorsCreateManyExpedientsInputEnvelope = {
  data: Prisma.doctorsCreateManyExpedientsInput | Prisma.doctorsCreateManyExpedientsInput[]
  skipDuplicates?: boolean
}

export type doctorsUpsertWithWhereUniqueWithoutExpedientsInput = {
  where: Prisma.doctorsWhereUniqueInput
  update: Prisma.XOR<Prisma.doctorsUpdateWithoutExpedientsInput, Prisma.doctorsUncheckedUpdateWithoutExpedientsInput>
  create: Prisma.XOR<Prisma.doctorsCreateWithoutExpedientsInput, Prisma.doctorsUncheckedCreateWithoutExpedientsInput>
}

export type doctorsUpdateWithWhereUniqueWithoutExpedientsInput = {
  where: Prisma.doctorsWhereUniqueInput
  data: Prisma.XOR<Prisma.doctorsUpdateWithoutExpedientsInput, Prisma.doctorsUncheckedUpdateWithoutExpedientsInput>
}

export type doctorsUpdateManyWithWhereWithoutExpedientsInput = {
  where: Prisma.doctorsScalarWhereInput
  data: Prisma.XOR<Prisma.doctorsUpdateManyMutationInput, Prisma.doctorsUncheckedUpdateManyWithoutExpedientsInput>
}

export type doctorsScalarWhereInput = {
  AND?: Prisma.doctorsScalarWhereInput | Prisma.doctorsScalarWhereInput[]
  OR?: Prisma.doctorsScalarWhereInput[]
  NOT?: Prisma.doctorsScalarWhereInput | Prisma.doctorsScalarWhereInput[]
  email?: Prisma.StringFilter<"doctors"> | string
  id_field?: Prisma.IntFilter<"doctors"> | number
  id_hospital?: Prisma.IntFilter<"doctors"> | number
  id_expedient?: Prisma.IntFilter<"doctors"> | number
  first_day?: Prisma.DateTimeFilter<"doctors"> | Date | string
}

export type doctorsCreateWithoutFieldsInput = {
  first_day?: Date | string
  appointments?: Prisma.appointmentsCreateNestedManyWithoutDoctorsInput
  registers: Prisma.registersCreateNestedOneWithoutDoctorsInput
  hospitals: Prisma.hospitalsCreateNestedOneWithoutDoctorsInput
  expedients: Prisma.expedientsCreateNestedOneWithoutDoctorsInput
}

export type doctorsUncheckedCreateWithoutFieldsInput = {
  email: string
  id_hospital: number
  id_expedient: number
  first_day?: Date | string
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutDoctorsInput
}

export type doctorsCreateOrConnectWithoutFieldsInput = {
  where: Prisma.doctorsWhereUniqueInput
  create: Prisma.XOR<Prisma.doctorsCreateWithoutFieldsInput, Prisma.doctorsUncheckedCreateWithoutFieldsInput>
}

export type doctorsCreateManyFieldsInputEnvelope = {
  data: Prisma.doctorsCreateManyFieldsInput | Prisma.doctorsCreateManyFieldsInput[]
  skipDuplicates?: boolean
}

export type doctorsUpsertWithWhereUniqueWithoutFieldsInput = {
  where: Prisma.doctorsWhereUniqueInput
  update: Prisma.XOR<Prisma.doctorsUpdateWithoutFieldsInput, Prisma.doctorsUncheckedUpdateWithoutFieldsInput>
  create: Prisma.XOR<Prisma.doctorsCreateWithoutFieldsInput, Prisma.doctorsUncheckedCreateWithoutFieldsInput>
}

export type doctorsUpdateWithWhereUniqueWithoutFieldsInput = {
  where: Prisma.doctorsWhereUniqueInput
  data: Prisma.XOR<Prisma.doctorsUpdateWithoutFieldsInput, Prisma.doctorsUncheckedUpdateWithoutFieldsInput>
}

export type doctorsUpdateManyWithWhereWithoutFieldsInput = {
  where: Prisma.doctorsScalarWhereInput
  data: Prisma.XOR<Prisma.doctorsUpdateManyMutationInput, Prisma.doctorsUncheckedUpdateManyWithoutFieldsInput>
}

export type doctorsCreateWithoutHospitalsInput = {
  first_day?: Date | string
  appointments?: Prisma.appointmentsCreateNestedManyWithoutDoctorsInput
  registers: Prisma.registersCreateNestedOneWithoutDoctorsInput
  fields: Prisma.fieldsCreateNestedOneWithoutDoctorsInput
  expedients: Prisma.expedientsCreateNestedOneWithoutDoctorsInput
}

export type doctorsUncheckedCreateWithoutHospitalsInput = {
  email: string
  id_field: number
  id_expedient: number
  first_day?: Date | string
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutDoctorsInput
}

export type doctorsCreateOrConnectWithoutHospitalsInput = {
  where: Prisma.doctorsWhereUniqueInput
  create: Prisma.XOR<Prisma.doctorsCreateWithoutHospitalsInput, Prisma.doctorsUncheckedCreateWithoutHospitalsInput>
}

export type doctorsCreateManyHospitalsInputEnvelope = {
  data: Prisma.doctorsCreateManyHospitalsInput | Prisma.doctorsCreateManyHospitalsInput[]
  skipDuplicates?: boolean
}

export type doctorsUpsertWithWhereUniqueWithoutHospitalsInput = {
  where: Prisma.doctorsWhereUniqueInput
  update: Prisma.XOR<Prisma.doctorsUpdateWithoutHospitalsInput, Prisma.doctorsUncheckedUpdateWithoutHospitalsInput>
  create: Prisma.XOR<Prisma.doctorsCreateWithoutHospitalsInput, Prisma.doctorsUncheckedCreateWithoutHospitalsInput>
}

export type doctorsUpdateWithWhereUniqueWithoutHospitalsInput = {
  where: Prisma.doctorsWhereUniqueInput
  data: Prisma.XOR<Prisma.doctorsUpdateWithoutHospitalsInput, Prisma.doctorsUncheckedUpdateWithoutHospitalsInput>
}

export type doctorsUpdateManyWithWhereWithoutHospitalsInput = {
  where: Prisma.doctorsScalarWhereInput
  data: Prisma.XOR<Prisma.doctorsUpdateManyMutationInput, Prisma.doctorsUncheckedUpdateManyWithoutHospitalsInput>
}

export type doctorsCreateWithoutRegistersInput = {
  first_day?: Date | string
  appointments?: Prisma.appointmentsCreateNestedManyWithoutDoctorsInput
  fields: Prisma.fieldsCreateNestedOneWithoutDoctorsInput
  hospitals: Prisma.hospitalsCreateNestedOneWithoutDoctorsInput
  expedients: Prisma.expedientsCreateNestedOneWithoutDoctorsInput
}

export type doctorsUncheckedCreateWithoutRegistersInput = {
  id_field: number
  id_hospital: number
  id_expedient: number
  first_day?: Date | string
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutDoctorsInput
}

export type doctorsCreateOrConnectWithoutRegistersInput = {
  where: Prisma.doctorsWhereUniqueInput
  create: Prisma.XOR<Prisma.doctorsCreateWithoutRegistersInput, Prisma.doctorsUncheckedCreateWithoutRegistersInput>
}

export type doctorsUpsertWithoutRegistersInput = {
  update: Prisma.XOR<Prisma.doctorsUpdateWithoutRegistersInput, Prisma.doctorsUncheckedUpdateWithoutRegistersInput>
  create: Prisma.XOR<Prisma.doctorsCreateWithoutRegistersInput, Prisma.doctorsUncheckedCreateWithoutRegistersInput>
  where?: Prisma.doctorsWhereInput
}

export type doctorsUpdateToOneWithWhereWithoutRegistersInput = {
  where?: Prisma.doctorsWhereInput
  data: Prisma.XOR<Prisma.doctorsUpdateWithoutRegistersInput, Prisma.doctorsUncheckedUpdateWithoutRegistersInput>
}

export type doctorsUpdateWithoutRegistersInput = {
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.appointmentsUpdateManyWithoutDoctorsNestedInput
  fields?: Prisma.fieldsUpdateOneRequiredWithoutDoctorsNestedInput
  hospitals?: Prisma.hospitalsUpdateOneRequiredWithoutDoctorsNestedInput
  expedients?: Prisma.expedientsUpdateOneRequiredWithoutDoctorsNestedInput
}

export type doctorsUncheckedUpdateWithoutRegistersInput = {
  id_field?: Prisma.IntFieldUpdateOperationsInput | number
  id_hospital?: Prisma.IntFieldUpdateOperationsInput | number
  id_expedient?: Prisma.IntFieldUpdateOperationsInput | number
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutDoctorsNestedInput
}

export type doctorsCreateManyExpedientsInput = {
  email: string
  id_field: number
  id_hospital: number
  first_day?: Date | string
}

export type doctorsUpdateWithoutExpedientsInput = {
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.appointmentsUpdateManyWithoutDoctorsNestedInput
  registers?: Prisma.registersUpdateOneRequiredWithoutDoctorsNestedInput
  fields?: Prisma.fieldsUpdateOneRequiredWithoutDoctorsNestedInput
  hospitals?: Prisma.hospitalsUpdateOneRequiredWithoutDoctorsNestedInput
}

export type doctorsUncheckedUpdateWithoutExpedientsInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  id_field?: Prisma.IntFieldUpdateOperationsInput | number
  id_hospital?: Prisma.IntFieldUpdateOperationsInput | number
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutDoctorsNestedInput
}

export type doctorsUncheckedUpdateManyWithoutExpedientsInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  id_field?: Prisma.IntFieldUpdateOperationsInput | number
  id_hospital?: Prisma.IntFieldUpdateOperationsInput | number
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type doctorsCreateManyFieldsInput = {
  email: string
  id_hospital: number
  id_expedient: number
  first_day?: Date | string
}

export type doctorsUpdateWithoutFieldsInput = {
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.appointmentsUpdateManyWithoutDoctorsNestedInput
  registers?: Prisma.registersUpdateOneRequiredWithoutDoctorsNestedInput
  hospitals?: Prisma.hospitalsUpdateOneRequiredWithoutDoctorsNestedInput
  expedients?: Prisma.expedientsUpdateOneRequiredWithoutDoctorsNestedInput
}

export type doctorsUncheckedUpdateWithoutFieldsInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  id_hospital?: Prisma.IntFieldUpdateOperationsInput | number
  id_expedient?: Prisma.IntFieldUpdateOperationsInput | number
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutDoctorsNestedInput
}

export type doctorsUncheckedUpdateManyWithoutFieldsInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  id_hospital?: Prisma.IntFieldUpdateOperationsInput | number
  id_expedient?: Prisma.IntFieldUpdateOperationsInput | number
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type doctorsCreateManyHospitalsInput = {
  email: string
  id_field: number
  id_expedient: number
  first_day?: Date | string
}

export type doctorsUpdateWithoutHospitalsInput = {
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.appointmentsUpdateManyWithoutDoctorsNestedInput
  registers?: Prisma.registersUpdateOneRequiredWithoutDoctorsNestedInput
  fields?: Prisma.fieldsUpdateOneRequiredWithoutDoctorsNestedInput
  expedients?: Prisma.expedientsUpdateOneRequiredWithoutDoctorsNestedInput
}

export type doctorsUncheckedUpdateWithoutHospitalsInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  id_field?: Prisma.IntFieldUpdateOperationsInput | number
  id_expedient?: Prisma.IntFieldUpdateOperationsInput | number
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutDoctorsNestedInput
}

export type doctorsUncheckedUpdateManyWithoutHospitalsInput = {
  email?: Prisma.StringFieldUpdateOperationsInput | string
  id_field?: Prisma.IntFieldUpdateOperationsInput | number
  id_expedient?: Prisma.IntFieldUpdateOperationsInput | number
  first_day?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type DoctorsCountOutputType
 */

export type DoctorsCountOutputType = {
  appointments: number
}

export type DoctorsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointments?: boolean | DoctorsCountOutputTypeCountAppointmentsArgs
}

/**
 * DoctorsCountOutputType without action
 */
export type DoctorsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DoctorsCountOutputType
   */
  select?: Prisma.DoctorsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DoctorsCountOutputType without action
 */
export type DoctorsCountOutputTypeCountAppointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.appointmentsWhereInput
}


export type doctorsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  email?: boolean
  id_field?: boolean
  id_hospital?: boolean
  id_expedient?: boolean
  first_day?: boolean
  appointments?: boolean | Prisma.doctors$appointmentsArgs<ExtArgs>
  registers?: boolean | Prisma.registersDefaultArgs<ExtArgs>
  fields?: boolean | Prisma.fieldsDefaultArgs<ExtArgs>
  hospitals?: boolean | Prisma.hospitalsDefaultArgs<ExtArgs>
  expedients?: boolean | Prisma.expedientsDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.DoctorsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["doctors"]>



export type doctorsSelectScalar = {
  email?: boolean
  id_field?: boolean
  id_hospital?: boolean
  id_expedient?: boolean
  first_day?: boolean
}

export type doctorsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"email" | "id_field" | "id_hospital" | "id_expedient" | "first_day", ExtArgs["result"]["doctors"]>
export type doctorsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointments?: boolean | Prisma.doctors$appointmentsArgs<ExtArgs>
  registers?: boolean | Prisma.registersDefaultArgs<ExtArgs>
  fields?: boolean | Prisma.fieldsDefaultArgs<ExtArgs>
  hospitals?: boolean | Prisma.hospitalsDefaultArgs<ExtArgs>
  expedients?: boolean | Prisma.expedientsDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.DoctorsCountOutputTypeDefaultArgs<ExtArgs>
}

export type $doctorsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "doctors"
  objects: {
    appointments: Prisma.$appointmentsPayload<ExtArgs>[]
    registers: Prisma.$registersPayload<ExtArgs>
    fields: Prisma.$fieldsPayload<ExtArgs>
    hospitals: Prisma.$hospitalsPayload<ExtArgs>
    expedients: Prisma.$expedientsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    email: string
    id_field: number
    id_hospital: number
    id_expedient: number
    first_day: Date
  }, ExtArgs["result"]["doctors"]>
  composites: {}
}

export type doctorsGetPayload<S extends boolean | null | undefined | doctorsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$doctorsPayload, S>

export type doctorsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<doctorsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DoctorsCountAggregateInputType | true
  }

export interface doctorsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['doctors'], meta: { name: 'doctors' } }
  /**
   * Find zero or one Doctors that matches the filter.
   * @param {doctorsFindUniqueArgs} args - Arguments to find a Doctors
   * @example
   * // Get one Doctors
   * const doctors = await prisma.doctors.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends doctorsFindUniqueArgs>(args: Prisma.SelectSubset<T, doctorsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__doctorsClient<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Doctors that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {doctorsFindUniqueOrThrowArgs} args - Arguments to find a Doctors
   * @example
   * // Get one Doctors
   * const doctors = await prisma.doctors.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends doctorsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, doctorsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__doctorsClient<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Doctors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {doctorsFindFirstArgs} args - Arguments to find a Doctors
   * @example
   * // Get one Doctors
   * const doctors = await prisma.doctors.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends doctorsFindFirstArgs>(args?: Prisma.SelectSubset<T, doctorsFindFirstArgs<ExtArgs>>): Prisma.Prisma__doctorsClient<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Doctors that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {doctorsFindFirstOrThrowArgs} args - Arguments to find a Doctors
   * @example
   * // Get one Doctors
   * const doctors = await prisma.doctors.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends doctorsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, doctorsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__doctorsClient<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Doctors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {doctorsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Doctors
   * const doctors = await prisma.doctors.findMany()
   * 
   * // Get first 10 Doctors
   * const doctors = await prisma.doctors.findMany({ take: 10 })
   * 
   * // Only select the `email`
   * const doctorsWithEmailOnly = await prisma.doctors.findMany({ select: { email: true } })
   * 
   */
  findMany<T extends doctorsFindManyArgs>(args?: Prisma.SelectSubset<T, doctorsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Doctors.
   * @param {doctorsCreateArgs} args - Arguments to create a Doctors.
   * @example
   * // Create one Doctors
   * const Doctors = await prisma.doctors.create({
   *   data: {
   *     // ... data to create a Doctors
   *   }
   * })
   * 
   */
  create<T extends doctorsCreateArgs>(args: Prisma.SelectSubset<T, doctorsCreateArgs<ExtArgs>>): Prisma.Prisma__doctorsClient<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Doctors.
   * @param {doctorsCreateManyArgs} args - Arguments to create many Doctors.
   * @example
   * // Create many Doctors
   * const doctors = await prisma.doctors.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends doctorsCreateManyArgs>(args?: Prisma.SelectSubset<T, doctorsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Doctors.
   * @param {doctorsDeleteArgs} args - Arguments to delete one Doctors.
   * @example
   * // Delete one Doctors
   * const Doctors = await prisma.doctors.delete({
   *   where: {
   *     // ... filter to delete one Doctors
   *   }
   * })
   * 
   */
  delete<T extends doctorsDeleteArgs>(args: Prisma.SelectSubset<T, doctorsDeleteArgs<ExtArgs>>): Prisma.Prisma__doctorsClient<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Doctors.
   * @param {doctorsUpdateArgs} args - Arguments to update one Doctors.
   * @example
   * // Update one Doctors
   * const doctors = await prisma.doctors.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends doctorsUpdateArgs>(args: Prisma.SelectSubset<T, doctorsUpdateArgs<ExtArgs>>): Prisma.Prisma__doctorsClient<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Doctors.
   * @param {doctorsDeleteManyArgs} args - Arguments to filter Doctors to delete.
   * @example
   * // Delete a few Doctors
   * const { count } = await prisma.doctors.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends doctorsDeleteManyArgs>(args?: Prisma.SelectSubset<T, doctorsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Doctors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {doctorsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Doctors
   * const doctors = await prisma.doctors.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends doctorsUpdateManyArgs>(args: Prisma.SelectSubset<T, doctorsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Doctors.
   * @param {doctorsUpsertArgs} args - Arguments to update or create a Doctors.
   * @example
   * // Update or create a Doctors
   * const doctors = await prisma.doctors.upsert({
   *   create: {
   *     // ... data to create a Doctors
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Doctors we want to update
   *   }
   * })
   */
  upsert<T extends doctorsUpsertArgs>(args: Prisma.SelectSubset<T, doctorsUpsertArgs<ExtArgs>>): Prisma.Prisma__doctorsClient<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Doctors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {doctorsCountArgs} args - Arguments to filter Doctors to count.
   * @example
   * // Count the number of Doctors
   * const count = await prisma.doctors.count({
   *   where: {
   *     // ... the filter for the Doctors we want to count
   *   }
   * })
  **/
  count<T extends doctorsCountArgs>(
    args?: Prisma.Subset<T, doctorsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DoctorsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Doctors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DoctorsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DoctorsAggregateArgs>(args: Prisma.Subset<T, DoctorsAggregateArgs>): Prisma.PrismaPromise<GetDoctorsAggregateType<T>>

  /**
   * Group by Doctors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {doctorsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends doctorsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: doctorsGroupByArgs['orderBy'] }
      : { orderBy?: doctorsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, doctorsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDoctorsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the doctors model
 */
readonly fields: doctorsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for doctors.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__doctorsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  appointments<T extends Prisma.doctors$appointmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.doctors$appointmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  registers<T extends Prisma.registersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.registersDefaultArgs<ExtArgs>>): Prisma.Prisma__registersClient<runtime.Types.Result.GetResult<Prisma.$registersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  fields<T extends Prisma.fieldsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.fieldsDefaultArgs<ExtArgs>>): Prisma.Prisma__fieldsClient<runtime.Types.Result.GetResult<Prisma.$fieldsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  hospitals<T extends Prisma.hospitalsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.hospitalsDefaultArgs<ExtArgs>>): Prisma.Prisma__hospitalsClient<runtime.Types.Result.GetResult<Prisma.$hospitalsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  expedients<T extends Prisma.expedientsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.expedientsDefaultArgs<ExtArgs>>): Prisma.Prisma__expedientsClient<runtime.Types.Result.GetResult<Prisma.$expedientsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the doctors model
 */
export interface doctorsFieldRefs {
  readonly email: Prisma.FieldRef<"doctors", 'String'>
  readonly id_field: Prisma.FieldRef<"doctors", 'Int'>
  readonly id_hospital: Prisma.FieldRef<"doctors", 'Int'>
  readonly id_expedient: Prisma.FieldRef<"doctors", 'Int'>
  readonly first_day: Prisma.FieldRef<"doctors", 'DateTime'>
}
    

// Custom InputTypes
/**
 * doctors findUnique
 */
export type doctorsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
  /**
   * Filter, which doctors to fetch.
   */
  where: Prisma.doctorsWhereUniqueInput
}

/**
 * doctors findUniqueOrThrow
 */
export type doctorsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
  /**
   * Filter, which doctors to fetch.
   */
  where: Prisma.doctorsWhereUniqueInput
}

/**
 * doctors findFirst
 */
export type doctorsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
  /**
   * Filter, which doctors to fetch.
   */
  where?: Prisma.doctorsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of doctors to fetch.
   */
  orderBy?: Prisma.doctorsOrderByWithRelationInput | Prisma.doctorsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for doctors.
   */
  cursor?: Prisma.doctorsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` doctors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` doctors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of doctors.
   */
  distinct?: Prisma.DoctorsScalarFieldEnum | Prisma.DoctorsScalarFieldEnum[]
}

/**
 * doctors findFirstOrThrow
 */
export type doctorsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
  /**
   * Filter, which doctors to fetch.
   */
  where?: Prisma.doctorsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of doctors to fetch.
   */
  orderBy?: Prisma.doctorsOrderByWithRelationInput | Prisma.doctorsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for doctors.
   */
  cursor?: Prisma.doctorsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` doctors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` doctors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of doctors.
   */
  distinct?: Prisma.DoctorsScalarFieldEnum | Prisma.DoctorsScalarFieldEnum[]
}

/**
 * doctors findMany
 */
export type doctorsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
  /**
   * Filter, which doctors to fetch.
   */
  where?: Prisma.doctorsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of doctors to fetch.
   */
  orderBy?: Prisma.doctorsOrderByWithRelationInput | Prisma.doctorsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing doctors.
   */
  cursor?: Prisma.doctorsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` doctors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` doctors.
   */
  skip?: number
  distinct?: Prisma.DoctorsScalarFieldEnum | Prisma.DoctorsScalarFieldEnum[]
}

/**
 * doctors create
 */
export type doctorsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
  /**
   * The data needed to create a doctors.
   */
  data: Prisma.XOR<Prisma.doctorsCreateInput, Prisma.doctorsUncheckedCreateInput>
}

/**
 * doctors createMany
 */
export type doctorsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many doctors.
   */
  data: Prisma.doctorsCreateManyInput | Prisma.doctorsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * doctors update
 */
export type doctorsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
  /**
   * The data needed to update a doctors.
   */
  data: Prisma.XOR<Prisma.doctorsUpdateInput, Prisma.doctorsUncheckedUpdateInput>
  /**
   * Choose, which doctors to update.
   */
  where: Prisma.doctorsWhereUniqueInput
}

/**
 * doctors updateMany
 */
export type doctorsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update doctors.
   */
  data: Prisma.XOR<Prisma.doctorsUpdateManyMutationInput, Prisma.doctorsUncheckedUpdateManyInput>
  /**
   * Filter which doctors to update
   */
  where?: Prisma.doctorsWhereInput
  /**
   * Limit how many doctors to update.
   */
  limit?: number
}

/**
 * doctors upsert
 */
export type doctorsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
  /**
   * The filter to search for the doctors to update in case it exists.
   */
  where: Prisma.doctorsWhereUniqueInput
  /**
   * In case the doctors found by the `where` argument doesn't exist, create a new doctors with this data.
   */
  create: Prisma.XOR<Prisma.doctorsCreateInput, Prisma.doctorsUncheckedCreateInput>
  /**
   * In case the doctors was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.doctorsUpdateInput, Prisma.doctorsUncheckedUpdateInput>
}

/**
 * doctors delete
 */
export type doctorsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
  /**
   * Filter which doctors to delete.
   */
  where: Prisma.doctorsWhereUniqueInput
}

/**
 * doctors deleteMany
 */
export type doctorsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which doctors to delete
   */
  where?: Prisma.doctorsWhereInput
  /**
   * Limit how many doctors to delete.
   */
  limit?: number
}

/**
 * doctors.appointments
 */
export type doctors$appointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  where?: Prisma.appointmentsWhereInput
  orderBy?: Prisma.appointmentsOrderByWithRelationInput | Prisma.appointmentsOrderByWithRelationInput[]
  cursor?: Prisma.appointmentsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AppointmentsScalarFieldEnum | Prisma.AppointmentsScalarFieldEnum[]
}

/**
 * doctors without action
 */
export type doctorsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
}
