
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `expedients` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model expedients
 * 
 */
export type expedientsModel = runtime.Types.Result.DefaultSelection<Prisma.$expedientsPayload>

export type AggregateExpedients = {
  _count: ExpedientsCountAggregateOutputType | null
  _avg: ExpedientsAvgAggregateOutputType | null
  _sum: ExpedientsSumAggregateOutputType | null
  _min: ExpedientsMinAggregateOutputType | null
  _max: ExpedientsMaxAggregateOutputType | null
}

export type ExpedientsAvgAggregateOutputType = {
  id: number | null
}

export type ExpedientsSumAggregateOutputType = {
  id: number | null
}

export type ExpedientsMinAggregateOutputType = {
  id: number | null
  duration: Date | null
  description: string | null
}

export type ExpedientsMaxAggregateOutputType = {
  id: number | null
  duration: Date | null
  description: string | null
}

export type ExpedientsCountAggregateOutputType = {
  id: number
  duration: number
  description: number
  _all: number
}


export type ExpedientsAvgAggregateInputType = {
  id?: true
}

export type ExpedientsSumAggregateInputType = {
  id?: true
}

export type ExpedientsMinAggregateInputType = {
  id?: true
  duration?: true
  description?: true
}

export type ExpedientsMaxAggregateInputType = {
  id?: true
  duration?: true
  description?: true
}

export type ExpedientsCountAggregateInputType = {
  id?: true
  duration?: true
  description?: true
  _all?: true
}

export type ExpedientsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which expedients to aggregate.
   */
  where?: Prisma.expedientsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of expedients to fetch.
   */
  orderBy?: Prisma.expedientsOrderByWithRelationInput | Prisma.expedientsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.expedientsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` expedients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` expedients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned expedients
  **/
  _count?: true | ExpedientsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ExpedientsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ExpedientsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ExpedientsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ExpedientsMaxAggregateInputType
}

export type GetExpedientsAggregateType<T extends ExpedientsAggregateArgs> = {
      [P in keyof T & keyof AggregateExpedients]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExpedients[P]>
    : Prisma.GetScalarType<T[P], AggregateExpedients[P]>
}




export type expedientsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.expedientsWhereInput
  orderBy?: Prisma.expedientsOrderByWithAggregationInput | Prisma.expedientsOrderByWithAggregationInput[]
  by: Prisma.ExpedientsScalarFieldEnum[] | Prisma.ExpedientsScalarFieldEnum
  having?: Prisma.expedientsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ExpedientsCountAggregateInputType | true
  _avg?: ExpedientsAvgAggregateInputType
  _sum?: ExpedientsSumAggregateInputType
  _min?: ExpedientsMinAggregateInputType
  _max?: ExpedientsMaxAggregateInputType
}

export type ExpedientsGroupByOutputType = {
  id: number
  duration: Date
  description: string | null
  _count: ExpedientsCountAggregateOutputType | null
  _avg: ExpedientsAvgAggregateOutputType | null
  _sum: ExpedientsSumAggregateOutputType | null
  _min: ExpedientsMinAggregateOutputType | null
  _max: ExpedientsMaxAggregateOutputType | null
}

type GetExpedientsGroupByPayload<T extends expedientsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ExpedientsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ExpedientsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ExpedientsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ExpedientsGroupByOutputType[P]>
      }
    >
  >



export type expedientsWhereInput = {
  AND?: Prisma.expedientsWhereInput | Prisma.expedientsWhereInput[]
  OR?: Prisma.expedientsWhereInput[]
  NOT?: Prisma.expedientsWhereInput | Prisma.expedientsWhereInput[]
  id?: Prisma.IntFilter<"expedients"> | number
  duration?: Prisma.DateTimeFilter<"expedients"> | Date | string
  description?: Prisma.StringNullableFilter<"expedients"> | string | null
  doctors?: Prisma.DoctorsListRelationFilter
  weekdays?: Prisma.WeekdaysListRelationFilter
}

export type expedientsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  doctors?: Prisma.doctorsOrderByRelationAggregateInput
  weekdays?: Prisma.weekdaysOrderByRelationAggregateInput
  _relevance?: Prisma.expedientsOrderByRelevanceInput
}

export type expedientsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.expedientsWhereInput | Prisma.expedientsWhereInput[]
  OR?: Prisma.expedientsWhereInput[]
  NOT?: Prisma.expedientsWhereInput | Prisma.expedientsWhereInput[]
  duration?: Prisma.DateTimeFilter<"expedients"> | Date | string
  description?: Prisma.StringNullableFilter<"expedients"> | string | null
  doctors?: Prisma.DoctorsListRelationFilter
  weekdays?: Prisma.WeekdaysListRelationFilter
}, "id">

export type expedientsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.expedientsCountOrderByAggregateInput
  _avg?: Prisma.expedientsAvgOrderByAggregateInput
  _max?: Prisma.expedientsMaxOrderByAggregateInput
  _min?: Prisma.expedientsMinOrderByAggregateInput
  _sum?: Prisma.expedientsSumOrderByAggregateInput
}

export type expedientsScalarWhereWithAggregatesInput = {
  AND?: Prisma.expedientsScalarWhereWithAggregatesInput | Prisma.expedientsScalarWhereWithAggregatesInput[]
  OR?: Prisma.expedientsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.expedientsScalarWhereWithAggregatesInput | Prisma.expedientsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"expedients"> | number
  duration?: Prisma.DateTimeWithAggregatesFilter<"expedients"> | Date | string
  description?: Prisma.StringNullableWithAggregatesFilter<"expedients"> | string | null
}

export type expedientsCreateInput = {
  duration: Date | string
  description?: string | null
  doctors?: Prisma.doctorsCreateNestedManyWithoutExpedientsInput
  weekdays?: Prisma.weekdaysCreateNestedManyWithoutExpedientsInput
}

export type expedientsUncheckedCreateInput = {
  id?: number
  duration: Date | string
  description?: string | null
  doctors?: Prisma.doctorsUncheckedCreateNestedManyWithoutExpedientsInput
  weekdays?: Prisma.weekdaysUncheckedCreateNestedManyWithoutExpedientsInput
}

export type expedientsUpdateInput = {
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  doctors?: Prisma.doctorsUpdateManyWithoutExpedientsNestedInput
  weekdays?: Prisma.weekdaysUpdateManyWithoutExpedientsNestedInput
}

export type expedientsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  doctors?: Prisma.doctorsUncheckedUpdateManyWithoutExpedientsNestedInput
  weekdays?: Prisma.weekdaysUncheckedUpdateManyWithoutExpedientsNestedInput
}

export type expedientsCreateManyInput = {
  id?: number
  duration: Date | string
  description?: string | null
}

export type expedientsUpdateManyMutationInput = {
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type expedientsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ExpedientsScalarRelationFilter = {
  is?: Prisma.expedientsWhereInput
  isNot?: Prisma.expedientsWhereInput
}

export type expedientsOrderByRelevanceInput = {
  fields: Prisma.expedientsOrderByRelevanceFieldEnum | Prisma.expedientsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type expedientsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type expedientsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type expedientsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type expedientsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type expedientsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type expedientsCreateNestedOneWithoutDoctorsInput = {
  create?: Prisma.XOR<Prisma.expedientsCreateWithoutDoctorsInput, Prisma.expedientsUncheckedCreateWithoutDoctorsInput>
  connectOrCreate?: Prisma.expedientsCreateOrConnectWithoutDoctorsInput
  connect?: Prisma.expedientsWhereUniqueInput
}

export type expedientsUpdateOneRequiredWithoutDoctorsNestedInput = {
  create?: Prisma.XOR<Prisma.expedientsCreateWithoutDoctorsInput, Prisma.expedientsUncheckedCreateWithoutDoctorsInput>
  connectOrCreate?: Prisma.expedientsCreateOrConnectWithoutDoctorsInput
  upsert?: Prisma.expedientsUpsertWithoutDoctorsInput
  connect?: Prisma.expedientsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.expedientsUpdateToOneWithWhereWithoutDoctorsInput, Prisma.expedientsUpdateWithoutDoctorsInput>, Prisma.expedientsUncheckedUpdateWithoutDoctorsInput>
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type expedientsCreateNestedOneWithoutWeekdaysInput = {
  create?: Prisma.XOR<Prisma.expedientsCreateWithoutWeekdaysInput, Prisma.expedientsUncheckedCreateWithoutWeekdaysInput>
  connectOrCreate?: Prisma.expedientsCreateOrConnectWithoutWeekdaysInput
  connect?: Prisma.expedientsWhereUniqueInput
}

export type expedientsUpdateOneRequiredWithoutWeekdaysNestedInput = {
  create?: Prisma.XOR<Prisma.expedientsCreateWithoutWeekdaysInput, Prisma.expedientsUncheckedCreateWithoutWeekdaysInput>
  connectOrCreate?: Prisma.expedientsCreateOrConnectWithoutWeekdaysInput
  upsert?: Prisma.expedientsUpsertWithoutWeekdaysInput
  connect?: Prisma.expedientsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.expedientsUpdateToOneWithWhereWithoutWeekdaysInput, Prisma.expedientsUpdateWithoutWeekdaysInput>, Prisma.expedientsUncheckedUpdateWithoutWeekdaysInput>
}

export type expedientsCreateWithoutDoctorsInput = {
  duration: Date | string
  description?: string | null
  weekdays?: Prisma.weekdaysCreateNestedManyWithoutExpedientsInput
}

export type expedientsUncheckedCreateWithoutDoctorsInput = {
  id?: number
  duration: Date | string
  description?: string | null
  weekdays?: Prisma.weekdaysUncheckedCreateNestedManyWithoutExpedientsInput
}

export type expedientsCreateOrConnectWithoutDoctorsInput = {
  where: Prisma.expedientsWhereUniqueInput
  create: Prisma.XOR<Prisma.expedientsCreateWithoutDoctorsInput, Prisma.expedientsUncheckedCreateWithoutDoctorsInput>
}

export type expedientsUpsertWithoutDoctorsInput = {
  update: Prisma.XOR<Prisma.expedientsUpdateWithoutDoctorsInput, Prisma.expedientsUncheckedUpdateWithoutDoctorsInput>
  create: Prisma.XOR<Prisma.expedientsCreateWithoutDoctorsInput, Prisma.expedientsUncheckedCreateWithoutDoctorsInput>
  where?: Prisma.expedientsWhereInput
}

export type expedientsUpdateToOneWithWhereWithoutDoctorsInput = {
  where?: Prisma.expedientsWhereInput
  data: Prisma.XOR<Prisma.expedientsUpdateWithoutDoctorsInput, Prisma.expedientsUncheckedUpdateWithoutDoctorsInput>
}

export type expedientsUpdateWithoutDoctorsInput = {
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  weekdays?: Prisma.weekdaysUpdateManyWithoutExpedientsNestedInput
}

export type expedientsUncheckedUpdateWithoutDoctorsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  weekdays?: Prisma.weekdaysUncheckedUpdateManyWithoutExpedientsNestedInput
}

export type expedientsCreateWithoutWeekdaysInput = {
  duration: Date | string
  description?: string | null
  doctors?: Prisma.doctorsCreateNestedManyWithoutExpedientsInput
}

export type expedientsUncheckedCreateWithoutWeekdaysInput = {
  id?: number
  duration: Date | string
  description?: string | null
  doctors?: Prisma.doctorsUncheckedCreateNestedManyWithoutExpedientsInput
}

export type expedientsCreateOrConnectWithoutWeekdaysInput = {
  where: Prisma.expedientsWhereUniqueInput
  create: Prisma.XOR<Prisma.expedientsCreateWithoutWeekdaysInput, Prisma.expedientsUncheckedCreateWithoutWeekdaysInput>
}

export type expedientsUpsertWithoutWeekdaysInput = {
  update: Prisma.XOR<Prisma.expedientsUpdateWithoutWeekdaysInput, Prisma.expedientsUncheckedUpdateWithoutWeekdaysInput>
  create: Prisma.XOR<Prisma.expedientsCreateWithoutWeekdaysInput, Prisma.expedientsUncheckedCreateWithoutWeekdaysInput>
  where?: Prisma.expedientsWhereInput
}

export type expedientsUpdateToOneWithWhereWithoutWeekdaysInput = {
  where?: Prisma.expedientsWhereInput
  data: Prisma.XOR<Prisma.expedientsUpdateWithoutWeekdaysInput, Prisma.expedientsUncheckedUpdateWithoutWeekdaysInput>
}

export type expedientsUpdateWithoutWeekdaysInput = {
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  doctors?: Prisma.doctorsUpdateManyWithoutExpedientsNestedInput
}

export type expedientsUncheckedUpdateWithoutWeekdaysInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  doctors?: Prisma.doctorsUncheckedUpdateManyWithoutExpedientsNestedInput
}


/**
 * Count Type ExpedientsCountOutputType
 */

export type ExpedientsCountOutputType = {
  doctors: number
  weekdays: number
}

export type ExpedientsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  doctors?: boolean | ExpedientsCountOutputTypeCountDoctorsArgs
  weekdays?: boolean | ExpedientsCountOutputTypeCountWeekdaysArgs
}

/**
 * ExpedientsCountOutputType without action
 */
export type ExpedientsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExpedientsCountOutputType
   */
  select?: Prisma.ExpedientsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ExpedientsCountOutputType without action
 */
export type ExpedientsCountOutputTypeCountDoctorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.doctorsWhereInput
}

/**
 * ExpedientsCountOutputType without action
 */
export type ExpedientsCountOutputTypeCountWeekdaysArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.weekdaysWhereInput
}


export type expedientsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  duration?: boolean
  description?: boolean
  doctors?: boolean | Prisma.expedients$doctorsArgs<ExtArgs>
  weekdays?: boolean | Prisma.expedients$weekdaysArgs<ExtArgs>
  _count?: boolean | Prisma.ExpedientsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["expedients"]>



export type expedientsSelectScalar = {
  id?: boolean
  duration?: boolean
  description?: boolean
}

export type expedientsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "duration" | "description", ExtArgs["result"]["expedients"]>
export type expedientsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  doctors?: boolean | Prisma.expedients$doctorsArgs<ExtArgs>
  weekdays?: boolean | Prisma.expedients$weekdaysArgs<ExtArgs>
  _count?: boolean | Prisma.ExpedientsCountOutputTypeDefaultArgs<ExtArgs>
}

export type $expedientsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "expedients"
  objects: {
    doctors: Prisma.$doctorsPayload<ExtArgs>[]
    weekdays: Prisma.$weekdaysPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    duration: Date
    description: string | null
  }, ExtArgs["result"]["expedients"]>
  composites: {}
}

export type expedientsGetPayload<S extends boolean | null | undefined | expedientsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$expedientsPayload, S>

export type expedientsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<expedientsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ExpedientsCountAggregateInputType | true
  }

export interface expedientsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['expedients'], meta: { name: 'expedients' } }
  /**
   * Find zero or one Expedients that matches the filter.
   * @param {expedientsFindUniqueArgs} args - Arguments to find a Expedients
   * @example
   * // Get one Expedients
   * const expedients = await prisma.expedients.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends expedientsFindUniqueArgs>(args: Prisma.SelectSubset<T, expedientsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__expedientsClient<runtime.Types.Result.GetResult<Prisma.$expedientsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Expedients that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {expedientsFindUniqueOrThrowArgs} args - Arguments to find a Expedients
   * @example
   * // Get one Expedients
   * const expedients = await prisma.expedients.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends expedientsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, expedientsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__expedientsClient<runtime.Types.Result.GetResult<Prisma.$expedientsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Expedients that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {expedientsFindFirstArgs} args - Arguments to find a Expedients
   * @example
   * // Get one Expedients
   * const expedients = await prisma.expedients.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends expedientsFindFirstArgs>(args?: Prisma.SelectSubset<T, expedientsFindFirstArgs<ExtArgs>>): Prisma.Prisma__expedientsClient<runtime.Types.Result.GetResult<Prisma.$expedientsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Expedients that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {expedientsFindFirstOrThrowArgs} args - Arguments to find a Expedients
   * @example
   * // Get one Expedients
   * const expedients = await prisma.expedients.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends expedientsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, expedientsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__expedientsClient<runtime.Types.Result.GetResult<Prisma.$expedientsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Expedients that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {expedientsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Expedients
   * const expedients = await prisma.expedients.findMany()
   * 
   * // Get first 10 Expedients
   * const expedients = await prisma.expedients.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const expedientsWithIdOnly = await prisma.expedients.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends expedientsFindManyArgs>(args?: Prisma.SelectSubset<T, expedientsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$expedientsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Expedients.
   * @param {expedientsCreateArgs} args - Arguments to create a Expedients.
   * @example
   * // Create one Expedients
   * const Expedients = await prisma.expedients.create({
   *   data: {
   *     // ... data to create a Expedients
   *   }
   * })
   * 
   */
  create<T extends expedientsCreateArgs>(args: Prisma.SelectSubset<T, expedientsCreateArgs<ExtArgs>>): Prisma.Prisma__expedientsClient<runtime.Types.Result.GetResult<Prisma.$expedientsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Expedients.
   * @param {expedientsCreateManyArgs} args - Arguments to create many Expedients.
   * @example
   * // Create many Expedients
   * const expedients = await prisma.expedients.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends expedientsCreateManyArgs>(args?: Prisma.SelectSubset<T, expedientsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Expedients.
   * @param {expedientsDeleteArgs} args - Arguments to delete one Expedients.
   * @example
   * // Delete one Expedients
   * const Expedients = await prisma.expedients.delete({
   *   where: {
   *     // ... filter to delete one Expedients
   *   }
   * })
   * 
   */
  delete<T extends expedientsDeleteArgs>(args: Prisma.SelectSubset<T, expedientsDeleteArgs<ExtArgs>>): Prisma.Prisma__expedientsClient<runtime.Types.Result.GetResult<Prisma.$expedientsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Expedients.
   * @param {expedientsUpdateArgs} args - Arguments to update one Expedients.
   * @example
   * // Update one Expedients
   * const expedients = await prisma.expedients.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends expedientsUpdateArgs>(args: Prisma.SelectSubset<T, expedientsUpdateArgs<ExtArgs>>): Prisma.Prisma__expedientsClient<runtime.Types.Result.GetResult<Prisma.$expedientsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Expedients.
   * @param {expedientsDeleteManyArgs} args - Arguments to filter Expedients to delete.
   * @example
   * // Delete a few Expedients
   * const { count } = await prisma.expedients.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends expedientsDeleteManyArgs>(args?: Prisma.SelectSubset<T, expedientsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Expedients.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {expedientsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Expedients
   * const expedients = await prisma.expedients.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends expedientsUpdateManyArgs>(args: Prisma.SelectSubset<T, expedientsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Expedients.
   * @param {expedientsUpsertArgs} args - Arguments to update or create a Expedients.
   * @example
   * // Update or create a Expedients
   * const expedients = await prisma.expedients.upsert({
   *   create: {
   *     // ... data to create a Expedients
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Expedients we want to update
   *   }
   * })
   */
  upsert<T extends expedientsUpsertArgs>(args: Prisma.SelectSubset<T, expedientsUpsertArgs<ExtArgs>>): Prisma.Prisma__expedientsClient<runtime.Types.Result.GetResult<Prisma.$expedientsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Expedients.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {expedientsCountArgs} args - Arguments to filter Expedients to count.
   * @example
   * // Count the number of Expedients
   * const count = await prisma.expedients.count({
   *   where: {
   *     // ... the filter for the Expedients we want to count
   *   }
   * })
  **/
  count<T extends expedientsCountArgs>(
    args?: Prisma.Subset<T, expedientsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExpedientsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Expedients.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpedientsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ExpedientsAggregateArgs>(args: Prisma.Subset<T, ExpedientsAggregateArgs>): Prisma.PrismaPromise<GetExpedientsAggregateType<T>>

  /**
   * Group by Expedients.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {expedientsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends expedientsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: expedientsGroupByArgs['orderBy'] }
      : { orderBy?: expedientsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, expedientsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetExpedientsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the expedients model
 */
readonly fields: expedientsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for expedients.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__expedientsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  doctors<T extends Prisma.expedients$doctorsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.expedients$doctorsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  weekdays<T extends Prisma.expedients$weekdaysArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.expedients$weekdaysArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$weekdaysPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the expedients model
 */
export interface expedientsFieldRefs {
  readonly id: Prisma.FieldRef<"expedients", 'Int'>
  readonly duration: Prisma.FieldRef<"expedients", 'DateTime'>
  readonly description: Prisma.FieldRef<"expedients", 'String'>
}
    

// Custom InputTypes
/**
 * expedients findUnique
 */
export type expedientsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the expedients
   */
  select?: Prisma.expedientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the expedients
   */
  omit?: Prisma.expedientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.expedientsInclude<ExtArgs> | null
  /**
   * Filter, which expedients to fetch.
   */
  where: Prisma.expedientsWhereUniqueInput
}

/**
 * expedients findUniqueOrThrow
 */
export type expedientsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the expedients
   */
  select?: Prisma.expedientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the expedients
   */
  omit?: Prisma.expedientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.expedientsInclude<ExtArgs> | null
  /**
   * Filter, which expedients to fetch.
   */
  where: Prisma.expedientsWhereUniqueInput
}

/**
 * expedients findFirst
 */
export type expedientsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the expedients
   */
  select?: Prisma.expedientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the expedients
   */
  omit?: Prisma.expedientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.expedientsInclude<ExtArgs> | null
  /**
   * Filter, which expedients to fetch.
   */
  where?: Prisma.expedientsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of expedients to fetch.
   */
  orderBy?: Prisma.expedientsOrderByWithRelationInput | Prisma.expedientsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for expedients.
   */
  cursor?: Prisma.expedientsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` expedients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` expedients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of expedients.
   */
  distinct?: Prisma.ExpedientsScalarFieldEnum | Prisma.ExpedientsScalarFieldEnum[]
}

/**
 * expedients findFirstOrThrow
 */
export type expedientsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the expedients
   */
  select?: Prisma.expedientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the expedients
   */
  omit?: Prisma.expedientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.expedientsInclude<ExtArgs> | null
  /**
   * Filter, which expedients to fetch.
   */
  where?: Prisma.expedientsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of expedients to fetch.
   */
  orderBy?: Prisma.expedientsOrderByWithRelationInput | Prisma.expedientsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for expedients.
   */
  cursor?: Prisma.expedientsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` expedients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` expedients.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of expedients.
   */
  distinct?: Prisma.ExpedientsScalarFieldEnum | Prisma.ExpedientsScalarFieldEnum[]
}

/**
 * expedients findMany
 */
export type expedientsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the expedients
   */
  select?: Prisma.expedientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the expedients
   */
  omit?: Prisma.expedientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.expedientsInclude<ExtArgs> | null
  /**
   * Filter, which expedients to fetch.
   */
  where?: Prisma.expedientsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of expedients to fetch.
   */
  orderBy?: Prisma.expedientsOrderByWithRelationInput | Prisma.expedientsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing expedients.
   */
  cursor?: Prisma.expedientsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` expedients from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` expedients.
   */
  skip?: number
  distinct?: Prisma.ExpedientsScalarFieldEnum | Prisma.ExpedientsScalarFieldEnum[]
}

/**
 * expedients create
 */
export type expedientsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the expedients
   */
  select?: Prisma.expedientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the expedients
   */
  omit?: Prisma.expedientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.expedientsInclude<ExtArgs> | null
  /**
   * The data needed to create a expedients.
   */
  data: Prisma.XOR<Prisma.expedientsCreateInput, Prisma.expedientsUncheckedCreateInput>
}

/**
 * expedients createMany
 */
export type expedientsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many expedients.
   */
  data: Prisma.expedientsCreateManyInput | Prisma.expedientsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * expedients update
 */
export type expedientsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the expedients
   */
  select?: Prisma.expedientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the expedients
   */
  omit?: Prisma.expedientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.expedientsInclude<ExtArgs> | null
  /**
   * The data needed to update a expedients.
   */
  data: Prisma.XOR<Prisma.expedientsUpdateInput, Prisma.expedientsUncheckedUpdateInput>
  /**
   * Choose, which expedients to update.
   */
  where: Prisma.expedientsWhereUniqueInput
}

/**
 * expedients updateMany
 */
export type expedientsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update expedients.
   */
  data: Prisma.XOR<Prisma.expedientsUpdateManyMutationInput, Prisma.expedientsUncheckedUpdateManyInput>
  /**
   * Filter which expedients to update
   */
  where?: Prisma.expedientsWhereInput
  /**
   * Limit how many expedients to update.
   */
  limit?: number
}

/**
 * expedients upsert
 */
export type expedientsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the expedients
   */
  select?: Prisma.expedientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the expedients
   */
  omit?: Prisma.expedientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.expedientsInclude<ExtArgs> | null
  /**
   * The filter to search for the expedients to update in case it exists.
   */
  where: Prisma.expedientsWhereUniqueInput
  /**
   * In case the expedients found by the `where` argument doesn't exist, create a new expedients with this data.
   */
  create: Prisma.XOR<Prisma.expedientsCreateInput, Prisma.expedientsUncheckedCreateInput>
  /**
   * In case the expedients was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.expedientsUpdateInput, Prisma.expedientsUncheckedUpdateInput>
}

/**
 * expedients delete
 */
export type expedientsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the expedients
   */
  select?: Prisma.expedientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the expedients
   */
  omit?: Prisma.expedientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.expedientsInclude<ExtArgs> | null
  /**
   * Filter which expedients to delete.
   */
  where: Prisma.expedientsWhereUniqueInput
}

/**
 * expedients deleteMany
 */
export type expedientsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which expedients to delete
   */
  where?: Prisma.expedientsWhereInput
  /**
   * Limit how many expedients to delete.
   */
  limit?: number
}

/**
 * expedients.doctors
 */
export type expedients$doctorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
  where?: Prisma.doctorsWhereInput
  orderBy?: Prisma.doctorsOrderByWithRelationInput | Prisma.doctorsOrderByWithRelationInput[]
  cursor?: Prisma.doctorsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DoctorsScalarFieldEnum | Prisma.DoctorsScalarFieldEnum[]
}

/**
 * expedients.weekdays
 */
export type expedients$weekdaysArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the weekdays
   */
  select?: Prisma.weekdaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the weekdays
   */
  omit?: Prisma.weekdaysOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.weekdaysInclude<ExtArgs> | null
  where?: Prisma.weekdaysWhereInput
  orderBy?: Prisma.weekdaysOrderByWithRelationInput | Prisma.weekdaysOrderByWithRelationInput[]
  cursor?: Prisma.weekdaysWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WeekdaysScalarFieldEnum | Prisma.WeekdaysScalarFieldEnum[]
}

/**
 * expedients without action
 */
export type expedientsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the expedients
   */
  select?: Prisma.expedientsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the expedients
   */
  omit?: Prisma.expedientsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.expedientsInclude<ExtArgs> | null
}
