
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `fields` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model fields
 * 
 */
export type fieldsModel = runtime.Types.Result.DefaultSelection<Prisma.$fieldsPayload>

export type AggregateFields = {
  _count: FieldsCountAggregateOutputType | null
  _avg: FieldsAvgAggregateOutputType | null
  _sum: FieldsSumAggregateOutputType | null
  _min: FieldsMinAggregateOutputType | null
  _max: FieldsMaxAggregateOutputType | null
}

export type FieldsAvgAggregateOutputType = {
  id: number | null
}

export type FieldsSumAggregateOutputType = {
  id: number | null
}

export type FieldsMinAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
}

export type FieldsMaxAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
}

export type FieldsCountAggregateOutputType = {
  id: number
  name: number
  description: number
  _all: number
}


export type FieldsAvgAggregateInputType = {
  id?: true
}

export type FieldsSumAggregateInputType = {
  id?: true
}

export type FieldsMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
}

export type FieldsMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
}

export type FieldsCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  _all?: true
}

export type FieldsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which fields to aggregate.
   */
  where?: Prisma.fieldsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of fields to fetch.
   */
  orderBy?: Prisma.fieldsOrderByWithRelationInput | Prisma.fieldsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.fieldsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` fields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` fields.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned fields
  **/
  _count?: true | FieldsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FieldsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FieldsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FieldsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FieldsMaxAggregateInputType
}

export type GetFieldsAggregateType<T extends FieldsAggregateArgs> = {
      [P in keyof T & keyof AggregateFields]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFields[P]>
    : Prisma.GetScalarType<T[P], AggregateFields[P]>
}




export type fieldsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.fieldsWhereInput
  orderBy?: Prisma.fieldsOrderByWithAggregationInput | Prisma.fieldsOrderByWithAggregationInput[]
  by: Prisma.FieldsScalarFieldEnum[] | Prisma.FieldsScalarFieldEnum
  having?: Prisma.fieldsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FieldsCountAggregateInputType | true
  _avg?: FieldsAvgAggregateInputType
  _sum?: FieldsSumAggregateInputType
  _min?: FieldsMinAggregateInputType
  _max?: FieldsMaxAggregateInputType
}

export type FieldsGroupByOutputType = {
  id: number
  name: string
  description: string | null
  _count: FieldsCountAggregateOutputType | null
  _avg: FieldsAvgAggregateOutputType | null
  _sum: FieldsSumAggregateOutputType | null
  _min: FieldsMinAggregateOutputType | null
  _max: FieldsMaxAggregateOutputType | null
}

type GetFieldsGroupByPayload<T extends fieldsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FieldsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FieldsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FieldsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FieldsGroupByOutputType[P]>
      }
    >
  >



export type fieldsWhereInput = {
  AND?: Prisma.fieldsWhereInput | Prisma.fieldsWhereInput[]
  OR?: Prisma.fieldsWhereInput[]
  NOT?: Prisma.fieldsWhereInput | Prisma.fieldsWhereInput[]
  id?: Prisma.IntFilter<"fields"> | number
  name?: Prisma.StringFilter<"fields"> | string
  description?: Prisma.StringNullableFilter<"fields"> | string | null
  doctors?: Prisma.DoctorsListRelationFilter
}

export type fieldsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  doctors?: Prisma.doctorsOrderByRelationAggregateInput
  _relevance?: Prisma.fieldsOrderByRelevanceInput
}

export type fieldsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.fieldsWhereInput | Prisma.fieldsWhereInput[]
  OR?: Prisma.fieldsWhereInput[]
  NOT?: Prisma.fieldsWhereInput | Prisma.fieldsWhereInput[]
  name?: Prisma.StringFilter<"fields"> | string
  description?: Prisma.StringNullableFilter<"fields"> | string | null
  doctors?: Prisma.DoctorsListRelationFilter
}, "id">

export type fieldsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.fieldsCountOrderByAggregateInput
  _avg?: Prisma.fieldsAvgOrderByAggregateInput
  _max?: Prisma.fieldsMaxOrderByAggregateInput
  _min?: Prisma.fieldsMinOrderByAggregateInput
  _sum?: Prisma.fieldsSumOrderByAggregateInput
}

export type fieldsScalarWhereWithAggregatesInput = {
  AND?: Prisma.fieldsScalarWhereWithAggregatesInput | Prisma.fieldsScalarWhereWithAggregatesInput[]
  OR?: Prisma.fieldsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.fieldsScalarWhereWithAggregatesInput | Prisma.fieldsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"fields"> | number
  name?: Prisma.StringWithAggregatesFilter<"fields"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"fields"> | string | null
}

export type fieldsCreateInput = {
  id: number
  name: string
  description?: string | null
  doctors?: Prisma.doctorsCreateNestedManyWithoutFieldsInput
}

export type fieldsUncheckedCreateInput = {
  id: number
  name: string
  description?: string | null
  doctors?: Prisma.doctorsUncheckedCreateNestedManyWithoutFieldsInput
}

export type fieldsUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  doctors?: Prisma.doctorsUpdateManyWithoutFieldsNestedInput
}

export type fieldsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  doctors?: Prisma.doctorsUncheckedUpdateManyWithoutFieldsNestedInput
}

export type fieldsCreateManyInput = {
  id: number
  name: string
  description?: string | null
}

export type fieldsUpdateManyMutationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type fieldsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type FieldsScalarRelationFilter = {
  is?: Prisma.fieldsWhereInput
  isNot?: Prisma.fieldsWhereInput
}

export type fieldsOrderByRelevanceInput = {
  fields: Prisma.fieldsOrderByRelevanceFieldEnum | Prisma.fieldsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type fieldsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type fieldsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type fieldsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type fieldsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type fieldsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type fieldsCreateNestedOneWithoutDoctorsInput = {
  create?: Prisma.XOR<Prisma.fieldsCreateWithoutDoctorsInput, Prisma.fieldsUncheckedCreateWithoutDoctorsInput>
  connectOrCreate?: Prisma.fieldsCreateOrConnectWithoutDoctorsInput
  connect?: Prisma.fieldsWhereUniqueInput
}

export type fieldsUpdateOneRequiredWithoutDoctorsNestedInput = {
  create?: Prisma.XOR<Prisma.fieldsCreateWithoutDoctorsInput, Prisma.fieldsUncheckedCreateWithoutDoctorsInput>
  connectOrCreate?: Prisma.fieldsCreateOrConnectWithoutDoctorsInput
  upsert?: Prisma.fieldsUpsertWithoutDoctorsInput
  connect?: Prisma.fieldsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.fieldsUpdateToOneWithWhereWithoutDoctorsInput, Prisma.fieldsUpdateWithoutDoctorsInput>, Prisma.fieldsUncheckedUpdateWithoutDoctorsInput>
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type fieldsCreateWithoutDoctorsInput = {
  id: number
  name: string
  description?: string | null
}

export type fieldsUncheckedCreateWithoutDoctorsInput = {
  id: number
  name: string
  description?: string | null
}

export type fieldsCreateOrConnectWithoutDoctorsInput = {
  where: Prisma.fieldsWhereUniqueInput
  create: Prisma.XOR<Prisma.fieldsCreateWithoutDoctorsInput, Prisma.fieldsUncheckedCreateWithoutDoctorsInput>
}

export type fieldsUpsertWithoutDoctorsInput = {
  update: Prisma.XOR<Prisma.fieldsUpdateWithoutDoctorsInput, Prisma.fieldsUncheckedUpdateWithoutDoctorsInput>
  create: Prisma.XOR<Prisma.fieldsCreateWithoutDoctorsInput, Prisma.fieldsUncheckedCreateWithoutDoctorsInput>
  where?: Prisma.fieldsWhereInput
}

export type fieldsUpdateToOneWithWhereWithoutDoctorsInput = {
  where?: Prisma.fieldsWhereInput
  data: Prisma.XOR<Prisma.fieldsUpdateWithoutDoctorsInput, Prisma.fieldsUncheckedUpdateWithoutDoctorsInput>
}

export type fieldsUpdateWithoutDoctorsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type fieldsUncheckedUpdateWithoutDoctorsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type FieldsCountOutputType
 */

export type FieldsCountOutputType = {
  doctors: number
}

export type FieldsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  doctors?: boolean | FieldsCountOutputTypeCountDoctorsArgs
}

/**
 * FieldsCountOutputType without action
 */
export type FieldsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldsCountOutputType
   */
  select?: Prisma.FieldsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FieldsCountOutputType without action
 */
export type FieldsCountOutputTypeCountDoctorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.doctorsWhereInput
}


export type fieldsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  doctors?: boolean | Prisma.fields$doctorsArgs<ExtArgs>
  _count?: boolean | Prisma.FieldsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fields"]>



export type fieldsSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
}

export type fieldsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description", ExtArgs["result"]["fields"]>
export type fieldsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  doctors?: boolean | Prisma.fields$doctorsArgs<ExtArgs>
  _count?: boolean | Prisma.FieldsCountOutputTypeDefaultArgs<ExtArgs>
}

export type $fieldsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "fields"
  objects: {
    doctors: Prisma.$doctorsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    description: string | null
  }, ExtArgs["result"]["fields"]>
  composites: {}
}

export type fieldsGetPayload<S extends boolean | null | undefined | fieldsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$fieldsPayload, S>

export type fieldsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<fieldsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FieldsCountAggregateInputType | true
  }

export interface fieldsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['fields'], meta: { name: 'fields' } }
  /**
   * Find zero or one Fields that matches the filter.
   * @param {fieldsFindUniqueArgs} args - Arguments to find a Fields
   * @example
   * // Get one Fields
   * const fields = await prisma.fields.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends fieldsFindUniqueArgs>(args: Prisma.SelectSubset<T, fieldsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__fieldsClient<runtime.Types.Result.GetResult<Prisma.$fieldsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Fields that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {fieldsFindUniqueOrThrowArgs} args - Arguments to find a Fields
   * @example
   * // Get one Fields
   * const fields = await prisma.fields.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends fieldsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, fieldsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__fieldsClient<runtime.Types.Result.GetResult<Prisma.$fieldsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Fields that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {fieldsFindFirstArgs} args - Arguments to find a Fields
   * @example
   * // Get one Fields
   * const fields = await prisma.fields.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends fieldsFindFirstArgs>(args?: Prisma.SelectSubset<T, fieldsFindFirstArgs<ExtArgs>>): Prisma.Prisma__fieldsClient<runtime.Types.Result.GetResult<Prisma.$fieldsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Fields that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {fieldsFindFirstOrThrowArgs} args - Arguments to find a Fields
   * @example
   * // Get one Fields
   * const fields = await prisma.fields.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends fieldsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, fieldsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__fieldsClient<runtime.Types.Result.GetResult<Prisma.$fieldsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Fields that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {fieldsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Fields
   * const fields = await prisma.fields.findMany()
   * 
   * // Get first 10 Fields
   * const fields = await prisma.fields.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fieldsWithIdOnly = await prisma.fields.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends fieldsFindManyArgs>(args?: Prisma.SelectSubset<T, fieldsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$fieldsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Fields.
   * @param {fieldsCreateArgs} args - Arguments to create a Fields.
   * @example
   * // Create one Fields
   * const Fields = await prisma.fields.create({
   *   data: {
   *     // ... data to create a Fields
   *   }
   * })
   * 
   */
  create<T extends fieldsCreateArgs>(args: Prisma.SelectSubset<T, fieldsCreateArgs<ExtArgs>>): Prisma.Prisma__fieldsClient<runtime.Types.Result.GetResult<Prisma.$fieldsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Fields.
   * @param {fieldsCreateManyArgs} args - Arguments to create many Fields.
   * @example
   * // Create many Fields
   * const fields = await prisma.fields.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends fieldsCreateManyArgs>(args?: Prisma.SelectSubset<T, fieldsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Fields.
   * @param {fieldsDeleteArgs} args - Arguments to delete one Fields.
   * @example
   * // Delete one Fields
   * const Fields = await prisma.fields.delete({
   *   where: {
   *     // ... filter to delete one Fields
   *   }
   * })
   * 
   */
  delete<T extends fieldsDeleteArgs>(args: Prisma.SelectSubset<T, fieldsDeleteArgs<ExtArgs>>): Prisma.Prisma__fieldsClient<runtime.Types.Result.GetResult<Prisma.$fieldsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Fields.
   * @param {fieldsUpdateArgs} args - Arguments to update one Fields.
   * @example
   * // Update one Fields
   * const fields = await prisma.fields.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends fieldsUpdateArgs>(args: Prisma.SelectSubset<T, fieldsUpdateArgs<ExtArgs>>): Prisma.Prisma__fieldsClient<runtime.Types.Result.GetResult<Prisma.$fieldsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Fields.
   * @param {fieldsDeleteManyArgs} args - Arguments to filter Fields to delete.
   * @example
   * // Delete a few Fields
   * const { count } = await prisma.fields.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends fieldsDeleteManyArgs>(args?: Prisma.SelectSubset<T, fieldsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Fields.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {fieldsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Fields
   * const fields = await prisma.fields.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends fieldsUpdateManyArgs>(args: Prisma.SelectSubset<T, fieldsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Fields.
   * @param {fieldsUpsertArgs} args - Arguments to update or create a Fields.
   * @example
   * // Update or create a Fields
   * const fields = await prisma.fields.upsert({
   *   create: {
   *     // ... data to create a Fields
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Fields we want to update
   *   }
   * })
   */
  upsert<T extends fieldsUpsertArgs>(args: Prisma.SelectSubset<T, fieldsUpsertArgs<ExtArgs>>): Prisma.Prisma__fieldsClient<runtime.Types.Result.GetResult<Prisma.$fieldsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Fields.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {fieldsCountArgs} args - Arguments to filter Fields to count.
   * @example
   * // Count the number of Fields
   * const count = await prisma.fields.count({
   *   where: {
   *     // ... the filter for the Fields we want to count
   *   }
   * })
  **/
  count<T extends fieldsCountArgs>(
    args?: Prisma.Subset<T, fieldsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FieldsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Fields.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FieldsAggregateArgs>(args: Prisma.Subset<T, FieldsAggregateArgs>): Prisma.PrismaPromise<GetFieldsAggregateType<T>>

  /**
   * Group by Fields.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {fieldsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends fieldsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: fieldsGroupByArgs['orderBy'] }
      : { orderBy?: fieldsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, fieldsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFieldsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the fields model
 */
readonly fields: fieldsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for fields.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__fieldsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  doctors<T extends Prisma.fields$doctorsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.fields$doctorsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the fields model
 */
export interface fieldsFieldRefs {
  readonly id: Prisma.FieldRef<"fields", 'Int'>
  readonly name: Prisma.FieldRef<"fields", 'String'>
  readonly description: Prisma.FieldRef<"fields", 'String'>
}
    

// Custom InputTypes
/**
 * fields findUnique
 */
export type fieldsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the fields
   */
  select?: Prisma.fieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the fields
   */
  omit?: Prisma.fieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.fieldsInclude<ExtArgs> | null
  /**
   * Filter, which fields to fetch.
   */
  where: Prisma.fieldsWhereUniqueInput
}

/**
 * fields findUniqueOrThrow
 */
export type fieldsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the fields
   */
  select?: Prisma.fieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the fields
   */
  omit?: Prisma.fieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.fieldsInclude<ExtArgs> | null
  /**
   * Filter, which fields to fetch.
   */
  where: Prisma.fieldsWhereUniqueInput
}

/**
 * fields findFirst
 */
export type fieldsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the fields
   */
  select?: Prisma.fieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the fields
   */
  omit?: Prisma.fieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.fieldsInclude<ExtArgs> | null
  /**
   * Filter, which fields to fetch.
   */
  where?: Prisma.fieldsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of fields to fetch.
   */
  orderBy?: Prisma.fieldsOrderByWithRelationInput | Prisma.fieldsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for fields.
   */
  cursor?: Prisma.fieldsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` fields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` fields.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of fields.
   */
  distinct?: Prisma.FieldsScalarFieldEnum | Prisma.FieldsScalarFieldEnum[]
}

/**
 * fields findFirstOrThrow
 */
export type fieldsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the fields
   */
  select?: Prisma.fieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the fields
   */
  omit?: Prisma.fieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.fieldsInclude<ExtArgs> | null
  /**
   * Filter, which fields to fetch.
   */
  where?: Prisma.fieldsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of fields to fetch.
   */
  orderBy?: Prisma.fieldsOrderByWithRelationInput | Prisma.fieldsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for fields.
   */
  cursor?: Prisma.fieldsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` fields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` fields.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of fields.
   */
  distinct?: Prisma.FieldsScalarFieldEnum | Prisma.FieldsScalarFieldEnum[]
}

/**
 * fields findMany
 */
export type fieldsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the fields
   */
  select?: Prisma.fieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the fields
   */
  omit?: Prisma.fieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.fieldsInclude<ExtArgs> | null
  /**
   * Filter, which fields to fetch.
   */
  where?: Prisma.fieldsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of fields to fetch.
   */
  orderBy?: Prisma.fieldsOrderByWithRelationInput | Prisma.fieldsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing fields.
   */
  cursor?: Prisma.fieldsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` fields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` fields.
   */
  skip?: number
  distinct?: Prisma.FieldsScalarFieldEnum | Prisma.FieldsScalarFieldEnum[]
}

/**
 * fields create
 */
export type fieldsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the fields
   */
  select?: Prisma.fieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the fields
   */
  omit?: Prisma.fieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.fieldsInclude<ExtArgs> | null
  /**
   * The data needed to create a fields.
   */
  data: Prisma.XOR<Prisma.fieldsCreateInput, Prisma.fieldsUncheckedCreateInput>
}

/**
 * fields createMany
 */
export type fieldsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many fields.
   */
  data: Prisma.fieldsCreateManyInput | Prisma.fieldsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * fields update
 */
export type fieldsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the fields
   */
  select?: Prisma.fieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the fields
   */
  omit?: Prisma.fieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.fieldsInclude<ExtArgs> | null
  /**
   * The data needed to update a fields.
   */
  data: Prisma.XOR<Prisma.fieldsUpdateInput, Prisma.fieldsUncheckedUpdateInput>
  /**
   * Choose, which fields to update.
   */
  where: Prisma.fieldsWhereUniqueInput
}

/**
 * fields updateMany
 */
export type fieldsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update fields.
   */
  data: Prisma.XOR<Prisma.fieldsUpdateManyMutationInput, Prisma.fieldsUncheckedUpdateManyInput>
  /**
   * Filter which fields to update
   */
  where?: Prisma.fieldsWhereInput
  /**
   * Limit how many fields to update.
   */
  limit?: number
}

/**
 * fields upsert
 */
export type fieldsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the fields
   */
  select?: Prisma.fieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the fields
   */
  omit?: Prisma.fieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.fieldsInclude<ExtArgs> | null
  /**
   * The filter to search for the fields to update in case it exists.
   */
  where: Prisma.fieldsWhereUniqueInput
  /**
   * In case the fields found by the `where` argument doesn't exist, create a new fields with this data.
   */
  create: Prisma.XOR<Prisma.fieldsCreateInput, Prisma.fieldsUncheckedCreateInput>
  /**
   * In case the fields was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.fieldsUpdateInput, Prisma.fieldsUncheckedUpdateInput>
}

/**
 * fields delete
 */
export type fieldsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the fields
   */
  select?: Prisma.fieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the fields
   */
  omit?: Prisma.fieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.fieldsInclude<ExtArgs> | null
  /**
   * Filter which fields to delete.
   */
  where: Prisma.fieldsWhereUniqueInput
}

/**
 * fields deleteMany
 */
export type fieldsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which fields to delete
   */
  where?: Prisma.fieldsWhereInput
  /**
   * Limit how many fields to delete.
   */
  limit?: number
}

/**
 * fields.doctors
 */
export type fields$doctorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
  where?: Prisma.doctorsWhereInput
  orderBy?: Prisma.doctorsOrderByWithRelationInput | Prisma.doctorsOrderByWithRelationInput[]
  cursor?: Prisma.doctorsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DoctorsScalarFieldEnum | Prisma.DoctorsScalarFieldEnum[]
}

/**
 * fields without action
 */
export type fieldsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the fields
   */
  select?: Prisma.fieldsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the fields
   */
  omit?: Prisma.fieldsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.fieldsInclude<ExtArgs> | null
}
