
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `hospitals` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model hospitals
 * 
 */
export type hospitalsModel = runtime.Types.Result.DefaultSelection<Prisma.$hospitalsPayload>

export type AggregateHospitals = {
  _count: HospitalsCountAggregateOutputType | null
  _avg: HospitalsAvgAggregateOutputType | null
  _sum: HospitalsSumAggregateOutputType | null
  _min: HospitalsMinAggregateOutputType | null
  _max: HospitalsMaxAggregateOutputType | null
}

export type HospitalsAvgAggregateOutputType = {
  id: number | null
  number: number | null
}

export type HospitalsSumAggregateOutputType = {
  id: number | null
  number: number | null
}

export type HospitalsMinAggregateOutputType = {
  id: number | null
  name: string | null
  street: string | null
  number: number | null
  district: string | null
  cep: string | null
  city: string | null
  uf: string | null
}

export type HospitalsMaxAggregateOutputType = {
  id: number | null
  name: string | null
  street: string | null
  number: number | null
  district: string | null
  cep: string | null
  city: string | null
  uf: string | null
}

export type HospitalsCountAggregateOutputType = {
  id: number
  name: number
  street: number
  number: number
  district: number
  cep: number
  city: number
  uf: number
  _all: number
}


export type HospitalsAvgAggregateInputType = {
  id?: true
  number?: true
}

export type HospitalsSumAggregateInputType = {
  id?: true
  number?: true
}

export type HospitalsMinAggregateInputType = {
  id?: true
  name?: true
  street?: true
  number?: true
  district?: true
  cep?: true
  city?: true
  uf?: true
}

export type HospitalsMaxAggregateInputType = {
  id?: true
  name?: true
  street?: true
  number?: true
  district?: true
  cep?: true
  city?: true
  uf?: true
}

export type HospitalsCountAggregateInputType = {
  id?: true
  name?: true
  street?: true
  number?: true
  district?: true
  cep?: true
  city?: true
  uf?: true
  _all?: true
}

export type HospitalsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which hospitals to aggregate.
   */
  where?: Prisma.hospitalsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of hospitals to fetch.
   */
  orderBy?: Prisma.hospitalsOrderByWithRelationInput | Prisma.hospitalsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.hospitalsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` hospitals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` hospitals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned hospitals
  **/
  _count?: true | HospitalsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HospitalsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HospitalsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HospitalsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HospitalsMaxAggregateInputType
}

export type GetHospitalsAggregateType<T extends HospitalsAggregateArgs> = {
      [P in keyof T & keyof AggregateHospitals]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHospitals[P]>
    : Prisma.GetScalarType<T[P], AggregateHospitals[P]>
}




export type hospitalsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.hospitalsWhereInput
  orderBy?: Prisma.hospitalsOrderByWithAggregationInput | Prisma.hospitalsOrderByWithAggregationInput[]
  by: Prisma.HospitalsScalarFieldEnum[] | Prisma.HospitalsScalarFieldEnum
  having?: Prisma.hospitalsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HospitalsCountAggregateInputType | true
  _avg?: HospitalsAvgAggregateInputType
  _sum?: HospitalsSumAggregateInputType
  _min?: HospitalsMinAggregateInputType
  _max?: HospitalsMaxAggregateInputType
}

export type HospitalsGroupByOutputType = {
  id: number
  name: string
  street: string
  number: number
  district: string
  cep: string
  city: string
  uf: string
  _count: HospitalsCountAggregateOutputType | null
  _avg: HospitalsAvgAggregateOutputType | null
  _sum: HospitalsSumAggregateOutputType | null
  _min: HospitalsMinAggregateOutputType | null
  _max: HospitalsMaxAggregateOutputType | null
}

type GetHospitalsGroupByPayload<T extends hospitalsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HospitalsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HospitalsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HospitalsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HospitalsGroupByOutputType[P]>
      }
    >
  >



export type hospitalsWhereInput = {
  AND?: Prisma.hospitalsWhereInput | Prisma.hospitalsWhereInput[]
  OR?: Prisma.hospitalsWhereInput[]
  NOT?: Prisma.hospitalsWhereInput | Prisma.hospitalsWhereInput[]
  id?: Prisma.IntFilter<"hospitals"> | number
  name?: Prisma.StringFilter<"hospitals"> | string
  street?: Prisma.StringFilter<"hospitals"> | string
  number?: Prisma.IntFilter<"hospitals"> | number
  district?: Prisma.StringFilter<"hospitals"> | string
  cep?: Prisma.StringFilter<"hospitals"> | string
  city?: Prisma.StringFilter<"hospitals"> | string
  uf?: Prisma.StringFilter<"hospitals"> | string
  doctors?: Prisma.DoctorsListRelationFilter
}

export type hospitalsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  street?: Prisma.SortOrder
  number?: Prisma.SortOrder
  district?: Prisma.SortOrder
  cep?: Prisma.SortOrder
  city?: Prisma.SortOrder
  uf?: Prisma.SortOrder
  doctors?: Prisma.doctorsOrderByRelationAggregateInput
  _relevance?: Prisma.hospitalsOrderByRelevanceInput
}

export type hospitalsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.hospitalsWhereInput | Prisma.hospitalsWhereInput[]
  OR?: Prisma.hospitalsWhereInput[]
  NOT?: Prisma.hospitalsWhereInput | Prisma.hospitalsWhereInput[]
  name?: Prisma.StringFilter<"hospitals"> | string
  street?: Prisma.StringFilter<"hospitals"> | string
  number?: Prisma.IntFilter<"hospitals"> | number
  district?: Prisma.StringFilter<"hospitals"> | string
  cep?: Prisma.StringFilter<"hospitals"> | string
  city?: Prisma.StringFilter<"hospitals"> | string
  uf?: Prisma.StringFilter<"hospitals"> | string
  doctors?: Prisma.DoctorsListRelationFilter
}, "id">

export type hospitalsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  street?: Prisma.SortOrder
  number?: Prisma.SortOrder
  district?: Prisma.SortOrder
  cep?: Prisma.SortOrder
  city?: Prisma.SortOrder
  uf?: Prisma.SortOrder
  _count?: Prisma.hospitalsCountOrderByAggregateInput
  _avg?: Prisma.hospitalsAvgOrderByAggregateInput
  _max?: Prisma.hospitalsMaxOrderByAggregateInput
  _min?: Prisma.hospitalsMinOrderByAggregateInput
  _sum?: Prisma.hospitalsSumOrderByAggregateInput
}

export type hospitalsScalarWhereWithAggregatesInput = {
  AND?: Prisma.hospitalsScalarWhereWithAggregatesInput | Prisma.hospitalsScalarWhereWithAggregatesInput[]
  OR?: Prisma.hospitalsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.hospitalsScalarWhereWithAggregatesInput | Prisma.hospitalsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"hospitals"> | number
  name?: Prisma.StringWithAggregatesFilter<"hospitals"> | string
  street?: Prisma.StringWithAggregatesFilter<"hospitals"> | string
  number?: Prisma.IntWithAggregatesFilter<"hospitals"> | number
  district?: Prisma.StringWithAggregatesFilter<"hospitals"> | string
  cep?: Prisma.StringWithAggregatesFilter<"hospitals"> | string
  city?: Prisma.StringWithAggregatesFilter<"hospitals"> | string
  uf?: Prisma.StringWithAggregatesFilter<"hospitals"> | string
}

export type hospitalsCreateInput = {
  name: string
  street: string
  number: number
  district: string
  cep: string
  city: string
  uf: string
  doctors?: Prisma.doctorsCreateNestedManyWithoutHospitalsInput
}

export type hospitalsUncheckedCreateInput = {
  id?: number
  name: string
  street: string
  number: number
  district: string
  cep: string
  city: string
  uf: string
  doctors?: Prisma.doctorsUncheckedCreateNestedManyWithoutHospitalsInput
}

export type hospitalsUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  district?: Prisma.StringFieldUpdateOperationsInput | string
  cep?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  uf?: Prisma.StringFieldUpdateOperationsInput | string
  doctors?: Prisma.doctorsUpdateManyWithoutHospitalsNestedInput
}

export type hospitalsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  district?: Prisma.StringFieldUpdateOperationsInput | string
  cep?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  uf?: Prisma.StringFieldUpdateOperationsInput | string
  doctors?: Prisma.doctorsUncheckedUpdateManyWithoutHospitalsNestedInput
}

export type hospitalsCreateManyInput = {
  id?: number
  name: string
  street: string
  number: number
  district: string
  cep: string
  city: string
  uf: string
}

export type hospitalsUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  district?: Prisma.StringFieldUpdateOperationsInput | string
  cep?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  uf?: Prisma.StringFieldUpdateOperationsInput | string
}

export type hospitalsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  district?: Prisma.StringFieldUpdateOperationsInput | string
  cep?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  uf?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HospitalsScalarRelationFilter = {
  is?: Prisma.hospitalsWhereInput
  isNot?: Prisma.hospitalsWhereInput
}

export type hospitalsOrderByRelevanceInput = {
  fields: Prisma.hospitalsOrderByRelevanceFieldEnum | Prisma.hospitalsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type hospitalsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  street?: Prisma.SortOrder
  number?: Prisma.SortOrder
  district?: Prisma.SortOrder
  cep?: Prisma.SortOrder
  city?: Prisma.SortOrder
  uf?: Prisma.SortOrder
}

export type hospitalsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  number?: Prisma.SortOrder
}

export type hospitalsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  street?: Prisma.SortOrder
  number?: Prisma.SortOrder
  district?: Prisma.SortOrder
  cep?: Prisma.SortOrder
  city?: Prisma.SortOrder
  uf?: Prisma.SortOrder
}

export type hospitalsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  street?: Prisma.SortOrder
  number?: Prisma.SortOrder
  district?: Prisma.SortOrder
  cep?: Prisma.SortOrder
  city?: Prisma.SortOrder
  uf?: Prisma.SortOrder
}

export type hospitalsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  number?: Prisma.SortOrder
}

export type hospitalsCreateNestedOneWithoutDoctorsInput = {
  create?: Prisma.XOR<Prisma.hospitalsCreateWithoutDoctorsInput, Prisma.hospitalsUncheckedCreateWithoutDoctorsInput>
  connectOrCreate?: Prisma.hospitalsCreateOrConnectWithoutDoctorsInput
  connect?: Prisma.hospitalsWhereUniqueInput
}

export type hospitalsUpdateOneRequiredWithoutDoctorsNestedInput = {
  create?: Prisma.XOR<Prisma.hospitalsCreateWithoutDoctorsInput, Prisma.hospitalsUncheckedCreateWithoutDoctorsInput>
  connectOrCreate?: Prisma.hospitalsCreateOrConnectWithoutDoctorsInput
  upsert?: Prisma.hospitalsUpsertWithoutDoctorsInput
  connect?: Prisma.hospitalsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.hospitalsUpdateToOneWithWhereWithoutDoctorsInput, Prisma.hospitalsUpdateWithoutDoctorsInput>, Prisma.hospitalsUncheckedUpdateWithoutDoctorsInput>
}

export type hospitalsCreateWithoutDoctorsInput = {
  name: string
  street: string
  number: number
  district: string
  cep: string
  city: string
  uf: string
}

export type hospitalsUncheckedCreateWithoutDoctorsInput = {
  id?: number
  name: string
  street: string
  number: number
  district: string
  cep: string
  city: string
  uf: string
}

export type hospitalsCreateOrConnectWithoutDoctorsInput = {
  where: Prisma.hospitalsWhereUniqueInput
  create: Prisma.XOR<Prisma.hospitalsCreateWithoutDoctorsInput, Prisma.hospitalsUncheckedCreateWithoutDoctorsInput>
}

export type hospitalsUpsertWithoutDoctorsInput = {
  update: Prisma.XOR<Prisma.hospitalsUpdateWithoutDoctorsInput, Prisma.hospitalsUncheckedUpdateWithoutDoctorsInput>
  create: Prisma.XOR<Prisma.hospitalsCreateWithoutDoctorsInput, Prisma.hospitalsUncheckedCreateWithoutDoctorsInput>
  where?: Prisma.hospitalsWhereInput
}

export type hospitalsUpdateToOneWithWhereWithoutDoctorsInput = {
  where?: Prisma.hospitalsWhereInput
  data: Prisma.XOR<Prisma.hospitalsUpdateWithoutDoctorsInput, Prisma.hospitalsUncheckedUpdateWithoutDoctorsInput>
}

export type hospitalsUpdateWithoutDoctorsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  district?: Prisma.StringFieldUpdateOperationsInput | string
  cep?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  uf?: Prisma.StringFieldUpdateOperationsInput | string
}

export type hospitalsUncheckedUpdateWithoutDoctorsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  street?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.IntFieldUpdateOperationsInput | number
  district?: Prisma.StringFieldUpdateOperationsInput | string
  cep?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  uf?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type HospitalsCountOutputType
 */

export type HospitalsCountOutputType = {
  doctors: number
}

export type HospitalsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  doctors?: boolean | HospitalsCountOutputTypeCountDoctorsArgs
}

/**
 * HospitalsCountOutputType without action
 */
export type HospitalsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HospitalsCountOutputType
   */
  select?: Prisma.HospitalsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * HospitalsCountOutputType without action
 */
export type HospitalsCountOutputTypeCountDoctorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.doctorsWhereInput
}


export type hospitalsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  street?: boolean
  number?: boolean
  district?: boolean
  cep?: boolean
  city?: boolean
  uf?: boolean
  doctors?: boolean | Prisma.hospitals$doctorsArgs<ExtArgs>
  _count?: boolean | Prisma.HospitalsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["hospitals"]>



export type hospitalsSelectScalar = {
  id?: boolean
  name?: boolean
  street?: boolean
  number?: boolean
  district?: boolean
  cep?: boolean
  city?: boolean
  uf?: boolean
}

export type hospitalsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "street" | "number" | "district" | "cep" | "city" | "uf", ExtArgs["result"]["hospitals"]>
export type hospitalsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  doctors?: boolean | Prisma.hospitals$doctorsArgs<ExtArgs>
  _count?: boolean | Prisma.HospitalsCountOutputTypeDefaultArgs<ExtArgs>
}

export type $hospitalsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "hospitals"
  objects: {
    doctors: Prisma.$doctorsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    street: string
    number: number
    district: string
    cep: string
    city: string
    uf: string
  }, ExtArgs["result"]["hospitals"]>
  composites: {}
}

export type hospitalsGetPayload<S extends boolean | null | undefined | hospitalsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$hospitalsPayload, S>

export type hospitalsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<hospitalsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HospitalsCountAggregateInputType | true
  }

export interface hospitalsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['hospitals'], meta: { name: 'hospitals' } }
  /**
   * Find zero or one Hospitals that matches the filter.
   * @param {hospitalsFindUniqueArgs} args - Arguments to find a Hospitals
   * @example
   * // Get one Hospitals
   * const hospitals = await prisma.hospitals.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends hospitalsFindUniqueArgs>(args: Prisma.SelectSubset<T, hospitalsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__hospitalsClient<runtime.Types.Result.GetResult<Prisma.$hospitalsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Hospitals that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {hospitalsFindUniqueOrThrowArgs} args - Arguments to find a Hospitals
   * @example
   * // Get one Hospitals
   * const hospitals = await prisma.hospitals.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends hospitalsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, hospitalsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__hospitalsClient<runtime.Types.Result.GetResult<Prisma.$hospitalsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hospitals that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {hospitalsFindFirstArgs} args - Arguments to find a Hospitals
   * @example
   * // Get one Hospitals
   * const hospitals = await prisma.hospitals.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends hospitalsFindFirstArgs>(args?: Prisma.SelectSubset<T, hospitalsFindFirstArgs<ExtArgs>>): Prisma.Prisma__hospitalsClient<runtime.Types.Result.GetResult<Prisma.$hospitalsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hospitals that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {hospitalsFindFirstOrThrowArgs} args - Arguments to find a Hospitals
   * @example
   * // Get one Hospitals
   * const hospitals = await prisma.hospitals.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends hospitalsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, hospitalsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__hospitalsClient<runtime.Types.Result.GetResult<Prisma.$hospitalsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Hospitals that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {hospitalsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Hospitals
   * const hospitals = await prisma.hospitals.findMany()
   * 
   * // Get first 10 Hospitals
   * const hospitals = await prisma.hospitals.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const hospitalsWithIdOnly = await prisma.hospitals.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends hospitalsFindManyArgs>(args?: Prisma.SelectSubset<T, hospitalsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$hospitalsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Hospitals.
   * @param {hospitalsCreateArgs} args - Arguments to create a Hospitals.
   * @example
   * // Create one Hospitals
   * const Hospitals = await prisma.hospitals.create({
   *   data: {
   *     // ... data to create a Hospitals
   *   }
   * })
   * 
   */
  create<T extends hospitalsCreateArgs>(args: Prisma.SelectSubset<T, hospitalsCreateArgs<ExtArgs>>): Prisma.Prisma__hospitalsClient<runtime.Types.Result.GetResult<Prisma.$hospitalsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Hospitals.
   * @param {hospitalsCreateManyArgs} args - Arguments to create many Hospitals.
   * @example
   * // Create many Hospitals
   * const hospitals = await prisma.hospitals.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends hospitalsCreateManyArgs>(args?: Prisma.SelectSubset<T, hospitalsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Hospitals.
   * @param {hospitalsDeleteArgs} args - Arguments to delete one Hospitals.
   * @example
   * // Delete one Hospitals
   * const Hospitals = await prisma.hospitals.delete({
   *   where: {
   *     // ... filter to delete one Hospitals
   *   }
   * })
   * 
   */
  delete<T extends hospitalsDeleteArgs>(args: Prisma.SelectSubset<T, hospitalsDeleteArgs<ExtArgs>>): Prisma.Prisma__hospitalsClient<runtime.Types.Result.GetResult<Prisma.$hospitalsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Hospitals.
   * @param {hospitalsUpdateArgs} args - Arguments to update one Hospitals.
   * @example
   * // Update one Hospitals
   * const hospitals = await prisma.hospitals.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends hospitalsUpdateArgs>(args: Prisma.SelectSubset<T, hospitalsUpdateArgs<ExtArgs>>): Prisma.Prisma__hospitalsClient<runtime.Types.Result.GetResult<Prisma.$hospitalsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Hospitals.
   * @param {hospitalsDeleteManyArgs} args - Arguments to filter Hospitals to delete.
   * @example
   * // Delete a few Hospitals
   * const { count } = await prisma.hospitals.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends hospitalsDeleteManyArgs>(args?: Prisma.SelectSubset<T, hospitalsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Hospitals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {hospitalsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Hospitals
   * const hospitals = await prisma.hospitals.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends hospitalsUpdateManyArgs>(args: Prisma.SelectSubset<T, hospitalsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Hospitals.
   * @param {hospitalsUpsertArgs} args - Arguments to update or create a Hospitals.
   * @example
   * // Update or create a Hospitals
   * const hospitals = await prisma.hospitals.upsert({
   *   create: {
   *     // ... data to create a Hospitals
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Hospitals we want to update
   *   }
   * })
   */
  upsert<T extends hospitalsUpsertArgs>(args: Prisma.SelectSubset<T, hospitalsUpsertArgs<ExtArgs>>): Prisma.Prisma__hospitalsClient<runtime.Types.Result.GetResult<Prisma.$hospitalsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Hospitals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {hospitalsCountArgs} args - Arguments to filter Hospitals to count.
   * @example
   * // Count the number of Hospitals
   * const count = await prisma.hospitals.count({
   *   where: {
   *     // ... the filter for the Hospitals we want to count
   *   }
   * })
  **/
  count<T extends hospitalsCountArgs>(
    args?: Prisma.Subset<T, hospitalsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HospitalsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Hospitals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HospitalsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HospitalsAggregateArgs>(args: Prisma.Subset<T, HospitalsAggregateArgs>): Prisma.PrismaPromise<GetHospitalsAggregateType<T>>

  /**
   * Group by Hospitals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {hospitalsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends hospitalsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: hospitalsGroupByArgs['orderBy'] }
      : { orderBy?: hospitalsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, hospitalsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHospitalsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the hospitals model
 */
readonly fields: hospitalsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for hospitals.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__hospitalsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  doctors<T extends Prisma.hospitals$doctorsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.hospitals$doctorsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the hospitals model
 */
export interface hospitalsFieldRefs {
  readonly id: Prisma.FieldRef<"hospitals", 'Int'>
  readonly name: Prisma.FieldRef<"hospitals", 'String'>
  readonly street: Prisma.FieldRef<"hospitals", 'String'>
  readonly number: Prisma.FieldRef<"hospitals", 'Int'>
  readonly district: Prisma.FieldRef<"hospitals", 'String'>
  readonly cep: Prisma.FieldRef<"hospitals", 'String'>
  readonly city: Prisma.FieldRef<"hospitals", 'String'>
  readonly uf: Prisma.FieldRef<"hospitals", 'String'>
}
    

// Custom InputTypes
/**
 * hospitals findUnique
 */
export type hospitalsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hospitals
   */
  select?: Prisma.hospitalsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hospitals
   */
  omit?: Prisma.hospitalsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hospitalsInclude<ExtArgs> | null
  /**
   * Filter, which hospitals to fetch.
   */
  where: Prisma.hospitalsWhereUniqueInput
}

/**
 * hospitals findUniqueOrThrow
 */
export type hospitalsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hospitals
   */
  select?: Prisma.hospitalsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hospitals
   */
  omit?: Prisma.hospitalsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hospitalsInclude<ExtArgs> | null
  /**
   * Filter, which hospitals to fetch.
   */
  where: Prisma.hospitalsWhereUniqueInput
}

/**
 * hospitals findFirst
 */
export type hospitalsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hospitals
   */
  select?: Prisma.hospitalsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hospitals
   */
  omit?: Prisma.hospitalsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hospitalsInclude<ExtArgs> | null
  /**
   * Filter, which hospitals to fetch.
   */
  where?: Prisma.hospitalsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of hospitals to fetch.
   */
  orderBy?: Prisma.hospitalsOrderByWithRelationInput | Prisma.hospitalsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for hospitals.
   */
  cursor?: Prisma.hospitalsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` hospitals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` hospitals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of hospitals.
   */
  distinct?: Prisma.HospitalsScalarFieldEnum | Prisma.HospitalsScalarFieldEnum[]
}

/**
 * hospitals findFirstOrThrow
 */
export type hospitalsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hospitals
   */
  select?: Prisma.hospitalsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hospitals
   */
  omit?: Prisma.hospitalsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hospitalsInclude<ExtArgs> | null
  /**
   * Filter, which hospitals to fetch.
   */
  where?: Prisma.hospitalsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of hospitals to fetch.
   */
  orderBy?: Prisma.hospitalsOrderByWithRelationInput | Prisma.hospitalsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for hospitals.
   */
  cursor?: Prisma.hospitalsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` hospitals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` hospitals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of hospitals.
   */
  distinct?: Prisma.HospitalsScalarFieldEnum | Prisma.HospitalsScalarFieldEnum[]
}

/**
 * hospitals findMany
 */
export type hospitalsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hospitals
   */
  select?: Prisma.hospitalsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hospitals
   */
  omit?: Prisma.hospitalsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hospitalsInclude<ExtArgs> | null
  /**
   * Filter, which hospitals to fetch.
   */
  where?: Prisma.hospitalsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of hospitals to fetch.
   */
  orderBy?: Prisma.hospitalsOrderByWithRelationInput | Prisma.hospitalsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing hospitals.
   */
  cursor?: Prisma.hospitalsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` hospitals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` hospitals.
   */
  skip?: number
  distinct?: Prisma.HospitalsScalarFieldEnum | Prisma.HospitalsScalarFieldEnum[]
}

/**
 * hospitals create
 */
export type hospitalsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hospitals
   */
  select?: Prisma.hospitalsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hospitals
   */
  omit?: Prisma.hospitalsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hospitalsInclude<ExtArgs> | null
  /**
   * The data needed to create a hospitals.
   */
  data: Prisma.XOR<Prisma.hospitalsCreateInput, Prisma.hospitalsUncheckedCreateInput>
}

/**
 * hospitals createMany
 */
export type hospitalsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many hospitals.
   */
  data: Prisma.hospitalsCreateManyInput | Prisma.hospitalsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * hospitals update
 */
export type hospitalsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hospitals
   */
  select?: Prisma.hospitalsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hospitals
   */
  omit?: Prisma.hospitalsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hospitalsInclude<ExtArgs> | null
  /**
   * The data needed to update a hospitals.
   */
  data: Prisma.XOR<Prisma.hospitalsUpdateInput, Prisma.hospitalsUncheckedUpdateInput>
  /**
   * Choose, which hospitals to update.
   */
  where: Prisma.hospitalsWhereUniqueInput
}

/**
 * hospitals updateMany
 */
export type hospitalsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update hospitals.
   */
  data: Prisma.XOR<Prisma.hospitalsUpdateManyMutationInput, Prisma.hospitalsUncheckedUpdateManyInput>
  /**
   * Filter which hospitals to update
   */
  where?: Prisma.hospitalsWhereInput
  /**
   * Limit how many hospitals to update.
   */
  limit?: number
}

/**
 * hospitals upsert
 */
export type hospitalsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hospitals
   */
  select?: Prisma.hospitalsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hospitals
   */
  omit?: Prisma.hospitalsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hospitalsInclude<ExtArgs> | null
  /**
   * The filter to search for the hospitals to update in case it exists.
   */
  where: Prisma.hospitalsWhereUniqueInput
  /**
   * In case the hospitals found by the `where` argument doesn't exist, create a new hospitals with this data.
   */
  create: Prisma.XOR<Prisma.hospitalsCreateInput, Prisma.hospitalsUncheckedCreateInput>
  /**
   * In case the hospitals was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.hospitalsUpdateInput, Prisma.hospitalsUncheckedUpdateInput>
}

/**
 * hospitals delete
 */
export type hospitalsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hospitals
   */
  select?: Prisma.hospitalsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hospitals
   */
  omit?: Prisma.hospitalsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hospitalsInclude<ExtArgs> | null
  /**
   * Filter which hospitals to delete.
   */
  where: Prisma.hospitalsWhereUniqueInput
}

/**
 * hospitals deleteMany
 */
export type hospitalsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which hospitals to delete
   */
  where?: Prisma.hospitalsWhereInput
  /**
   * Limit how many hospitals to delete.
   */
  limit?: number
}

/**
 * hospitals.doctors
 */
export type hospitals$doctorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
  where?: Prisma.doctorsWhereInput
  orderBy?: Prisma.doctorsOrderByWithRelationInput | Prisma.doctorsOrderByWithRelationInput[]
  cursor?: Prisma.doctorsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DoctorsScalarFieldEnum | Prisma.DoctorsScalarFieldEnum[]
}

/**
 * hospitals without action
 */
export type hospitalsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hospitals
   */
  select?: Prisma.hospitalsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hospitals
   */
  omit?: Prisma.hospitalsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hospitalsInclude<ExtArgs> | null
}
