
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `registers` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model registers
 * 
 */
export type registersModel = runtime.Types.Result.DefaultSelection<Prisma.$registersPayload>

export type AggregateRegisters = {
  _count: RegistersCountAggregateOutputType | null
  _avg: RegistersAvgAggregateOutputType | null
  _sum: RegistersSumAggregateOutputType | null
  _min: RegistersMinAggregateOutputType | null
  _max: RegistersMaxAggregateOutputType | null
}

export type RegistersAvgAggregateOutputType = {
  type: number | null
}

export type RegistersSumAggregateOutputType = {
  type: number | null
}

export type RegistersMinAggregateOutputType = {
  name: string | null
  cpf: string | null
  gender: string | null
  birth: Date | null
  email: string | null
  password: string | null
  type: number | null
}

export type RegistersMaxAggregateOutputType = {
  name: string | null
  cpf: string | null
  gender: string | null
  birth: Date | null
  email: string | null
  password: string | null
  type: number | null
}

export type RegistersCountAggregateOutputType = {
  name: number
  cpf: number
  gender: number
  birth: number
  email: number
  password: number
  type: number
  _all: number
}


export type RegistersAvgAggregateInputType = {
  type?: true
}

export type RegistersSumAggregateInputType = {
  type?: true
}

export type RegistersMinAggregateInputType = {
  name?: true
  cpf?: true
  gender?: true
  birth?: true
  email?: true
  password?: true
  type?: true
}

export type RegistersMaxAggregateInputType = {
  name?: true
  cpf?: true
  gender?: true
  birth?: true
  email?: true
  password?: true
  type?: true
}

export type RegistersCountAggregateInputType = {
  name?: true
  cpf?: true
  gender?: true
  birth?: true
  email?: true
  password?: true
  type?: true
  _all?: true
}

export type RegistersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which registers to aggregate.
   */
  where?: Prisma.registersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of registers to fetch.
   */
  orderBy?: Prisma.registersOrderByWithRelationInput | Prisma.registersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.registersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` registers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` registers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned registers
  **/
  _count?: true | RegistersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RegistersAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RegistersSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RegistersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RegistersMaxAggregateInputType
}

export type GetRegistersAggregateType<T extends RegistersAggregateArgs> = {
      [P in keyof T & keyof AggregateRegisters]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRegisters[P]>
    : Prisma.GetScalarType<T[P], AggregateRegisters[P]>
}




export type registersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.registersWhereInput
  orderBy?: Prisma.registersOrderByWithAggregationInput | Prisma.registersOrderByWithAggregationInput[]
  by: Prisma.RegistersScalarFieldEnum[] | Prisma.RegistersScalarFieldEnum
  having?: Prisma.registersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RegistersCountAggregateInputType | true
  _avg?: RegistersAvgAggregateInputType
  _sum?: RegistersSumAggregateInputType
  _min?: RegistersMinAggregateInputType
  _max?: RegistersMaxAggregateInputType
}

export type RegistersGroupByOutputType = {
  name: string
  cpf: string
  gender: string
  birth: Date
  email: string
  password: string
  type: number
  _count: RegistersCountAggregateOutputType | null
  _avg: RegistersAvgAggregateOutputType | null
  _sum: RegistersSumAggregateOutputType | null
  _min: RegistersMinAggregateOutputType | null
  _max: RegistersMaxAggregateOutputType | null
}

type GetRegistersGroupByPayload<T extends registersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RegistersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RegistersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RegistersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RegistersGroupByOutputType[P]>
      }
    >
  >



export type registersWhereInput = {
  AND?: Prisma.registersWhereInput | Prisma.registersWhereInput[]
  OR?: Prisma.registersWhereInput[]
  NOT?: Prisma.registersWhereInput | Prisma.registersWhereInput[]
  name?: Prisma.StringFilter<"registers"> | string
  cpf?: Prisma.StringFilter<"registers"> | string
  gender?: Prisma.StringFilter<"registers"> | string
  birth?: Prisma.DateTimeFilter<"registers"> | Date | string
  email?: Prisma.StringFilter<"registers"> | string
  password?: Prisma.StringFilter<"registers"> | string
  type?: Prisma.IntFilter<"registers"> | number
  appointments?: Prisma.AppointmentsListRelationFilter
  doctors?: Prisma.XOR<Prisma.DoctorsNullableScalarRelationFilter, Prisma.doctorsWhereInput> | null
}

export type registersOrderByWithRelationInput = {
  name?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  birth?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  type?: Prisma.SortOrder
  appointments?: Prisma.appointmentsOrderByRelationAggregateInput
  doctors?: Prisma.doctorsOrderByWithRelationInput
  _relevance?: Prisma.registersOrderByRelevanceInput
}

export type registersWhereUniqueInput = Prisma.AtLeast<{
  cpf?: string
  email?: string
  AND?: Prisma.registersWhereInput | Prisma.registersWhereInput[]
  OR?: Prisma.registersWhereInput[]
  NOT?: Prisma.registersWhereInput | Prisma.registersWhereInput[]
  name?: Prisma.StringFilter<"registers"> | string
  gender?: Prisma.StringFilter<"registers"> | string
  birth?: Prisma.DateTimeFilter<"registers"> | Date | string
  password?: Prisma.StringFilter<"registers"> | string
  type?: Prisma.IntFilter<"registers"> | number
  appointments?: Prisma.AppointmentsListRelationFilter
  doctors?: Prisma.XOR<Prisma.DoctorsNullableScalarRelationFilter, Prisma.doctorsWhereInput> | null
}, "email" | "cpf">

export type registersOrderByWithAggregationInput = {
  name?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  birth?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  type?: Prisma.SortOrder
  _count?: Prisma.registersCountOrderByAggregateInput
  _avg?: Prisma.registersAvgOrderByAggregateInput
  _max?: Prisma.registersMaxOrderByAggregateInput
  _min?: Prisma.registersMinOrderByAggregateInput
  _sum?: Prisma.registersSumOrderByAggregateInput
}

export type registersScalarWhereWithAggregatesInput = {
  AND?: Prisma.registersScalarWhereWithAggregatesInput | Prisma.registersScalarWhereWithAggregatesInput[]
  OR?: Prisma.registersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.registersScalarWhereWithAggregatesInput | Prisma.registersScalarWhereWithAggregatesInput[]
  name?: Prisma.StringWithAggregatesFilter<"registers"> | string
  cpf?: Prisma.StringWithAggregatesFilter<"registers"> | string
  gender?: Prisma.StringWithAggregatesFilter<"registers"> | string
  birth?: Prisma.DateTimeWithAggregatesFilter<"registers"> | Date | string
  email?: Prisma.StringWithAggregatesFilter<"registers"> | string
  password?: Prisma.StringWithAggregatesFilter<"registers"> | string
  type?: Prisma.IntWithAggregatesFilter<"registers"> | number
}

export type registersCreateInput = {
  name: string
  cpf: string
  gender: string
  birth: Date | string
  email: string
  password: string
  type: number
  appointments?: Prisma.appointmentsCreateNestedManyWithoutRegistersInput
  doctors?: Prisma.doctorsCreateNestedOneWithoutRegistersInput
}

export type registersUncheckedCreateInput = {
  name: string
  cpf: string
  gender: string
  birth: Date | string
  email: string
  password: string
  type: number
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutRegistersInput
  doctors?: Prisma.doctorsUncheckedCreateNestedOneWithoutRegistersInput
}

export type registersUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  birth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.IntFieldUpdateOperationsInput | number
  appointments?: Prisma.appointmentsUpdateManyWithoutRegistersNestedInput
  doctors?: Prisma.doctorsUpdateOneWithoutRegistersNestedInput
}

export type registersUncheckedUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  birth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.IntFieldUpdateOperationsInput | number
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutRegistersNestedInput
  doctors?: Prisma.doctorsUncheckedUpdateOneWithoutRegistersNestedInput
}

export type registersCreateManyInput = {
  name: string
  cpf: string
  gender: string
  birth: Date | string
  email: string
  password: string
  type: number
}

export type registersUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  birth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.IntFieldUpdateOperationsInput | number
}

export type registersUncheckedUpdateManyInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  birth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RegistersScalarRelationFilter = {
  is?: Prisma.registersWhereInput
  isNot?: Prisma.registersWhereInput
}

export type registersOrderByRelevanceInput = {
  fields: Prisma.registersOrderByRelevanceFieldEnum | Prisma.registersOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type registersCountOrderByAggregateInput = {
  name?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  birth?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type registersAvgOrderByAggregateInput = {
  type?: Prisma.SortOrder
}

export type registersMaxOrderByAggregateInput = {
  name?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  birth?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type registersMinOrderByAggregateInput = {
  name?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  birth?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type registersSumOrderByAggregateInput = {
  type?: Prisma.SortOrder
}

export type registersCreateNestedOneWithoutAppointmentsInput = {
  create?: Prisma.XOR<Prisma.registersCreateWithoutAppointmentsInput, Prisma.registersUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.registersCreateOrConnectWithoutAppointmentsInput
  connect?: Prisma.registersWhereUniqueInput
}

export type registersUpdateOneRequiredWithoutAppointmentsNestedInput = {
  create?: Prisma.XOR<Prisma.registersCreateWithoutAppointmentsInput, Prisma.registersUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.registersCreateOrConnectWithoutAppointmentsInput
  upsert?: Prisma.registersUpsertWithoutAppointmentsInput
  connect?: Prisma.registersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.registersUpdateToOneWithWhereWithoutAppointmentsInput, Prisma.registersUpdateWithoutAppointmentsInput>, Prisma.registersUncheckedUpdateWithoutAppointmentsInput>
}

export type registersCreateNestedOneWithoutDoctorsInput = {
  create?: Prisma.XOR<Prisma.registersCreateWithoutDoctorsInput, Prisma.registersUncheckedCreateWithoutDoctorsInput>
  connectOrCreate?: Prisma.registersCreateOrConnectWithoutDoctorsInput
  connect?: Prisma.registersWhereUniqueInput
}

export type registersUpdateOneRequiredWithoutDoctorsNestedInput = {
  create?: Prisma.XOR<Prisma.registersCreateWithoutDoctorsInput, Prisma.registersUncheckedCreateWithoutDoctorsInput>
  connectOrCreate?: Prisma.registersCreateOrConnectWithoutDoctorsInput
  upsert?: Prisma.registersUpsertWithoutDoctorsInput
  connect?: Prisma.registersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.registersUpdateToOneWithWhereWithoutDoctorsInput, Prisma.registersUpdateWithoutDoctorsInput>, Prisma.registersUncheckedUpdateWithoutDoctorsInput>
}

export type registersCreateWithoutAppointmentsInput = {
  name: string
  cpf: string
  gender: string
  birth: Date | string
  email: string
  password: string
  type: number
  doctors?: Prisma.doctorsCreateNestedOneWithoutRegistersInput
}

export type registersUncheckedCreateWithoutAppointmentsInput = {
  name: string
  cpf: string
  gender: string
  birth: Date | string
  email: string
  password: string
  type: number
  doctors?: Prisma.doctorsUncheckedCreateNestedOneWithoutRegistersInput
}

export type registersCreateOrConnectWithoutAppointmentsInput = {
  where: Prisma.registersWhereUniqueInput
  create: Prisma.XOR<Prisma.registersCreateWithoutAppointmentsInput, Prisma.registersUncheckedCreateWithoutAppointmentsInput>
}

export type registersUpsertWithoutAppointmentsInput = {
  update: Prisma.XOR<Prisma.registersUpdateWithoutAppointmentsInput, Prisma.registersUncheckedUpdateWithoutAppointmentsInput>
  create: Prisma.XOR<Prisma.registersCreateWithoutAppointmentsInput, Prisma.registersUncheckedCreateWithoutAppointmentsInput>
  where?: Prisma.registersWhereInput
}

export type registersUpdateToOneWithWhereWithoutAppointmentsInput = {
  where?: Prisma.registersWhereInput
  data: Prisma.XOR<Prisma.registersUpdateWithoutAppointmentsInput, Prisma.registersUncheckedUpdateWithoutAppointmentsInput>
}

export type registersUpdateWithoutAppointmentsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  birth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.IntFieldUpdateOperationsInput | number
  doctors?: Prisma.doctorsUpdateOneWithoutRegistersNestedInput
}

export type registersUncheckedUpdateWithoutAppointmentsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  birth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.IntFieldUpdateOperationsInput | number
  doctors?: Prisma.doctorsUncheckedUpdateOneWithoutRegistersNestedInput
}

export type registersCreateWithoutDoctorsInput = {
  name: string
  cpf: string
  gender: string
  birth: Date | string
  email: string
  password: string
  type: number
  appointments?: Prisma.appointmentsCreateNestedManyWithoutRegistersInput
}

export type registersUncheckedCreateWithoutDoctorsInput = {
  name: string
  cpf: string
  gender: string
  birth: Date | string
  email: string
  password: string
  type: number
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutRegistersInput
}

export type registersCreateOrConnectWithoutDoctorsInput = {
  where: Prisma.registersWhereUniqueInput
  create: Prisma.XOR<Prisma.registersCreateWithoutDoctorsInput, Prisma.registersUncheckedCreateWithoutDoctorsInput>
}

export type registersUpsertWithoutDoctorsInput = {
  update: Prisma.XOR<Prisma.registersUpdateWithoutDoctorsInput, Prisma.registersUncheckedUpdateWithoutDoctorsInput>
  create: Prisma.XOR<Prisma.registersCreateWithoutDoctorsInput, Prisma.registersUncheckedCreateWithoutDoctorsInput>
  where?: Prisma.registersWhereInput
}

export type registersUpdateToOneWithWhereWithoutDoctorsInput = {
  where?: Prisma.registersWhereInput
  data: Prisma.XOR<Prisma.registersUpdateWithoutDoctorsInput, Prisma.registersUncheckedUpdateWithoutDoctorsInput>
}

export type registersUpdateWithoutDoctorsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  birth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.IntFieldUpdateOperationsInput | number
  appointments?: Prisma.appointmentsUpdateManyWithoutRegistersNestedInput
}

export type registersUncheckedUpdateWithoutDoctorsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  birth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.IntFieldUpdateOperationsInput | number
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutRegistersNestedInput
}


/**
 * Count Type RegistersCountOutputType
 */

export type RegistersCountOutputType = {
  appointments: number
}

export type RegistersCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointments?: boolean | RegistersCountOutputTypeCountAppointmentsArgs
}

/**
 * RegistersCountOutputType without action
 */
export type RegistersCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegistersCountOutputType
   */
  select?: Prisma.RegistersCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RegistersCountOutputType without action
 */
export type RegistersCountOutputTypeCountAppointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.appointmentsWhereInput
}


export type registersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  cpf?: boolean
  gender?: boolean
  birth?: boolean
  email?: boolean
  password?: boolean
  type?: boolean
  appointments?: boolean | Prisma.registers$appointmentsArgs<ExtArgs>
  doctors?: boolean | Prisma.registers$doctorsArgs<ExtArgs>
  _count?: boolean | Prisma.RegistersCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["registers"]>



export type registersSelectScalar = {
  name?: boolean
  cpf?: boolean
  gender?: boolean
  birth?: boolean
  email?: boolean
  password?: boolean
  type?: boolean
}

export type registersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"name" | "cpf" | "gender" | "birth" | "email" | "password" | "type", ExtArgs["result"]["registers"]>
export type registersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointments?: boolean | Prisma.registers$appointmentsArgs<ExtArgs>
  doctors?: boolean | Prisma.registers$doctorsArgs<ExtArgs>
  _count?: boolean | Prisma.RegistersCountOutputTypeDefaultArgs<ExtArgs>
}

export type $registersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "registers"
  objects: {
    appointments: Prisma.$appointmentsPayload<ExtArgs>[]
    doctors: Prisma.$doctorsPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    name: string
    cpf: string
    gender: string
    birth: Date
    email: string
    password: string
    type: number
  }, ExtArgs["result"]["registers"]>
  composites: {}
}

export type registersGetPayload<S extends boolean | null | undefined | registersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$registersPayload, S>

export type registersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<registersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RegistersCountAggregateInputType | true
  }

export interface registersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['registers'], meta: { name: 'registers' } }
  /**
   * Find zero or one Registers that matches the filter.
   * @param {registersFindUniqueArgs} args - Arguments to find a Registers
   * @example
   * // Get one Registers
   * const registers = await prisma.registers.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends registersFindUniqueArgs>(args: Prisma.SelectSubset<T, registersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__registersClient<runtime.Types.Result.GetResult<Prisma.$registersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Registers that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {registersFindUniqueOrThrowArgs} args - Arguments to find a Registers
   * @example
   * // Get one Registers
   * const registers = await prisma.registers.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends registersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, registersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__registersClient<runtime.Types.Result.GetResult<Prisma.$registersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Registers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {registersFindFirstArgs} args - Arguments to find a Registers
   * @example
   * // Get one Registers
   * const registers = await prisma.registers.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends registersFindFirstArgs>(args?: Prisma.SelectSubset<T, registersFindFirstArgs<ExtArgs>>): Prisma.Prisma__registersClient<runtime.Types.Result.GetResult<Prisma.$registersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Registers that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {registersFindFirstOrThrowArgs} args - Arguments to find a Registers
   * @example
   * // Get one Registers
   * const registers = await prisma.registers.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends registersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, registersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__registersClient<runtime.Types.Result.GetResult<Prisma.$registersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Registers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {registersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Registers
   * const registers = await prisma.registers.findMany()
   * 
   * // Get first 10 Registers
   * const registers = await prisma.registers.findMany({ take: 10 })
   * 
   * // Only select the `name`
   * const registersWithNameOnly = await prisma.registers.findMany({ select: { name: true } })
   * 
   */
  findMany<T extends registersFindManyArgs>(args?: Prisma.SelectSubset<T, registersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$registersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Registers.
   * @param {registersCreateArgs} args - Arguments to create a Registers.
   * @example
   * // Create one Registers
   * const Registers = await prisma.registers.create({
   *   data: {
   *     // ... data to create a Registers
   *   }
   * })
   * 
   */
  create<T extends registersCreateArgs>(args: Prisma.SelectSubset<T, registersCreateArgs<ExtArgs>>): Prisma.Prisma__registersClient<runtime.Types.Result.GetResult<Prisma.$registersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Registers.
   * @param {registersCreateManyArgs} args - Arguments to create many Registers.
   * @example
   * // Create many Registers
   * const registers = await prisma.registers.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends registersCreateManyArgs>(args?: Prisma.SelectSubset<T, registersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Registers.
   * @param {registersDeleteArgs} args - Arguments to delete one Registers.
   * @example
   * // Delete one Registers
   * const Registers = await prisma.registers.delete({
   *   where: {
   *     // ... filter to delete one Registers
   *   }
   * })
   * 
   */
  delete<T extends registersDeleteArgs>(args: Prisma.SelectSubset<T, registersDeleteArgs<ExtArgs>>): Prisma.Prisma__registersClient<runtime.Types.Result.GetResult<Prisma.$registersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Registers.
   * @param {registersUpdateArgs} args - Arguments to update one Registers.
   * @example
   * // Update one Registers
   * const registers = await prisma.registers.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends registersUpdateArgs>(args: Prisma.SelectSubset<T, registersUpdateArgs<ExtArgs>>): Prisma.Prisma__registersClient<runtime.Types.Result.GetResult<Prisma.$registersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Registers.
   * @param {registersDeleteManyArgs} args - Arguments to filter Registers to delete.
   * @example
   * // Delete a few Registers
   * const { count } = await prisma.registers.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends registersDeleteManyArgs>(args?: Prisma.SelectSubset<T, registersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Registers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {registersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Registers
   * const registers = await prisma.registers.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends registersUpdateManyArgs>(args: Prisma.SelectSubset<T, registersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Registers.
   * @param {registersUpsertArgs} args - Arguments to update or create a Registers.
   * @example
   * // Update or create a Registers
   * const registers = await prisma.registers.upsert({
   *   create: {
   *     // ... data to create a Registers
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Registers we want to update
   *   }
   * })
   */
  upsert<T extends registersUpsertArgs>(args: Prisma.SelectSubset<T, registersUpsertArgs<ExtArgs>>): Prisma.Prisma__registersClient<runtime.Types.Result.GetResult<Prisma.$registersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Registers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {registersCountArgs} args - Arguments to filter Registers to count.
   * @example
   * // Count the number of Registers
   * const count = await prisma.registers.count({
   *   where: {
   *     // ... the filter for the Registers we want to count
   *   }
   * })
  **/
  count<T extends registersCountArgs>(
    args?: Prisma.Subset<T, registersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RegistersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Registers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RegistersAggregateArgs>(args: Prisma.Subset<T, RegistersAggregateArgs>): Prisma.PrismaPromise<GetRegistersAggregateType<T>>

  /**
   * Group by Registers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {registersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends registersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: registersGroupByArgs['orderBy'] }
      : { orderBy?: registersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, registersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRegistersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the registers model
 */
readonly fields: registersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for registers.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__registersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  appointments<T extends Prisma.registers$appointmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.registers$appointmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  doctors<T extends Prisma.registers$doctorsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.registers$doctorsArgs<ExtArgs>>): Prisma.Prisma__doctorsClient<runtime.Types.Result.GetResult<Prisma.$doctorsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the registers model
 */
export interface registersFieldRefs {
  readonly name: Prisma.FieldRef<"registers", 'String'>
  readonly cpf: Prisma.FieldRef<"registers", 'String'>
  readonly gender: Prisma.FieldRef<"registers", 'String'>
  readonly birth: Prisma.FieldRef<"registers", 'DateTime'>
  readonly email: Prisma.FieldRef<"registers", 'String'>
  readonly password: Prisma.FieldRef<"registers", 'String'>
  readonly type: Prisma.FieldRef<"registers", 'Int'>
}
    

// Custom InputTypes
/**
 * registers findUnique
 */
export type registersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the registers
   */
  select?: Prisma.registersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the registers
   */
  omit?: Prisma.registersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.registersInclude<ExtArgs> | null
  /**
   * Filter, which registers to fetch.
   */
  where: Prisma.registersWhereUniqueInput
}

/**
 * registers findUniqueOrThrow
 */
export type registersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the registers
   */
  select?: Prisma.registersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the registers
   */
  omit?: Prisma.registersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.registersInclude<ExtArgs> | null
  /**
   * Filter, which registers to fetch.
   */
  where: Prisma.registersWhereUniqueInput
}

/**
 * registers findFirst
 */
export type registersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the registers
   */
  select?: Prisma.registersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the registers
   */
  omit?: Prisma.registersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.registersInclude<ExtArgs> | null
  /**
   * Filter, which registers to fetch.
   */
  where?: Prisma.registersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of registers to fetch.
   */
  orderBy?: Prisma.registersOrderByWithRelationInput | Prisma.registersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for registers.
   */
  cursor?: Prisma.registersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` registers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` registers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of registers.
   */
  distinct?: Prisma.RegistersScalarFieldEnum | Prisma.RegistersScalarFieldEnum[]
}

/**
 * registers findFirstOrThrow
 */
export type registersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the registers
   */
  select?: Prisma.registersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the registers
   */
  omit?: Prisma.registersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.registersInclude<ExtArgs> | null
  /**
   * Filter, which registers to fetch.
   */
  where?: Prisma.registersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of registers to fetch.
   */
  orderBy?: Prisma.registersOrderByWithRelationInput | Prisma.registersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for registers.
   */
  cursor?: Prisma.registersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` registers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` registers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of registers.
   */
  distinct?: Prisma.RegistersScalarFieldEnum | Prisma.RegistersScalarFieldEnum[]
}

/**
 * registers findMany
 */
export type registersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the registers
   */
  select?: Prisma.registersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the registers
   */
  omit?: Prisma.registersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.registersInclude<ExtArgs> | null
  /**
   * Filter, which registers to fetch.
   */
  where?: Prisma.registersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of registers to fetch.
   */
  orderBy?: Prisma.registersOrderByWithRelationInput | Prisma.registersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing registers.
   */
  cursor?: Prisma.registersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` registers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` registers.
   */
  skip?: number
  distinct?: Prisma.RegistersScalarFieldEnum | Prisma.RegistersScalarFieldEnum[]
}

/**
 * registers create
 */
export type registersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the registers
   */
  select?: Prisma.registersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the registers
   */
  omit?: Prisma.registersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.registersInclude<ExtArgs> | null
  /**
   * The data needed to create a registers.
   */
  data: Prisma.XOR<Prisma.registersCreateInput, Prisma.registersUncheckedCreateInput>
}

/**
 * registers createMany
 */
export type registersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many registers.
   */
  data: Prisma.registersCreateManyInput | Prisma.registersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * registers update
 */
export type registersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the registers
   */
  select?: Prisma.registersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the registers
   */
  omit?: Prisma.registersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.registersInclude<ExtArgs> | null
  /**
   * The data needed to update a registers.
   */
  data: Prisma.XOR<Prisma.registersUpdateInput, Prisma.registersUncheckedUpdateInput>
  /**
   * Choose, which registers to update.
   */
  where: Prisma.registersWhereUniqueInput
}

/**
 * registers updateMany
 */
export type registersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update registers.
   */
  data: Prisma.XOR<Prisma.registersUpdateManyMutationInput, Prisma.registersUncheckedUpdateManyInput>
  /**
   * Filter which registers to update
   */
  where?: Prisma.registersWhereInput
  /**
   * Limit how many registers to update.
   */
  limit?: number
}

/**
 * registers upsert
 */
export type registersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the registers
   */
  select?: Prisma.registersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the registers
   */
  omit?: Prisma.registersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.registersInclude<ExtArgs> | null
  /**
   * The filter to search for the registers to update in case it exists.
   */
  where: Prisma.registersWhereUniqueInput
  /**
   * In case the registers found by the `where` argument doesn't exist, create a new registers with this data.
   */
  create: Prisma.XOR<Prisma.registersCreateInput, Prisma.registersUncheckedCreateInput>
  /**
   * In case the registers was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.registersUpdateInput, Prisma.registersUncheckedUpdateInput>
}

/**
 * registers delete
 */
export type registersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the registers
   */
  select?: Prisma.registersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the registers
   */
  omit?: Prisma.registersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.registersInclude<ExtArgs> | null
  /**
   * Filter which registers to delete.
   */
  where: Prisma.registersWhereUniqueInput
}

/**
 * registers deleteMany
 */
export type registersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which registers to delete
   */
  where?: Prisma.registersWhereInput
  /**
   * Limit how many registers to delete.
   */
  limit?: number
}

/**
 * registers.appointments
 */
export type registers$appointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  where?: Prisma.appointmentsWhereInput
  orderBy?: Prisma.appointmentsOrderByWithRelationInput | Prisma.appointmentsOrderByWithRelationInput[]
  cursor?: Prisma.appointmentsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AppointmentsScalarFieldEnum | Prisma.AppointmentsScalarFieldEnum[]
}

/**
 * registers.doctors
 */
export type registers$doctorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the doctors
   */
  select?: Prisma.doctorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the doctors
   */
  omit?: Prisma.doctorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.doctorsInclude<ExtArgs> | null
  where?: Prisma.doctorsWhereInput
}

/**
 * registers without action
 */
export type registersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the registers
   */
  select?: Prisma.registersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the registers
   */
  omit?: Prisma.registersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.registersInclude<ExtArgs> | null
}
