
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `weekdays` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model weekdays
 * 
 */
export type weekdaysModel = runtime.Types.Result.DefaultSelection<Prisma.$weekdaysPayload>

export type AggregateWeekdays = {
  _count: WeekdaysCountAggregateOutputType | null
  _avg: WeekdaysAvgAggregateOutputType | null
  _sum: WeekdaysSumAggregateOutputType | null
  _min: WeekdaysMinAggregateOutputType | null
  _max: WeekdaysMaxAggregateOutputType | null
}

export type WeekdaysAvgAggregateOutputType = {
  id_expedient: number | null
  weekday: number | null
  week: number | null
}

export type WeekdaysSumAggregateOutputType = {
  id_expedient: number | null
  weekday: number | null
  week: number | null
}

export type WeekdaysMinAggregateOutputType = {
  id_expedient: number | null
  weekday: number | null
  week: number | null
  start: Date | null
  end: Date | null
  break: Date | null
  time_break: Date | null
}

export type WeekdaysMaxAggregateOutputType = {
  id_expedient: number | null
  weekday: number | null
  week: number | null
  start: Date | null
  end: Date | null
  break: Date | null
  time_break: Date | null
}

export type WeekdaysCountAggregateOutputType = {
  id_expedient: number
  weekday: number
  week: number
  start: number
  end: number
  break: number
  time_break: number
  _all: number
}


export type WeekdaysAvgAggregateInputType = {
  id_expedient?: true
  weekday?: true
  week?: true
}

export type WeekdaysSumAggregateInputType = {
  id_expedient?: true
  weekday?: true
  week?: true
}

export type WeekdaysMinAggregateInputType = {
  id_expedient?: true
  weekday?: true
  week?: true
  start?: true
  end?: true
  break?: true
  time_break?: true
}

export type WeekdaysMaxAggregateInputType = {
  id_expedient?: true
  weekday?: true
  week?: true
  start?: true
  end?: true
  break?: true
  time_break?: true
}

export type WeekdaysCountAggregateInputType = {
  id_expedient?: true
  weekday?: true
  week?: true
  start?: true
  end?: true
  break?: true
  time_break?: true
  _all?: true
}

export type WeekdaysAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which weekdays to aggregate.
   */
  where?: Prisma.weekdaysWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of weekdays to fetch.
   */
  orderBy?: Prisma.weekdaysOrderByWithRelationInput | Prisma.weekdaysOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.weekdaysWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` weekdays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` weekdays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned weekdays
  **/
  _count?: true | WeekdaysCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WeekdaysAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WeekdaysSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WeekdaysMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WeekdaysMaxAggregateInputType
}

export type GetWeekdaysAggregateType<T extends WeekdaysAggregateArgs> = {
      [P in keyof T & keyof AggregateWeekdays]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWeekdays[P]>
    : Prisma.GetScalarType<T[P], AggregateWeekdays[P]>
}




export type weekdaysGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.weekdaysWhereInput
  orderBy?: Prisma.weekdaysOrderByWithAggregationInput | Prisma.weekdaysOrderByWithAggregationInput[]
  by: Prisma.WeekdaysScalarFieldEnum[] | Prisma.WeekdaysScalarFieldEnum
  having?: Prisma.weekdaysScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WeekdaysCountAggregateInputType | true
  _avg?: WeekdaysAvgAggregateInputType
  _sum?: WeekdaysSumAggregateInputType
  _min?: WeekdaysMinAggregateInputType
  _max?: WeekdaysMaxAggregateInputType
}

export type WeekdaysGroupByOutputType = {
  id_expedient: number
  weekday: number
  week: number
  start: Date
  end: Date
  break: Date | null
  time_break: Date | null
  _count: WeekdaysCountAggregateOutputType | null
  _avg: WeekdaysAvgAggregateOutputType | null
  _sum: WeekdaysSumAggregateOutputType | null
  _min: WeekdaysMinAggregateOutputType | null
  _max: WeekdaysMaxAggregateOutputType | null
}

type GetWeekdaysGroupByPayload<T extends weekdaysGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WeekdaysGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WeekdaysGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WeekdaysGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WeekdaysGroupByOutputType[P]>
      }
    >
  >



export type weekdaysWhereInput = {
  AND?: Prisma.weekdaysWhereInput | Prisma.weekdaysWhereInput[]
  OR?: Prisma.weekdaysWhereInput[]
  NOT?: Prisma.weekdaysWhereInput | Prisma.weekdaysWhereInput[]
  id_expedient?: Prisma.IntFilter<"weekdays"> | number
  weekday?: Prisma.IntFilter<"weekdays"> | number
  week?: Prisma.IntFilter<"weekdays"> | number
  start?: Prisma.DateTimeFilter<"weekdays"> | Date | string
  end?: Prisma.DateTimeFilter<"weekdays"> | Date | string
  break?: Prisma.DateTimeNullableFilter<"weekdays"> | Date | string | null
  time_break?: Prisma.DateTimeNullableFilter<"weekdays"> | Date | string | null
  expedients?: Prisma.XOR<Prisma.ExpedientsScalarRelationFilter, Prisma.expedientsWhereInput>
}

export type weekdaysOrderByWithRelationInput = {
  id_expedient?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
  week?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
  break?: Prisma.SortOrderInput | Prisma.SortOrder
  time_break?: Prisma.SortOrderInput | Prisma.SortOrder
  expedients?: Prisma.expedientsOrderByWithRelationInput
}

export type weekdaysWhereUniqueInput = Prisma.AtLeast<{
  id_expedient_weekday_week?: Prisma.weekdaysId_expedientWeekdayWeekCompoundUniqueInput
  AND?: Prisma.weekdaysWhereInput | Prisma.weekdaysWhereInput[]
  OR?: Prisma.weekdaysWhereInput[]
  NOT?: Prisma.weekdaysWhereInput | Prisma.weekdaysWhereInput[]
  id_expedient?: Prisma.IntFilter<"weekdays"> | number
  weekday?: Prisma.IntFilter<"weekdays"> | number
  week?: Prisma.IntFilter<"weekdays"> | number
  start?: Prisma.DateTimeFilter<"weekdays"> | Date | string
  end?: Prisma.DateTimeFilter<"weekdays"> | Date | string
  break?: Prisma.DateTimeNullableFilter<"weekdays"> | Date | string | null
  time_break?: Prisma.DateTimeNullableFilter<"weekdays"> | Date | string | null
  expedients?: Prisma.XOR<Prisma.ExpedientsScalarRelationFilter, Prisma.expedientsWhereInput>
}, "id_expedient_weekday_week">

export type weekdaysOrderByWithAggregationInput = {
  id_expedient?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
  week?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
  break?: Prisma.SortOrderInput | Prisma.SortOrder
  time_break?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.weekdaysCountOrderByAggregateInput
  _avg?: Prisma.weekdaysAvgOrderByAggregateInput
  _max?: Prisma.weekdaysMaxOrderByAggregateInput
  _min?: Prisma.weekdaysMinOrderByAggregateInput
  _sum?: Prisma.weekdaysSumOrderByAggregateInput
}

export type weekdaysScalarWhereWithAggregatesInput = {
  AND?: Prisma.weekdaysScalarWhereWithAggregatesInput | Prisma.weekdaysScalarWhereWithAggregatesInput[]
  OR?: Prisma.weekdaysScalarWhereWithAggregatesInput[]
  NOT?: Prisma.weekdaysScalarWhereWithAggregatesInput | Prisma.weekdaysScalarWhereWithAggregatesInput[]
  id_expedient?: Prisma.IntWithAggregatesFilter<"weekdays"> | number
  weekday?: Prisma.IntWithAggregatesFilter<"weekdays"> | number
  week?: Prisma.IntWithAggregatesFilter<"weekdays"> | number
  start?: Prisma.DateTimeWithAggregatesFilter<"weekdays"> | Date | string
  end?: Prisma.DateTimeWithAggregatesFilter<"weekdays"> | Date | string
  break?: Prisma.DateTimeNullableWithAggregatesFilter<"weekdays"> | Date | string | null
  time_break?: Prisma.DateTimeNullableWithAggregatesFilter<"weekdays"> | Date | string | null
}

export type weekdaysCreateInput = {
  weekday: number
  week?: number
  start: Date | string
  end: Date | string
  break?: Date | string | null
  time_break?: Date | string | null
  expedients: Prisma.expedientsCreateNestedOneWithoutWeekdaysInput
}

export type weekdaysUncheckedCreateInput = {
  id_expedient: number
  weekday: number
  week?: number
  start: Date | string
  end: Date | string
  break?: Date | string | null
  time_break?: Date | string | null
}

export type weekdaysUpdateInput = {
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  week?: Prisma.IntFieldUpdateOperationsInput | number
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time_break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expedients?: Prisma.expedientsUpdateOneRequiredWithoutWeekdaysNestedInput
}

export type weekdaysUncheckedUpdateInput = {
  id_expedient?: Prisma.IntFieldUpdateOperationsInput | number
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  week?: Prisma.IntFieldUpdateOperationsInput | number
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time_break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type weekdaysCreateManyInput = {
  id_expedient: number
  weekday: number
  week?: number
  start: Date | string
  end: Date | string
  break?: Date | string | null
  time_break?: Date | string | null
}

export type weekdaysUpdateManyMutationInput = {
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  week?: Prisma.IntFieldUpdateOperationsInput | number
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time_break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type weekdaysUncheckedUpdateManyInput = {
  id_expedient?: Prisma.IntFieldUpdateOperationsInput | number
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  week?: Prisma.IntFieldUpdateOperationsInput | number
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time_break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type WeekdaysListRelationFilter = {
  every?: Prisma.weekdaysWhereInput
  some?: Prisma.weekdaysWhereInput
  none?: Prisma.weekdaysWhereInput
}

export type weekdaysOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type weekdaysId_expedientWeekdayWeekCompoundUniqueInput = {
  id_expedient: number
  weekday: number
  week: number
}

export type weekdaysCountOrderByAggregateInput = {
  id_expedient?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
  week?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
  break?: Prisma.SortOrder
  time_break?: Prisma.SortOrder
}

export type weekdaysAvgOrderByAggregateInput = {
  id_expedient?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
  week?: Prisma.SortOrder
}

export type weekdaysMaxOrderByAggregateInput = {
  id_expedient?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
  week?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
  break?: Prisma.SortOrder
  time_break?: Prisma.SortOrder
}

export type weekdaysMinOrderByAggregateInput = {
  id_expedient?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
  week?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
  break?: Prisma.SortOrder
  time_break?: Prisma.SortOrder
}

export type weekdaysSumOrderByAggregateInput = {
  id_expedient?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
  week?: Prisma.SortOrder
}

export type weekdaysCreateNestedManyWithoutExpedientsInput = {
  create?: Prisma.XOR<Prisma.weekdaysCreateWithoutExpedientsInput, Prisma.weekdaysUncheckedCreateWithoutExpedientsInput> | Prisma.weekdaysCreateWithoutExpedientsInput[] | Prisma.weekdaysUncheckedCreateWithoutExpedientsInput[]
  connectOrCreate?: Prisma.weekdaysCreateOrConnectWithoutExpedientsInput | Prisma.weekdaysCreateOrConnectWithoutExpedientsInput[]
  createMany?: Prisma.weekdaysCreateManyExpedientsInputEnvelope
  connect?: Prisma.weekdaysWhereUniqueInput | Prisma.weekdaysWhereUniqueInput[]
}

export type weekdaysUncheckedCreateNestedManyWithoutExpedientsInput = {
  create?: Prisma.XOR<Prisma.weekdaysCreateWithoutExpedientsInput, Prisma.weekdaysUncheckedCreateWithoutExpedientsInput> | Prisma.weekdaysCreateWithoutExpedientsInput[] | Prisma.weekdaysUncheckedCreateWithoutExpedientsInput[]
  connectOrCreate?: Prisma.weekdaysCreateOrConnectWithoutExpedientsInput | Prisma.weekdaysCreateOrConnectWithoutExpedientsInput[]
  createMany?: Prisma.weekdaysCreateManyExpedientsInputEnvelope
  connect?: Prisma.weekdaysWhereUniqueInput | Prisma.weekdaysWhereUniqueInput[]
}

export type weekdaysUpdateManyWithoutExpedientsNestedInput = {
  create?: Prisma.XOR<Prisma.weekdaysCreateWithoutExpedientsInput, Prisma.weekdaysUncheckedCreateWithoutExpedientsInput> | Prisma.weekdaysCreateWithoutExpedientsInput[] | Prisma.weekdaysUncheckedCreateWithoutExpedientsInput[]
  connectOrCreate?: Prisma.weekdaysCreateOrConnectWithoutExpedientsInput | Prisma.weekdaysCreateOrConnectWithoutExpedientsInput[]
  upsert?: Prisma.weekdaysUpsertWithWhereUniqueWithoutExpedientsInput | Prisma.weekdaysUpsertWithWhereUniqueWithoutExpedientsInput[]
  createMany?: Prisma.weekdaysCreateManyExpedientsInputEnvelope
  set?: Prisma.weekdaysWhereUniqueInput | Prisma.weekdaysWhereUniqueInput[]
  disconnect?: Prisma.weekdaysWhereUniqueInput | Prisma.weekdaysWhereUniqueInput[]
  delete?: Prisma.weekdaysWhereUniqueInput | Prisma.weekdaysWhereUniqueInput[]
  connect?: Prisma.weekdaysWhereUniqueInput | Prisma.weekdaysWhereUniqueInput[]
  update?: Prisma.weekdaysUpdateWithWhereUniqueWithoutExpedientsInput | Prisma.weekdaysUpdateWithWhereUniqueWithoutExpedientsInput[]
  updateMany?: Prisma.weekdaysUpdateManyWithWhereWithoutExpedientsInput | Prisma.weekdaysUpdateManyWithWhereWithoutExpedientsInput[]
  deleteMany?: Prisma.weekdaysScalarWhereInput | Prisma.weekdaysScalarWhereInput[]
}

export type weekdaysUncheckedUpdateManyWithoutExpedientsNestedInput = {
  create?: Prisma.XOR<Prisma.weekdaysCreateWithoutExpedientsInput, Prisma.weekdaysUncheckedCreateWithoutExpedientsInput> | Prisma.weekdaysCreateWithoutExpedientsInput[] | Prisma.weekdaysUncheckedCreateWithoutExpedientsInput[]
  connectOrCreate?: Prisma.weekdaysCreateOrConnectWithoutExpedientsInput | Prisma.weekdaysCreateOrConnectWithoutExpedientsInput[]
  upsert?: Prisma.weekdaysUpsertWithWhereUniqueWithoutExpedientsInput | Prisma.weekdaysUpsertWithWhereUniqueWithoutExpedientsInput[]
  createMany?: Prisma.weekdaysCreateManyExpedientsInputEnvelope
  set?: Prisma.weekdaysWhereUniqueInput | Prisma.weekdaysWhereUniqueInput[]
  disconnect?: Prisma.weekdaysWhereUniqueInput | Prisma.weekdaysWhereUniqueInput[]
  delete?: Prisma.weekdaysWhereUniqueInput | Prisma.weekdaysWhereUniqueInput[]
  connect?: Prisma.weekdaysWhereUniqueInput | Prisma.weekdaysWhereUniqueInput[]
  update?: Prisma.weekdaysUpdateWithWhereUniqueWithoutExpedientsInput | Prisma.weekdaysUpdateWithWhereUniqueWithoutExpedientsInput[]
  updateMany?: Prisma.weekdaysUpdateManyWithWhereWithoutExpedientsInput | Prisma.weekdaysUpdateManyWithWhereWithoutExpedientsInput[]
  deleteMany?: Prisma.weekdaysScalarWhereInput | Prisma.weekdaysScalarWhereInput[]
}

export type weekdaysCreateWithoutExpedientsInput = {
  weekday: number
  week?: number
  start: Date | string
  end: Date | string
  break?: Date | string | null
  time_break?: Date | string | null
}

export type weekdaysUncheckedCreateWithoutExpedientsInput = {
  weekday: number
  week?: number
  start: Date | string
  end: Date | string
  break?: Date | string | null
  time_break?: Date | string | null
}

export type weekdaysCreateOrConnectWithoutExpedientsInput = {
  where: Prisma.weekdaysWhereUniqueInput
  create: Prisma.XOR<Prisma.weekdaysCreateWithoutExpedientsInput, Prisma.weekdaysUncheckedCreateWithoutExpedientsInput>
}

export type weekdaysCreateManyExpedientsInputEnvelope = {
  data: Prisma.weekdaysCreateManyExpedientsInput | Prisma.weekdaysCreateManyExpedientsInput[]
  skipDuplicates?: boolean
}

export type weekdaysUpsertWithWhereUniqueWithoutExpedientsInput = {
  where: Prisma.weekdaysWhereUniqueInput
  update: Prisma.XOR<Prisma.weekdaysUpdateWithoutExpedientsInput, Prisma.weekdaysUncheckedUpdateWithoutExpedientsInput>
  create: Prisma.XOR<Prisma.weekdaysCreateWithoutExpedientsInput, Prisma.weekdaysUncheckedCreateWithoutExpedientsInput>
}

export type weekdaysUpdateWithWhereUniqueWithoutExpedientsInput = {
  where: Prisma.weekdaysWhereUniqueInput
  data: Prisma.XOR<Prisma.weekdaysUpdateWithoutExpedientsInput, Prisma.weekdaysUncheckedUpdateWithoutExpedientsInput>
}

export type weekdaysUpdateManyWithWhereWithoutExpedientsInput = {
  where: Prisma.weekdaysScalarWhereInput
  data: Prisma.XOR<Prisma.weekdaysUpdateManyMutationInput, Prisma.weekdaysUncheckedUpdateManyWithoutExpedientsInput>
}

export type weekdaysScalarWhereInput = {
  AND?: Prisma.weekdaysScalarWhereInput | Prisma.weekdaysScalarWhereInput[]
  OR?: Prisma.weekdaysScalarWhereInput[]
  NOT?: Prisma.weekdaysScalarWhereInput | Prisma.weekdaysScalarWhereInput[]
  id_expedient?: Prisma.IntFilter<"weekdays"> | number
  weekday?: Prisma.IntFilter<"weekdays"> | number
  week?: Prisma.IntFilter<"weekdays"> | number
  start?: Prisma.DateTimeFilter<"weekdays"> | Date | string
  end?: Prisma.DateTimeFilter<"weekdays"> | Date | string
  break?: Prisma.DateTimeNullableFilter<"weekdays"> | Date | string | null
  time_break?: Prisma.DateTimeNullableFilter<"weekdays"> | Date | string | null
}

export type weekdaysCreateManyExpedientsInput = {
  weekday: number
  week?: number
  start: Date | string
  end: Date | string
  break?: Date | string | null
  time_break?: Date | string | null
}

export type weekdaysUpdateWithoutExpedientsInput = {
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  week?: Prisma.IntFieldUpdateOperationsInput | number
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time_break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type weekdaysUncheckedUpdateWithoutExpedientsInput = {
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  week?: Prisma.IntFieldUpdateOperationsInput | number
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time_break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type weekdaysUncheckedUpdateManyWithoutExpedientsInput = {
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  week?: Prisma.IntFieldUpdateOperationsInput | number
  start?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time_break?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type weekdaysSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_expedient?: boolean
  weekday?: boolean
  week?: boolean
  start?: boolean
  end?: boolean
  break?: boolean
  time_break?: boolean
  expedients?: boolean | Prisma.expedientsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["weekdays"]>



export type weekdaysSelectScalar = {
  id_expedient?: boolean
  weekday?: boolean
  week?: boolean
  start?: boolean
  end?: boolean
  break?: boolean
  time_break?: boolean
}

export type weekdaysOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id_expedient" | "weekday" | "week" | "start" | "end" | "break" | "time_break", ExtArgs["result"]["weekdays"]>
export type weekdaysInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  expedients?: boolean | Prisma.expedientsDefaultArgs<ExtArgs>
}

export type $weekdaysPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "weekdays"
  objects: {
    expedients: Prisma.$expedientsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id_expedient: number
    weekday: number
    week: number
    start: Date
    end: Date
    break: Date | null
    time_break: Date | null
  }, ExtArgs["result"]["weekdays"]>
  composites: {}
}

export type weekdaysGetPayload<S extends boolean | null | undefined | weekdaysDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$weekdaysPayload, S>

export type weekdaysCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<weekdaysFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WeekdaysCountAggregateInputType | true
  }

export interface weekdaysDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['weekdays'], meta: { name: 'weekdays' } }
  /**
   * Find zero or one Weekdays that matches the filter.
   * @param {weekdaysFindUniqueArgs} args - Arguments to find a Weekdays
   * @example
   * // Get one Weekdays
   * const weekdays = await prisma.weekdays.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends weekdaysFindUniqueArgs>(args: Prisma.SelectSubset<T, weekdaysFindUniqueArgs<ExtArgs>>): Prisma.Prisma__weekdaysClient<runtime.Types.Result.GetResult<Prisma.$weekdaysPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Weekdays that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {weekdaysFindUniqueOrThrowArgs} args - Arguments to find a Weekdays
   * @example
   * // Get one Weekdays
   * const weekdays = await prisma.weekdays.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends weekdaysFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, weekdaysFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__weekdaysClient<runtime.Types.Result.GetResult<Prisma.$weekdaysPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Weekdays that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {weekdaysFindFirstArgs} args - Arguments to find a Weekdays
   * @example
   * // Get one Weekdays
   * const weekdays = await prisma.weekdays.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends weekdaysFindFirstArgs>(args?: Prisma.SelectSubset<T, weekdaysFindFirstArgs<ExtArgs>>): Prisma.Prisma__weekdaysClient<runtime.Types.Result.GetResult<Prisma.$weekdaysPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Weekdays that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {weekdaysFindFirstOrThrowArgs} args - Arguments to find a Weekdays
   * @example
   * // Get one Weekdays
   * const weekdays = await prisma.weekdays.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends weekdaysFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, weekdaysFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__weekdaysClient<runtime.Types.Result.GetResult<Prisma.$weekdaysPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Weekdays that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {weekdaysFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Weekdays
   * const weekdays = await prisma.weekdays.findMany()
   * 
   * // Get first 10 Weekdays
   * const weekdays = await prisma.weekdays.findMany({ take: 10 })
   * 
   * // Only select the `id_expedient`
   * const weekdaysWithId_expedientOnly = await prisma.weekdays.findMany({ select: { id_expedient: true } })
   * 
   */
  findMany<T extends weekdaysFindManyArgs>(args?: Prisma.SelectSubset<T, weekdaysFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$weekdaysPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Weekdays.
   * @param {weekdaysCreateArgs} args - Arguments to create a Weekdays.
   * @example
   * // Create one Weekdays
   * const Weekdays = await prisma.weekdays.create({
   *   data: {
   *     // ... data to create a Weekdays
   *   }
   * })
   * 
   */
  create<T extends weekdaysCreateArgs>(args: Prisma.SelectSubset<T, weekdaysCreateArgs<ExtArgs>>): Prisma.Prisma__weekdaysClient<runtime.Types.Result.GetResult<Prisma.$weekdaysPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Weekdays.
   * @param {weekdaysCreateManyArgs} args - Arguments to create many Weekdays.
   * @example
   * // Create many Weekdays
   * const weekdays = await prisma.weekdays.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends weekdaysCreateManyArgs>(args?: Prisma.SelectSubset<T, weekdaysCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Weekdays.
   * @param {weekdaysDeleteArgs} args - Arguments to delete one Weekdays.
   * @example
   * // Delete one Weekdays
   * const Weekdays = await prisma.weekdays.delete({
   *   where: {
   *     // ... filter to delete one Weekdays
   *   }
   * })
   * 
   */
  delete<T extends weekdaysDeleteArgs>(args: Prisma.SelectSubset<T, weekdaysDeleteArgs<ExtArgs>>): Prisma.Prisma__weekdaysClient<runtime.Types.Result.GetResult<Prisma.$weekdaysPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Weekdays.
   * @param {weekdaysUpdateArgs} args - Arguments to update one Weekdays.
   * @example
   * // Update one Weekdays
   * const weekdays = await prisma.weekdays.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends weekdaysUpdateArgs>(args: Prisma.SelectSubset<T, weekdaysUpdateArgs<ExtArgs>>): Prisma.Prisma__weekdaysClient<runtime.Types.Result.GetResult<Prisma.$weekdaysPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Weekdays.
   * @param {weekdaysDeleteManyArgs} args - Arguments to filter Weekdays to delete.
   * @example
   * // Delete a few Weekdays
   * const { count } = await prisma.weekdays.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends weekdaysDeleteManyArgs>(args?: Prisma.SelectSubset<T, weekdaysDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Weekdays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {weekdaysUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Weekdays
   * const weekdays = await prisma.weekdays.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends weekdaysUpdateManyArgs>(args: Prisma.SelectSubset<T, weekdaysUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Weekdays.
   * @param {weekdaysUpsertArgs} args - Arguments to update or create a Weekdays.
   * @example
   * // Update or create a Weekdays
   * const weekdays = await prisma.weekdays.upsert({
   *   create: {
   *     // ... data to create a Weekdays
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Weekdays we want to update
   *   }
   * })
   */
  upsert<T extends weekdaysUpsertArgs>(args: Prisma.SelectSubset<T, weekdaysUpsertArgs<ExtArgs>>): Prisma.Prisma__weekdaysClient<runtime.Types.Result.GetResult<Prisma.$weekdaysPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Weekdays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {weekdaysCountArgs} args - Arguments to filter Weekdays to count.
   * @example
   * // Count the number of Weekdays
   * const count = await prisma.weekdays.count({
   *   where: {
   *     // ... the filter for the Weekdays we want to count
   *   }
   * })
  **/
  count<T extends weekdaysCountArgs>(
    args?: Prisma.Subset<T, weekdaysCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WeekdaysCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Weekdays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WeekdaysAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WeekdaysAggregateArgs>(args: Prisma.Subset<T, WeekdaysAggregateArgs>): Prisma.PrismaPromise<GetWeekdaysAggregateType<T>>

  /**
   * Group by Weekdays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {weekdaysGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends weekdaysGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: weekdaysGroupByArgs['orderBy'] }
      : { orderBy?: weekdaysGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, weekdaysGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWeekdaysGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the weekdays model
 */
readonly fields: weekdaysFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for weekdays.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__weekdaysClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  expedients<T extends Prisma.expedientsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.expedientsDefaultArgs<ExtArgs>>): Prisma.Prisma__expedientsClient<runtime.Types.Result.GetResult<Prisma.$expedientsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the weekdays model
 */
export interface weekdaysFieldRefs {
  readonly id_expedient: Prisma.FieldRef<"weekdays", 'Int'>
  readonly weekday: Prisma.FieldRef<"weekdays", 'Int'>
  readonly week: Prisma.FieldRef<"weekdays", 'Int'>
  readonly start: Prisma.FieldRef<"weekdays", 'DateTime'>
  readonly end: Prisma.FieldRef<"weekdays", 'DateTime'>
  readonly break: Prisma.FieldRef<"weekdays", 'DateTime'>
  readonly time_break: Prisma.FieldRef<"weekdays", 'DateTime'>
}
    

// Custom InputTypes
/**
 * weekdays findUnique
 */
export type weekdaysFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the weekdays
   */
  select?: Prisma.weekdaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the weekdays
   */
  omit?: Prisma.weekdaysOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.weekdaysInclude<ExtArgs> | null
  /**
   * Filter, which weekdays to fetch.
   */
  where: Prisma.weekdaysWhereUniqueInput
}

/**
 * weekdays findUniqueOrThrow
 */
export type weekdaysFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the weekdays
   */
  select?: Prisma.weekdaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the weekdays
   */
  omit?: Prisma.weekdaysOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.weekdaysInclude<ExtArgs> | null
  /**
   * Filter, which weekdays to fetch.
   */
  where: Prisma.weekdaysWhereUniqueInput
}

/**
 * weekdays findFirst
 */
export type weekdaysFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the weekdays
   */
  select?: Prisma.weekdaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the weekdays
   */
  omit?: Prisma.weekdaysOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.weekdaysInclude<ExtArgs> | null
  /**
   * Filter, which weekdays to fetch.
   */
  where?: Prisma.weekdaysWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of weekdays to fetch.
   */
  orderBy?: Prisma.weekdaysOrderByWithRelationInput | Prisma.weekdaysOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for weekdays.
   */
  cursor?: Prisma.weekdaysWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` weekdays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` weekdays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of weekdays.
   */
  distinct?: Prisma.WeekdaysScalarFieldEnum | Prisma.WeekdaysScalarFieldEnum[]
}

/**
 * weekdays findFirstOrThrow
 */
export type weekdaysFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the weekdays
   */
  select?: Prisma.weekdaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the weekdays
   */
  omit?: Prisma.weekdaysOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.weekdaysInclude<ExtArgs> | null
  /**
   * Filter, which weekdays to fetch.
   */
  where?: Prisma.weekdaysWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of weekdays to fetch.
   */
  orderBy?: Prisma.weekdaysOrderByWithRelationInput | Prisma.weekdaysOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for weekdays.
   */
  cursor?: Prisma.weekdaysWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` weekdays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` weekdays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of weekdays.
   */
  distinct?: Prisma.WeekdaysScalarFieldEnum | Prisma.WeekdaysScalarFieldEnum[]
}

/**
 * weekdays findMany
 */
export type weekdaysFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the weekdays
   */
  select?: Prisma.weekdaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the weekdays
   */
  omit?: Prisma.weekdaysOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.weekdaysInclude<ExtArgs> | null
  /**
   * Filter, which weekdays to fetch.
   */
  where?: Prisma.weekdaysWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of weekdays to fetch.
   */
  orderBy?: Prisma.weekdaysOrderByWithRelationInput | Prisma.weekdaysOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing weekdays.
   */
  cursor?: Prisma.weekdaysWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` weekdays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` weekdays.
   */
  skip?: number
  distinct?: Prisma.WeekdaysScalarFieldEnum | Prisma.WeekdaysScalarFieldEnum[]
}

/**
 * weekdays create
 */
export type weekdaysCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the weekdays
   */
  select?: Prisma.weekdaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the weekdays
   */
  omit?: Prisma.weekdaysOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.weekdaysInclude<ExtArgs> | null
  /**
   * The data needed to create a weekdays.
   */
  data: Prisma.XOR<Prisma.weekdaysCreateInput, Prisma.weekdaysUncheckedCreateInput>
}

/**
 * weekdays createMany
 */
export type weekdaysCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many weekdays.
   */
  data: Prisma.weekdaysCreateManyInput | Prisma.weekdaysCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * weekdays update
 */
export type weekdaysUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the weekdays
   */
  select?: Prisma.weekdaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the weekdays
   */
  omit?: Prisma.weekdaysOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.weekdaysInclude<ExtArgs> | null
  /**
   * The data needed to update a weekdays.
   */
  data: Prisma.XOR<Prisma.weekdaysUpdateInput, Prisma.weekdaysUncheckedUpdateInput>
  /**
   * Choose, which weekdays to update.
   */
  where: Prisma.weekdaysWhereUniqueInput
}

/**
 * weekdays updateMany
 */
export type weekdaysUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update weekdays.
   */
  data: Prisma.XOR<Prisma.weekdaysUpdateManyMutationInput, Prisma.weekdaysUncheckedUpdateManyInput>
  /**
   * Filter which weekdays to update
   */
  where?: Prisma.weekdaysWhereInput
  /**
   * Limit how many weekdays to update.
   */
  limit?: number
}

/**
 * weekdays upsert
 */
export type weekdaysUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the weekdays
   */
  select?: Prisma.weekdaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the weekdays
   */
  omit?: Prisma.weekdaysOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.weekdaysInclude<ExtArgs> | null
  /**
   * The filter to search for the weekdays to update in case it exists.
   */
  where: Prisma.weekdaysWhereUniqueInput
  /**
   * In case the weekdays found by the `where` argument doesn't exist, create a new weekdays with this data.
   */
  create: Prisma.XOR<Prisma.weekdaysCreateInput, Prisma.weekdaysUncheckedCreateInput>
  /**
   * In case the weekdays was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.weekdaysUpdateInput, Prisma.weekdaysUncheckedUpdateInput>
}

/**
 * weekdays delete
 */
export type weekdaysDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the weekdays
   */
  select?: Prisma.weekdaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the weekdays
   */
  omit?: Prisma.weekdaysOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.weekdaysInclude<ExtArgs> | null
  /**
   * Filter which weekdays to delete.
   */
  where: Prisma.weekdaysWhereUniqueInput
}

/**
 * weekdays deleteMany
 */
export type weekdaysDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which weekdays to delete
   */
  where?: Prisma.weekdaysWhereInput
  /**
   * Limit how many weekdays to delete.
   */
  limit?: number
}

/**
 * weekdays without action
 */
export type weekdaysDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the weekdays
   */
  select?: Prisma.weekdaysSelect<ExtArgs> | null
  /**
   * Omit specific fields from the weekdays
   */
  omit?: Prisma.weekdaysOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.weekdaysInclude<ExtArgs> | null
}
